// Code generated by velox. DO NOT EDIT.

package filter

import (
	"errors"
	"fmt"

	gqlrelay "github.com/syssam/velox/contrib/graphql/gqlrelay"
	"github.com/syssam/velox/tests/integration/predicate"
	"github.com/syssam/velox/tests/integration/query"
	"github.com/syssam/velox/tests/integration/user"
)

// UserWhereInput represents a where input for filtering User queries.
type UserWhereInput struct {
	Predicates []predicate.User  `json:"-"`
	Not        *UserWhereInput   `json:"not,omitempty"`
	Or         []*UserWhereInput `json:"or,omitempty"`
	And        []*UserWhereInput `json:"and,omitempty"`

	// "name" field predicates.
	Name         *string  `json:"name,omitempty"`
	NameNEQ      *string  `json:"nameNEQ,omitempty"`
	NameIn       []string `json:"nameIn,omitempty"`
	NameNotIn    []string `json:"nameNotIn,omitempty"`
	NameContains *string  `json:"nameContains,omitempty"`

	// "email" field predicates.
	Email         *string  `json:"email,omitempty"`
	EmailNEQ      *string  `json:"emailNEQ,omitempty"`
	EmailIn       []string `json:"emailIn,omitempty"`
	EmailNotIn    []string `json:"emailNotIn,omitempty"`
	EmailContains *string  `json:"emailContains,omitempty"`

	// "role" field predicates.
	Role      *user.Role  `json:"role,omitempty"`
	RoleNEQ   *user.Role  `json:"roleNEQ,omitempty"`
	RoleIn    []user.Role `json:"roleIn,omitempty"`
	RoleNotIn []user.Role `json:"roleNotIn,omitempty"`

	// "posts" edge predicates.
	HasPosts     *bool             `json:"hasPosts,omitempty"`
	HasPostsWith []*PostWhereInput `json:"hasPostsWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *UserWhereInput) AddPredicates(predicates ...predicate.User) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the UserWhereInput filter on the UserQuery builder.
func (i *UserWhereInput) Filter(q *query.UserQuery) (*query.UserQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyUserWhereInput {
			return q, nil
		}
		return nil, err
	}
	q.Where(p)
	return q, nil
}

// ErrEmptyUserWhereInput is returned in case the UserWhereInput is empty.
var ErrEmptyUserWhereInput = errors.New("velox: empty predicate UserWhereInput")

// P returns a predicate for filtering users.
// An error is returned if the input is empty or invalid.
func (i *UserWhereInput) P() (predicate.User, error) {
	return i.p(0)
}

func (i *UserWhereInput) p(depth int) (predicate.User, error) {
	if depth > DefaultMaxFilterDepth {
		return nil, fmt.Errorf("%w: maximum depth is %d", ErrFilterDepthExceeded, DefaultMaxFilterDepth)
	}
	var predicates []predicate.User
	if i.Not != nil {
		p, err := i.Not.p(depth + 1)
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, user.Not(p))
	}
	if len(i.Or) > 0 {
		or := make([]predicate.User, 0, len(i.Or))
		for _, w := range i.Or {
			if w == nil {
				continue
			}
			p, err := w.p(depth + 1)
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		if len(or) > 0 {
			predicates = append(predicates, user.Or(or...))
		}
	}
	if len(i.And) > 0 {
		and := make([]predicate.User, 0, len(i.And))
		for _, w := range i.And {
			if w == nil {
				continue
			}
			p, err := w.p(depth + 1)
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		if len(and) > 0 {
			predicates = append(predicates, user.And(and...))
		}
	}
	predicates = append(predicates, i.Predicates...)
	predicates = gqlrelay.AppendIf(predicates, i.Name, user.NameField.EQ)
	predicates = gqlrelay.AppendIf(predicates, i.NameNEQ, user.NameField.NEQ)
	predicates = gqlrelay.AppendSlice(predicates, i.NameIn, user.NameField.In)
	predicates = gqlrelay.AppendSlice(predicates, i.NameNotIn, user.NameField.NotIn)
	predicates = gqlrelay.AppendIf(predicates, i.NameContains, user.NameField.Contains)
	predicates = gqlrelay.AppendIf(predicates, i.Email, user.EmailField.EQ)
	predicates = gqlrelay.AppendIf(predicates, i.EmailNEQ, user.EmailField.NEQ)
	predicates = gqlrelay.AppendSlice(predicates, i.EmailIn, user.EmailField.In)
	predicates = gqlrelay.AppendSlice(predicates, i.EmailNotIn, user.EmailField.NotIn)
	predicates = gqlrelay.AppendIf(predicates, i.EmailContains, user.EmailField.Contains)
	predicates = gqlrelay.AppendIf(predicates, i.Role, user.RoleField.EQ)
	predicates = gqlrelay.AppendIf(predicates, i.RoleNEQ, user.RoleField.NEQ)
	predicates = gqlrelay.AppendSlice(predicates, i.RoleIn, user.RoleField.In)
	predicates = gqlrelay.AppendSlice(predicates, i.RoleNotIn, user.RoleField.NotIn)
	if i.HasPosts != nil {
		p := user.HasPosts()
		if !*i.HasPosts {
			p = user.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasPostsWith) > 0 {
		with := make([]predicate.Post, 0, len(i.HasPostsWith))
		for _, w := range i.HasPostsWith {
			p, err := w.p(depth + 1)
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasPostsWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, user.HasPostsWith(with...))
	}
	switch len(predicates) {
	case 0:
		return nil, ErrEmptyUserWhereInput
	case 1:
		return predicates[0], nil
	default:
		return user.And(predicates...), nil
	}
}
