// Code generated by velox. DO NOT EDIT.

package token

import (
	sql "github.com/syssam/velox/dialect/sql"
	privacy "github.com/syssam/velox/privacy"
	runtime "github.com/syssam/velox/runtime"
	predicate "github.com/syssam/velox/tests/integration/predicate"
)

// TokenFilter provides a generic filtering capability at runtime for Token.
type TokenFilter struct {
	config runtime.Config
	adder  runtime.PredicateAdder
}

// NewTokenFilter builds a TokenFilter that writes predicates through the given PredicateAdder.
// Used by generated query builders to implement privacy.Filterable.
func NewTokenFilter(cfg runtime.Config, adder runtime.PredicateAdder) privacy.Filter {
	return &TokenFilter{
		adder:  adder,
		config: cfg,
	}
}

// WhereP appends storage-level predicates to the filter.
// Using this method, users can use type-assertion to e.g., compose dynamic filters.
//
// Example usage with entity predicates:
//
//	f.WhereP(token.WorkspaceIDField.EQ(workspaceID))
func (f *TokenFilter) WhereP(ps ...func(*sql.Selector)) {
	for _, p := range ps {
		f.adder.AddPredicate(p)
	}
}

// Where appends type-safe predicates to the filter.
//
// Example usage:
//
//	f.Where(token.StatusEQ("active"))
func (f *TokenFilter) Where(ps ...predicate.Token) {
	for _, p := range ps {
		f.adder.AddPredicate(p)
	}
}

// HasColumn reports whether the entity has the given column name.
// This is useful for writing generic privacy rules that apply to multiple entities.
func (f *TokenFilter) HasColumn(column string) bool {
	return ValidColumn(column)
}
