// Code generated by velox. DO NOT EDIT.

package token

import (
	"context"
	"fmt"

	uuid "github.com/google/uuid"
	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	privacy "github.com/syssam/velox/privacy"
	runtime "github.com/syssam/velox/runtime"
	entity "github.com/syssam/velox/tests/integration/entity"
	predicate "github.com/syssam/velox/tests/integration/predicate"
)

// TokenMutation represents an operation that mutates the Token nodes in the graph.
type TokenMutation struct {
	config        runtime.Config
	op            runtime.Op
	id            *uuid.UUID
	_name         *string
	clearedFields map[string]struct{}
	oldValue      func(context.Context) (*entity.Token, error)
	oldLoaded     bool
	oldCache      *entity.Token
	predicates    []predicate.Token
}

var _ velox.Mutation = (*TokenMutation)(nil)

// tokenOption allows management of the mutation configuration using functional options.
type tokenOption func(*TokenMutation)

// NewTokenMutation creates new mutation for the Token entity.
func NewTokenMutation(c runtime.Config, op runtime.Op, opts ...tokenOption) *TokenMutation {
	m := &TokenMutation{
		config: c,
		op:     runtime.Op(op),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// Op returns the operation name.
func (m *TokenMutation) Op() runtime.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *TokenMutation) SetOp(op runtime.Op) {
	m.op = op
}

// Type returns the schema type name of this mutation ("Token").
func (m *TokenMutation) Type() string {
	return "Token"
}

// ID returns the ID value in the mutation, if it was provided by the caller.
// The second bool return indicates whether the ID field was set.
func (m *TokenMutation) ID() (id any, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetID sets the entity ID value on the mutation.
func (m *TokenMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// loadOld lazily loads the pre-mutation entity state for OldXxx methods.
func (m *TokenMutation) loadOld(ctx context.Context) (*entity.Token, error) {
	if m.op != runtime.OpUpdateOne {
		return nil, fmt.Errorf("OldField is only allowed on UpdateOne operations")
	}
	if m.oldValue == nil {
		return nil, fmt.Errorf("OldField is not supported: no old value loader configured")
	}
	if m.oldLoaded {
		return m.oldCache, nil
	}
	old, err := m.oldValue(ctx)
	if err != nil {
		return nil, fmt.Errorf("querying old values: %w", err)
	}
	m.oldCache = old
	m.oldLoaded = true
	return old, nil
}

// Where appends a list predicates to the TokenMutation builder.
func (m *TokenMutation) Where(ps ...predicate.Token) {
	m.predicates = append(m.predicates, ps...)
}

// PredicatesFuncs returns the predicates as untyped selector functions.
func (m *TokenMutation) PredicatesFuncs() []func(*sql.Selector) {
	ps := make([]func(*sql.Selector), len(m.predicates))
	for i, p := range m.predicates {
		ps[i] = p
	}
	return ps
}

// AddPredicate appends a raw SQL-level predicate to the mutation.
// Satisfies runtime.PredicateAdder so privacy filters can write
// predicates through this method rather than touching internal state.
func (m *TokenMutation) AddPredicate(p func(*sql.Selector)) {
	m.predicates = append(m.predicates, predicate.Token(p))
}

// Filter returns a TokenFilter that writes predicates through this mutation.
// Implements privacy.Filterable so FilterFunc-based mutation rules
// can inject WHERE clauses without knowing the concrete mutation type.
func (m *TokenMutation) Filter() privacy.Filter {
	return NewTokenFilter(m.config, m)
}

// SetName sets the "name" field.
func (m *TokenMutation) SetName(v string) {
	m._name = &v
}

// Name returns the value of the "name" field in the mutation.
func (m *TokenMutation) Name() (r string, exists bool) {
	if m._name == nil {
		return
	}
	return *m._name, true
}

// ResetName resets all changes to the "name" field.
func (m *TokenMutation) ResetName() {
	m._name = nil
	delete(m.clearedFields, "name")
}

// Fields returns all fields that were changed during this mutation.
func (m *TokenMutation) Fields() []string {
	var fields []string
	if m._name != nil {
		fields = append(fields, "name")
	}
	return fields
}

// Field returns the value of a field with the given name.
func (m *TokenMutation) Field(name string) (runtime.Value, bool) {
	switch name {
	case "name":
		if m._name != nil {
			return *m._name, true
		}
	}
	return nil, false
}

// SetField sets the value of a field with the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *TokenMutation) SetField(name string, value runtime.Value) error {
	switch name {
	case "name":
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field name", value)
		}
		m.SetName(v)
		return nil
	default:
		return fmt.Errorf("unknown Token field %s", name)
	}
}

// AddedFields returns all numeric fields that were incremented or decremented during this mutation.
func (m *TokenMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented or decremented for a field.
func (m *TokenMutation) AddedField(name string) (runtime.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an error if the field is not defined in the schema, or if the value type does not match.
func (m *TokenMutation) AddField(name string, value runtime.Value) error {
	switch name {
	default:
		return fmt.Errorf("unknown Token addable field %s", name)
	}
}

// ClearedFields returns all fields that were cleared during this mutation.
func (m *TokenMutation) ClearedFields() []string {
	var fields []string
	for f := range m.clearedFields {
		fields = append(fields, f)
	}
	return fields
}

// FieldCleared reports if a field with the given name was cleared in this mutation.
func (m *TokenMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an error if the field is not defined in the schema or is not nullable.
func (m *TokenMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Token nullable field %s", name)
}

// ResetField resets all changes for the field with the given name. It returns an error if the field is not defined in the schema.
func (m *TokenMutation) ResetField(name string) error {
	switch name {
	case "name":
		m._name = nil
		delete(m.clearedFields, "name")
	default:
		return fmt.Errorf("unknown Token field %s", name)
	}
	return nil
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TokenMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs that were added for the given edge name.
func (m *TokenMutation) AddedIDs(name string) []velox.Value {
	switch name {
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TokenMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs that were removed for the given edge name.
func (m *TokenMutation) RemovedIDs(name string) []velox.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TokenMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared reports if the given edge was cleared in this mutation.
func (m *TokenMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value of the edge with the given name.
func (m *TokenMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Token unique edge %s", name)
}

// ResetEdge resets all changes for the edge with the given name.
func (m *TokenMutation) ResetEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Token edge %s", name)
}

// OldField returns the old value of a field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database fails.
func (m *TokenMutation) OldField(ctx context.Context, name string) (velox.Value, error) {
	switch name {
	case "name":
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Token field %s", name)
}

// OldName returns the old "name" field value, if exists.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TokenMutation) OldName(ctx context.Context) (v string, err error) {
	old, loadErr := m.loadOld(ctx)
	if loadErr != nil {
		err = loadErr
		return
	}
	v = old.Name
	return
}
