// Code generated by velox. DO NOT EDIT.

package token

import (
	"context"
	"errors"
	"fmt"

	uuid "github.com/google/uuid"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
	entity "github.com/syssam/velox/tests/integration/entity"
	testschema "github.com/syssam/velox/testschema"
)

// The init function reads schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to the package variables.
func init() {
	tokenFields := testschema.Token{}.Fields()
	_ = tokenFields
	// tokenDescName is the schema descriptor for name field.
	tokenDescName := tokenFields[1].Descriptor()
	// token.NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator = func() func(string) error {
		validators := tokenDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tokenDescID is the schema descriptor for id field.
	tokenDescID := tokenFields[0].Descriptor()
	// token.DefaultID holds the default value on creation for the id field.
	DefaultID = tokenDescID.Default.(func() uuid.UUID)
	runtime.RegisterEntity(runtime.EntityRegistration{
		Client: func(cfg runtime.Config) any {
			return NewTokenClient(cfg)
		},
		Mutator: func(ctx context.Context, cfg runtime.Config, m any) (any, error) {
			return NewTokenClient(cfg).mutate(ctx, m.(*TokenMutation))
		},
		Name:  "Token",
		Table: Table,
		TypeInfo: &runtime.RegisteredTypeInfo{
			Assign: func(_e any, columns []string, values []any) error {
				return _e.(*entity.Token).AssignValues(columns, values)
			},
			Columns: Columns,
			GetID: func(_e any) any {
				return _e.(*entity.Token).ID
			},
			IDColumn:    FieldID,
			IDFieldType: field.TypeUUID,
			New: func() any {
				return &entity.Token{}
			},
			ScanValues: func(columns []string) ([]any, error) {
				return (&entity.Token{}).ScanValues(columns)
			},
			Table: Table,
		},
		ValidColumn: ValidColumn,
	})
	runtime.RegisterNodeResolver(Table, runtime.NodeResolver{
		Resolve: func(ctx context.Context, id any) (any, error) {
			cfg := runtime.ConfigFromContext(ctx)
			if cfg.Driver == nil {
				return nil, errors.New("velox: NodeResolver requires Config in context — call client.Noder so cfg is propagated")
			}
			typedID, ok := id.(uuid.UUID)
			if !ok {
				return nil, fmt.Errorf("velox: NodeResolver: unexpected id type %T", id)
			}
			return NewTokenClient(cfg).Get(ctx, typedID)
		},
		Type: "Token",
	})
}
