// Code generated by velox. DO NOT EDIT.

package token

import (
	uuid "github.com/google/uuid"
	sql "github.com/syssam/velox/dialect/sql"
	runtime "github.com/syssam/velox/runtime"
	predicate "github.com/syssam/velox/tests/integration/predicate"
)

const (
	// Label holds the string label denoting the Token type in the database.
	Label = "token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the Token in the database.
	Table = "tokens"
)

// Columns holds all SQL columns for Token fields.
var Columns = []string{FieldID, FieldName}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tokens"
// table and are not defined as standalone fields in the schema.
var ForeignKeys []string

// columnSet holds the set of valid column names for O(1) lookups.
var columnSet = func() map[string]struct{} {
	s := make(map[string]struct{}, 2)
	for _, c := range Columns {
		s[c] = struct{}{}
	}
	return s
}()

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	_, ok := columnSet[column]
	return ok
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Token queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// =============================================================================
// LoadOption helpers (functional options for edge loading)
// =============================================================================

// Where returns a LoadOption that adds predicates to the edge query.
func Where(ps ...predicate.Token) runtime.LoadOption {
	return func(c *runtime.LoadConfig) {
		for _, p := range ps {
			c.Predicates = append(c.Predicates, (func(*sql.Selector))(p))
		}
	}
}

// Select returns a LoadOption that selects specific fields.
func Select(fields ...string) runtime.LoadOption {
	return runtime.Select(fields...)
}

// Limit returns a LoadOption that limits the number of results.
func Limit(n int) runtime.LoadOption {
	return runtime.Limit(n)
}

// OrderBy returns a LoadOption that orders the results.
func OrderBy(o ...func(*sql.Selector)) runtime.LoadOption {
	return runtime.OrderBy(o...)
}
