// Code generated by velox. DO NOT EDIT.

package token

import (
	"context"
	"errors"
	"slices"

	velox "github.com/syssam/velox"
	sql "github.com/syssam/velox/dialect/sql"
	sqlgraph "github.com/syssam/velox/dialect/sql/sqlgraph"
	runtime "github.com/syssam/velox/runtime"
	field "github.com/syssam/velox/schema/field"
	entity "github.com/syssam/velox/tests/integration/entity"
	internal "github.com/syssam/velox/tests/integration/internal"
	predicate "github.com/syssam/velox/tests/integration/predicate"
)

// TokenUpdate is the update builder for Token entities.
type TokenUpdate struct {
	config       runtime.Config
	schemaConfig internal.SchemaConfig
	mutation     *TokenMutation
	hooks        []runtime.Hook
	modifiers    []func(*sql.UpdateBuilder)
}

// NewTokenUpdate creates a new TokenUpdate builder.
func NewTokenUpdate(c runtime.Config, mutation *TokenMutation, hooks []runtime.Hook) *TokenUpdate {
	return &TokenUpdate{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the TokenUpdate builder.
func (_u *TokenUpdate) Where(ps ...predicate.Token) *TokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TokenUpdate) SetName(v string) *TokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TokenUpdate) SetNillableName(v *string) *TokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the TokenMutation.
func (_u *TokenUpdate) Mutation() *TokenMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TokenUpdate) Modify(modifiers ...func(*sql.UpdateBuilder)) *TokenUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// sqlSave executes the SQL update for Token after hooks have run.
func (_u *TokenUpdate) sqlSave(ctx context.Context) (int, error) {
	spec := sqlgraph.NewUpdateSpec(Table, Columns, &sqlgraph.FieldSpec{
		Column: FieldID,
		Type:   tokenIDFieldType,
	})
	if _u.mutation._name != nil {
		spec.SetField("name", field.TypeString, *_u.mutation._name)
	}
	ps := _u.mutation.PredicatesFuncs()
	if len(ps) > 0 {
		spec.Predicate = func(s *sql.Selector) {
			for i := range ps {
				ps[i](s)
			}
		}
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	spec.Node.Schema = _u.schemaConfig.Token
	affected, err := sqlgraph.UpdateNodes(ctx, _u.config.Driver, spec)
	if err != nil {
		return 0, runtime.MayWrapConstraintError(err)
	}
	return affected, nil
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TokenUpdate) Save(ctx context.Context) (int, error) {
	hooks := _u.hooks
	return velox.WithHooks[int, TokenMutation, *TokenMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// TokenUpdateOne is the update builder for a single Token entity.
type TokenUpdateOne struct {
	config       runtime.Config
	schemaConfig internal.SchemaConfig
	mutation     *TokenMutation
	hooks        []runtime.Hook
	modifiers    []func(*sql.UpdateBuilder)
	selectFields []string
}

// NewTokenUpdateOne creates a new TokenUpdateOne builder.
func NewTokenUpdateOne(c runtime.Config, mutation *TokenMutation, hooks []runtime.Hook) *TokenUpdateOne {
	return &TokenUpdateOne{
		config:   c,
		hooks:    hooks,
		mutation: mutation,
	}
}

// Where appends a list predicates to the TokenUpdateOne builder.
func (_u *TokenUpdateOne) Where(ps ...predicate.Token) *TokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields/columns for the given update query.
func (_u *TokenUpdateOne) Select(field string, fields ...string) *TokenUpdateOne {
	_u.selectFields = append([]string{field}, fields...)
	return _u
}

// SetName sets the "name" field.
func (_u *TokenUpdateOne) SetName(v string) *TokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TokenUpdateOne) SetNillableName(v *string) *TokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the TokenMutation.
func (_u *TokenUpdateOne) Mutation() *TokenMutation {
	return _u.mutation
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TokenUpdateOne) Modify(modifiers ...func(*sql.UpdateBuilder)) *TokenUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

// sqlSave executes the SQL update for a single Token after hooks have run.
func (_u *TokenUpdateOne) sqlSave(ctx context.Context) (*entity.Token, error) {
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, errors.New("velox: missing ID for UpdateOne")
	}
	spec := sqlgraph.NewUpdateSpec(Table, Columns, &sqlgraph.FieldSpec{
		Column: FieldID,
		Type:   tokenIDFieldType,
	})
	if len(_u.selectFields) == 0 || slices.Contains(_u.selectFields, "name") {
		if _u.mutation._name != nil {
			spec.SetField("name", field.TypeString, *_u.mutation._name)
		}
	}
	spec.Predicate = func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	}
	if len(_u.modifiers) > 0 {
		spec.AddModifiers(_u.modifiers...)
	}
	spec.Node.Schema = _u.schemaConfig.Token
	_, err := sqlgraph.UpdateNodes(ctx, _u.config.Driver, spec)
	if err != nil {
		return nil, runtime.MayWrapConstraintError(err)
	}
	columns := Columns
	if len(_u.selectFields) > 0 {
		columns = append([]string{FieldID}, _u.selectFields...)
	}
	build := func(_ context.Context) (*sql.Selector, error) {
		s := sql.Select(columns...).From(sql.Table(Table))
		s.SetDialect(_u.config.Driver.Dialect())
		s.Where(sql.EQ(s.C(FieldID), id))
		s.Limit(1)
		return s, nil
	}
	_node, err2 := runtime.ScanFirst[entity.Token, *entity.Token](ctx, _u.config.Driver, build, "Token")
	if err2 != nil {
		return nil, err2
	}
	_node.SetConfig(_u.config)
	return _node, nil
}

// Save executes the query and returns the updated Token entity.
func (_u *TokenUpdateOne) Save(ctx context.Context) (*entity.Token, error) {
	_u.mutation.oldValue = func(ctx context.Context) (*entity.Token, error) {
		id, ok := _u.mutation.ID()
		if !ok {
			return nil, errors.New("velox: missing ID for OldField")
		}
		build := func(_ context.Context) (*sql.Selector, error) {
			s := sql.Select(Columns...).From(sql.Table(Table))
			s.SetDialect(_u.config.Driver.Dialect())
			s.Where(sql.EQ(s.C(FieldID), id))
			s.Limit(1)
			return s, nil
		}
		_old, err := runtime.ScanFirst[entity.Token, *entity.Token](ctx, _u.config.Driver, build, "Token")
		if err != nil {
			return nil, err
		}
		_old.SetConfig(_u.config)
		return _old, nil
	}
	hooks := _u.hooks
	return velox.WithHooks[*entity.Token, TokenMutation, *TokenMutation](ctx, _u.sqlSave, _u.mutation, hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokenUpdateOne) SaveX(ctx context.Context) *entity.Token {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}
