// Code generated by velox. DO NOT EDIT.

package token

import (
	uuid "github.com/google/uuid"
	sql "github.com/syssam/velox/dialect/sql"
	predicate "github.com/syssam/velox/tests/integration/predicate"
)

// IDField is the predicate for the id field.
var IDField = sql.UUIDField[predicate.Token, uuid.UUID](FieldID)

// NameField is the predicate for the "name" field.
var NameField = sql.StringField[predicate.Token](FieldName)

// And groups predicates with the AND operator between them.
var And = sql.PredicateAnd[predicate.Token]

// Or groups predicates with the OR operator between them.
var Or = sql.PredicateOr[predicate.Token]

// Not applies the not operator on the given predicate.
var Not = sql.PredicateNot[predicate.Token]
