package integration_test

import (
	"context"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/syssam/velox/dialect/sql"
	"github.com/syssam/velox/tests/integration/predicate"
	"github.com/syssam/velox/tests/integration/user"
)

// TestQuery_FirstOnEmpty verifies First() returns NotFoundError on empty.
func TestQuery_FirstOnEmpty(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	_, err := client.User.Query().First(ctx)
	assert.Error(t, err)
}

// TestQuery_OnlyOnEmpty verifies Only() returns NotFoundError on empty.
func TestQuery_OnlyOnEmpty(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	_, err := client.User.Query().Only(ctx)
	assert.Error(t, err)
}

// TestQuery_OnlyMultiple verifies Only() returns NotSingularError on >1 match.
func TestQuery_OnlyMultiple(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	createUser(t, client, "Alice", "alice@example.com")
	createUser(t, client, "Bob", "bob@example.com")

	_, err := client.User.Query().Only(ctx)
	assert.Error(t, err)
}

// TestQuery_Exist verifies Exist() returns true/false correctly.
func TestQuery_Exist(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	exists, err := client.User.Query().Exist(ctx)
	require.NoError(t, err)
	assert.False(t, exists)

	createUser(t, client, "Alice", "alice@example.com")

	exists, err = client.User.Query().Exist(ctx)
	require.NoError(t, err)
	assert.True(t, exists)
}

// TestQuery_LimitOrderDesc verifies Limit + Order desc.
func TestQuery_LimitOrderDesc(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	createUser(t, client, "Alice", "a@test.com")
	createUser(t, client, "Bob", "b@test.com")
	createUser(t, client, "Charlie", "c@test.com")

	users, err := client.User.Query().
		Order(user.ByName(sql.OrderDesc())).
		Limit(2).
		All(ctx)
	require.NoError(t, err)
	require.Len(t, users, 2)
	assert.Equal(t, "Charlie", users[0].Name)
	assert.Equal(t, "Bob", users[1].Name)
}

// TestQuery_Offset verifies Offset pagination.
func TestQuery_Offset(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	createUser(t, client, "Alice", "a@test.com")
	createUser(t, client, "Bob", "b@test.com")
	createUser(t, client, "Charlie", "c@test.com")

	users, err := client.User.Query().
		Order(user.ByName(sql.OrderAsc())).
		Offset(1).
		All(ctx)
	require.NoError(t, err)
	require.Len(t, users, 2)
	assert.Equal(t, "Bob", users[0].Name)
	assert.Equal(t, "Charlie", users[1].Name)
}

// TestQuery_IDs verifies IDs() returns all matching entity IDs.
func TestQuery_IDs(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	u1 := createUser(t, client, "Alice", "a@test.com")
	u2 := createUser(t, client, "Bob", "b@test.com")

	ids, err := client.User.Query().IDs(ctx)
	require.NoError(t, err)
	assert.ElementsMatch(t, []int{u1.ID, u2.ID}, ids)
}

// TestQuery_TokenIDs verifies IDs(), FirstID(), and OnlyID() work on a
// UUID-keyed entity. These methods use runtime.ExtractID which previously
// panicked on non-integer ID types (Bug B1).
func TestQuery_TokenIDs(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	// Create two tokens (UUID PKs are generated by Default(uuid.New)).
	tok1, err := client.Token.Create().SetName("tok-alpha").Save(ctx)
	require.NoError(t, err)
	tok2, err := client.Token.Create().SetName("tok-beta").Save(ctx)
	require.NoError(t, err)

	// IDs — should return both UUIDs.
	ids, err := client.Token.Query().IDs(ctx)
	require.NoError(t, err)
	require.Len(t, ids, 2)
	assert.ElementsMatch(t, []uuid.UUID{tok1.ID, tok2.ID}, ids)

	// FirstID — should return one of the two (order not guaranteed without Order).
	firstID, err := client.Token.Query().FirstID(ctx)
	require.NoError(t, err)
	assert.Contains(t, []uuid.UUID{tok1.ID, tok2.ID}, firstID)

	// OnlyID — needs exactly one match, so filter.
	onlyID, err := client.Token.Query().Where(
		predicate.Token(sql.FieldEQ("name", "tok-alpha")),
	).OnlyID(ctx)
	require.NoError(t, err)
	assert.Equal(t, tok1.ID, onlyID)
}
