package integration_test

import (
	"context"
	"strconv"
	"sync/atomic"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	integration "github.com/syssam/velox/tests/integration"
	"github.com/syssam/velox/tests/integration/tag"
	"github.com/syssam/velox/tests/integration/user"
)

// TestInterceptor_RootClientSeesAllQueries verifies an interceptor registered
// via client.Intercept fires for queries across all entity types.
func TestInterceptor_RootClientSeesAllQueries(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	alice := createUser(t, client, "Alice", "alice@test.com")
	createPost(t, client, alice, "Post1", "Content1")
	createTag(t, client, "go")

	var calls atomic.Int32
	client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
		return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
			calls.Add(1)
			return next.Query(ctx, q)
		})
	}))

	_, err := client.User.Query().All(ctx)
	require.NoError(t, err)
	_, err = client.Post.Query().All(ctx)
	require.NoError(t, err)
	_, err = client.Tag.Query().All(ctx)
	require.NoError(t, err)

	assert.GreaterOrEqual(t, calls.Load(), int32(3), "interceptor must fire once per entity-level query")
}

// TestInterceptor_ChainOrder verifies multiple interceptors execute in
// registration order (outer -> inner -> handler -> inner -> outer).
func TestInterceptor_ChainOrder(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()
	createUser(t, client, "Alice", "alice@test.com")

	var order []string
	client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
		return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
			order = append(order, "outer-before")
			v, err := next.Query(ctx, q)
			order = append(order, "outer-after")
			return v, err
		})
	}))
	client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
		return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
			order = append(order, "inner-before")
			v, err := next.Query(ctx, q)
			order = append(order, "inner-after")
			return v, err
		})
	}))

	_, err := client.User.Query().All(ctx)
	require.NoError(t, err)

	assert.Equal(t, []string{
		"outer-before",
		"inner-before",
		"inner-after",
		"outer-after",
	}, order)
}

// TestInterceptor_ScalarPathsFire verifies that interceptors registered
// via client.Intercept() fire on scalar and aggregate query terminal
// methods: .IDs(), .Select().Strings(), .Aggregate().Int(), and
// .GroupBy().Scan(). Each of these used to bypass the interceptor
// chain by calling runtime helpers directly (QuerySelect / QueryGroupBy
// / sqlgraph.QueryNodes).
func TestInterceptor_ScalarPathsFire(t *testing.T) {
	cases := []struct {
		name string
		run  func(t *testing.T, client *integration.Client, ctx context.Context)
	}{
		{"IDs", func(t *testing.T, client *integration.Client, ctx context.Context) {
			_, err := client.User.Query().IDs(ctx)
			require.NoError(t, err)
		}},
		{"Select.Strings", func(t *testing.T, client *integration.Client, ctx context.Context) {
			_, err := client.User.Query().Select(user.FieldName).Strings(ctx)
			require.NoError(t, err)
		}},
		{"Aggregate.Int", func(t *testing.T, client *integration.Client, ctx context.Context) {
			_, err := client.User.Query().Aggregate(integration.Count()).Int(ctx)
			require.NoError(t, err)
		}},
		{"GroupBy.Scan", func(t *testing.T, client *integration.Client, ctx context.Context) {
			var rows []struct {
				Role string `json:"role"`
			}
			err := client.User.Query().GroupBy(user.FieldRole).Scan(ctx, &rows)
			require.NoError(t, err)
		}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			client := openTestClient(t)
			ctx := context.Background()
			createUser(t, client, "Alice", "alice@test.com")
			createUser(t, client, "Bob", "bob@test.com")

			var calls atomic.Int32
			client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
				return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
					calls.Add(1)
					return next.Query(ctx, q)
				})
			}))

			tc.run(t, client, ctx)

			assert.GreaterOrEqual(t, calls.Load(), int32(1),
				"interceptor must fire on %s, got %d calls", tc.name, calls.Load())
		})
	}
}

// TestInterceptor_EagerLoadFires verifies that interceptors registered
// via client.Intercept() fire on the child SELECT generated by an
// eager-load .WithPosts() call. The eager-load creates a fresh child
// PostQuery via NewPostQuery(q.config); the generator must thread
// the parent's interceptors into that child query, otherwise the
// child's SELECT is invisible to the interceptor chain.
func TestInterceptor_EagerLoadFires(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	alice := createUser(t, client, "Alice", "alice@test.com")
	createPost(t, client, alice, "P1", "C1")
	createPost(t, client, alice, "P2", "C2")

	var calls atomic.Int32
	client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
		return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
			calls.Add(1)
			return next.Query(ctx, q)
		})
	}))

	// Eager-load: one SELECT on users + one SELECT on posts = 2 queries.
	users, err := client.User.Query().WithPosts().All(ctx)
	require.NoError(t, err)
	require.Len(t, users, 1)
	assert.Len(t, users[0].Edges.Posts, 2)

	assert.GreaterOrEqual(t, calls.Load(), int32(2),
		"interceptor must fire on both the parent User query and the eager-loaded Post sub-query, got %d", calls.Load())
}

// TestInterceptor_EdgeQueryFires verifies that interceptors registered on
// the root client fire for edge traversal queries (e.g. client.User.
// QueryPosts(v)), not just direct entity queries (client.Post.Query()).
//
// The edge-query generator previously emitted SetPath on the new query
// but NOT SetInters — a silent gap that made client.Intercept() do
// nothing on edge traversals. This test pins the contract.
func TestInterceptor_EdgeQueryFires(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	alice := createUser(t, client, "Alice", "alice@test.com")
	createPost(t, client, alice, "P1", "C1")
	createPost(t, client, alice, "P2", "C2")

	var calls atomic.Int32
	client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
		return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
			calls.Add(1)
			return next.Query(ctx, q)
		})
	}))

	// Edge traversal: alice → posts. Goes through UserClient.QueryPosts,
	// which constructs a new entity query for Post via runtime.NewEntityQuery
	// + SetPath. The generator MUST also call SetInters here; otherwise the
	// root-client interceptor never sees this query.
	posts, err := client.User.QueryPosts(alice).All(ctx)
	require.NoError(t, err)
	require.Len(t, posts, 2)

	assert.GreaterOrEqual(t, calls.Load(), int32(1),
		"interceptor must fire on edge-query traversal, not just direct Query()")
}

// TestInterceptor_OldFieldBypass pins an intentional limitation: a
// query interceptor registered via client.Intercept() does NOT fire
// on the internal SELECT that a mutation hook runs to resolve
// OldField() calls. That SELECT goes through runtime.ScanFirst →
// drv.Query directly, bypassing the interceptor chain.
//
// This is deliberate, matches Ent, and is the right design:
//   - Hooks run INSIDE the mutation path; the interceptor chain is
//     for the USER's query surface.
//   - Audit-log interceptors should observe user queries, not every
//     internal implementation-detail SELECT velox runs.
//   - Caching/RLS interceptors on loadOld would be semantically
//     confusing (loadOld is a point-in-time pre-image, not a
//     user-visible query).
//
// If you're reading this test because you expected interceptors to
// fire on OldField loads: don't. Put your logic in a mutation hook
// instead — that's the right abstraction for observing mutations
// and their pre/post state.
func TestInterceptor_OldFieldBypass(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	alice := createUser(t, client, "Alice", "alice@test.com")

	var queryCalls atomic.Int32
	client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
		return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
			queryCalls.Add(1)
			return next.Query(ctx, q)
		})
	}))

	// Register a hook that reads OldField on update — this forces
	// the mutation path to run an internal SELECT.
	var hookSawOldName string
	client.User.Use(func(next integration.Mutator) integration.Mutator {
		return integration.MutateFunc(func(ctx context.Context, m integration.Mutation) (integration.Value, error) {
			if m.Op().Is(integration.OpUpdateOne) {
				if um, ok := m.(interface {
					OldName(context.Context) (string, error)
				}); ok {
					oldName, err := um.OldName(ctx)
					if err != nil {
						return nil, err
					}
					hookSawOldName = oldName
				}
			}
			return next.Mutate(ctx, m)
		})
	})

	_, err := client.User.UpdateOneID(alice.ID).SetName("Alice Updated").Save(ctx)
	require.NoError(t, err)

	assert.Equal(t, "Alice", hookSawOldName, "hook should have read the old name via loadOld")

	// The critical assertion: the interceptor did NOT fire for the
	// loadOld SELECT. It may have fired for other queries but not
	// for that one. For this test we assert it fires zero times
	// because the only thing we did was one UpdateOne, which does
	// not emit any user-facing query.
	assert.Equal(t, int32(0), queryCalls.Load(),
		"interceptor must NOT fire for loadOld internal queries; got %d calls", queryCalls.Load())
}

// TestInterceptor_RecursiveMutationFromInterceptor verifies that a
// query interceptor can safely call a mutation (Create/Update/Delete)
// on the same client from within its body. This is a natural pattern
// for audit logging — "every read of User X creates an audit row".
// Without reentrance support, this would deadlock or corrupt state.
func TestInterceptor_RecursiveMutationFromInterceptor(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()

	createUser(t, client, "Alice", "alice@test.com")

	// The interceptor creates an audit Tag for every query observed
	// while `enabled` is true. We flip `enabled` off before the
	// verification query so the count isn't itself intercepted and
	// doesn't generate another audit row — the interceptor would
	// fire on ANY query, not just the one we're trying to audit.
	var auditWrites atomic.Int32
	var enabled atomic.Bool
	enabled.Store(true)
	var depth atomic.Int32
	client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
		return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
			if !enabled.Load() || depth.Add(1) > 1 {
				if depth.Load() > 0 {
					defer depth.Add(-1)
				}
				return next.Query(ctx, q)
			}
			defer depth.Add(-1)

			// Recursive mutation call from inside the interceptor.
			// This is the load-bearing assertion: Tag.Create().Save(ctx)
			// from within a Querier.Query must not deadlock, must not
			// corrupt the outer query's state, and must actually
			// persist the row.
			_, err := client.Tag.Create().
				SetName("audit_" + strconv.FormatInt(int64(auditWrites.Load()), 10)).
				Save(ctx)
			if err != nil {
				return nil, err
			}
			auditWrites.Add(1)

			return next.Query(ctx, q)
		})
	}))

	// One User.Query → one audit Tag row written from inside the
	// interceptor. The mutation flow (Tag.Create) inside the
	// interceptor must not deadlock or corrupt the outer query.
	users, err := client.User.Query().All(ctx)
	require.NoError(t, err)
	assert.Len(t, users, 1)
	assert.Equal(t, int32(1), auditWrites.Load(), "interceptor body should run exactly once")

	// Turn off the audit side-effect and verify the row landed.
	enabled.Store(false)
	count, err := client.Tag.Query().Where(tag.NameField.HasPrefix("audit_")).Count(ctx)
	require.NoError(t, err)
	assert.Equal(t, 1, count, "recursive Save from interceptor must persist row")
}

// TestInterceptor_TxInheritsClientInterceptors verifies a transaction started
// from a client with registered interceptors inherits them.
func TestInterceptor_TxInheritsClientInterceptors(t *testing.T) {
	client := openTestClient(t)
	ctx := context.Background()
	createUser(t, client, "Alice", "alice@test.com")

	var called atomic.Bool
	client.Intercept(integration.InterceptFunc(func(next integration.Querier) integration.Querier {
		return integration.QuerierFunc(func(ctx context.Context, q integration.Query) (integration.Value, error) {
			called.Store(true)
			return next.Query(ctx, q)
		})
	}))

	tx, err := client.Tx(ctx)
	require.NoError(t, err)
	defer tx.Rollback()

	_, err = tx.User.Query().All(ctx)
	require.NoError(t, err)
	assert.True(t, called.Load(), "tx queries must inherit client interceptors")
}
