// Code generated by velox. DO NOT EDIT.

package integration

import (
	"context"
	"errors"

	"github.com/syssam/velox/contrib/graphql/gqlrelay"
	"github.com/syssam/velox/runtime"
)

// Noder is the interface for Relay Node resolution.
type Noder interface {
	IsNode()
}

var ErrNodeNotFound = gqlrelay.ErrNodeNotFound

// Noder returns the Node with the given ID. It returns ErrNodeNotFound when no
// type has the ID, and an error wrapping runtime.ErrAmbiguousNodeID when more
// than one does — Relay IDs must be globally unique (FeatureGlobalID).
func (c *Client) Noder(ctx context.Context, id int) (Noder, error) {
	ctx = runtime.WithConfigContext(ctx, c.RuntimeConfig())
	return resolveNoder(ctx, id)
}

// Noders returns the Nodes with the given IDs. An ID no type has yields a nil
// entry (per the Relay spec); any other error, including an ambiguous ID, is returned.
func (c *Client) Noders(ctx context.Context, ids []int) ([]Noder, error) {
	ctx = runtime.WithConfigContext(ctx, c.RuntimeConfig())
	nodes := make([]Noder, len(ids))
	for i, id := range ids {
		n, err := resolveNoder(ctx, id)
		if errors.Is(err, ErrNodeNotFound) {
			continue
		}
		if err != nil {
			return nil, err
		}
		nodes[i] = n
	}
	return nodes, nil
}
func resolveNoder(ctx context.Context, id int) (Noder, error) {
	v, found, err := runtime.ResolveNode(ctx, id)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, ErrNodeNotFound
	}
	noder, ok := v.(Noder)
	if !ok {
		return nil, ErrNodeNotFound
	}
	return noder, nil
}

type (
	NodeDescriptor  = gqlrelay.NodeDescriptor
	FieldDescriptor = gqlrelay.FieldDescriptor
	EdgeDescriptor  = gqlrelay.EdgeDescriptor
)
