// Code generated by velox. DO NOT EDIT.

package integration

import (
	"context"

	"github.com/syssam/velox/contrib/graphql/gqlrelay"
	"github.com/syssam/velox/runtime"
)

// Noder is the interface for Relay Node resolution.
type Noder interface {
	IsNode()
}

var ErrNodeNotFound = gqlrelay.ErrNodeNotFound

// Noder returns a Node by its ID using the registered node resolvers.
// It tries each registered resolver until one succeeds.
// Not-found errors are skipped; all other errors (e.g., database failures) are returned immediately.
func (c *Client) Noder(ctx context.Context, id int) (Noder, error) {
	ctx = runtime.WithConfigContext(ctx, c.RuntimeConfig())
	for _, resolver := range runtime.NodeResolvers() {
		result, err := resolver.Resolve(ctx, id)
		if err != nil {
			if runtime.IsNotFound(err) {
				continue
			}
			return nil, err
		}
		if noder, ok := result.(Noder); ok {
			return noder, nil
		}
	}
	return nil, ErrNodeNotFound
}

// Noders returns Nodes by their IDs, resolving each via the registered resolvers.
// Unresolvable IDs produce nil entries (per Relay spec). Real errors are returned immediately.
func (c *Client) Noders(ctx context.Context, ids []int) ([]Noder, error) {
	ctx = runtime.WithConfigContext(ctx, c.RuntimeConfig())
	resolvers := runtime.NodeResolvers()
	nodes := make([]Noder, len(ids))
	for i, id := range ids {
		for _, resolver := range resolvers {
			result, err := resolver.Resolve(ctx, id)
			if err != nil {
				if runtime.IsNotFound(err) {
					continue
				}
				return nil, err
			}
			if noder, ok := result.(Noder); ok {
				nodes[i] = noder
				break
			}
		}
		// nodes[i] remains nil if no resolver found (per Relay spec)
	}
	return nodes, nil
}

type (
	NodeDescriptor  = gqlrelay.NodeDescriptor
	FieldDescriptor = gqlrelay.FieldDescriptor
	EdgeDescriptor  = gqlrelay.EdgeDescriptor
)
