package graphql

// Edge resolver generator: generates gql_edge_{entity}.go in root package with edge methods
// on root wrapper types so gqlgen can resolve edges without hand-written resolvers.
//
// Three patterns:
//   - Unique edge (e.g., Parent): check OrErr() → wrap + fallback to QueryXxx().Only(ctx) → wrap
//   - Connection edge (non-unique + Relay): delegate to QueryXxx().Paginate()
//   - Plain list edge (non-unique, no Relay): check OrErr() → wrap + fallback to QueryXxx().All(ctx) → wrap

import (
	"github.com/dave/jennifer/jen"

	"github.com/syssam/velox/compiler/gen"
)

// genEntityEdge generates edge resolver methods for an entity in the entity/ package.
// Output: entity/gql_edge_{entity}.go
// Edge methods are on entity types directly — no wrapping needed.
// They call the entity-level QueryXxx() method directly, which lives in the
// per-entity sub-package and returns a typed edge query.
func (g *Generator) genEntityEdge(t *gen.Type) *jen.File {
	if g.config.ORMPackage == "" {
		return nil
	}

	edges := g.filterEdges(t.Edges, SkipType)
	if len(edges) == 0 {
		return nil
	}

	entityPkg := g.config.ORMPackage + "/entity"
	f := jen.NewFilePathName(entityPkg, "entity")
	f.HeaderComment("Code generated by velox. DO NOT EDIT.")

	f.ImportName("context", "context")
	f.ImportName("github.com/99designs/gqlgen/graphql", "graphql")
	f.ImportName(gqlrelayPkg, "gqlrelay")
	f.ImportName(runtimePkgPath, "runtime")

	typeName := g.graphqlTypeName(t)

	for _, e := range edges {
		if e.Unique {
			g.genSimpleEdgeMethod(f, t, e, typeName, entityPkg)
		} else if g.config.RelayConnection && g.hasRelayConnection(e.Type) {
			g.genConnectionEdgeMethod(f, t, e, typeName)
		} else {
			g.genListEdgeMethod(f, t, e, typeName, entityPkg)
		}
	}

	return f
}

// genSimpleEdgeMethod generates a unique edge method (returns single entity or nil).
// Methods are on entity types directly in entity/ package — no wrapping needed.
// Delegates to the entity-level QueryXxx() method for lazy loading.
//
//	func (m *Category) Parent(ctx context.Context) (*Category, error) {
//	    result, err := m.Edges.ParentOrErr()
//	    if runtime.IsNotLoaded(err) {
//	        val, err := m.QueryParent().Only(ctx)
//	        if err != nil { return nil, runtime.MaskNotFound(err) }
//	        return val, nil
//	    }
//	    return result, runtime.MaskNotFound(err)
//	}
func (g *Generator) genSimpleEdgeMethod(f *jen.File, _ *gen.Type, e *gen.Edge, typeName, _ string) {
	edgePascal := pascal(e.Name)
	targetType := g.graphqlTypeName(e.Type)

	// Direct call: m.QueryXxx().Only(ctx). The entity-level QueryXxx()
	// already encodes direction (M2O Step with Inverse=true) so the SQL
	// is correct for both M2O and M2M-unique edges.
	queryMethod := "Query" + edgePascal
	f.Func().Params(
		jen.Id("m").Op("*").Id(typeName),
	).Id(edgePascal).Params(
		jen.Id("ctx").Qual("context", "Context"),
	).Params(
		jen.Op("*").Id(targetType),
		jen.Error(),
	).Block(
		jen.List(jen.Id("result"), jen.Id("err")).Op(":=").Id("m").Dot("Edges").Dot(edgePascal+"OrErr").Call(),
		jen.If(jen.Qual(runtimePkgPath, "IsNotLoaded").Call(jen.Id("err"))).Block(
			jen.List(jen.Id("val"), jen.Id("err2")).Op(":=").Id("m").Dot(queryMethod).Call().Dot("Only").Call(jen.Id("ctx")),
			jen.If(jen.Id("err2").Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Qual(runtimePkgPath, "MaskNotFound").Call(jen.Id("err2"))),
			),
			jen.Return(jen.Id("val"), jen.Nil()),
		),
		jen.Return(
			jen.Id("result"),
			jen.Qual(runtimePkgPath, "MaskNotFound").Call(jen.Id("err")),
		),
	)
}

// genListEdgeMethod generates a non-unique edge method without pagination (returns slice).
// Methods are on entity types directly — no wrapping needed.
//
//	func (m *Todo) Comments(ctx context.Context) ([]*Comment, error) {
//	    result, err := m.Edges.CommentsOrErr()
//	    if runtime.IsNotLoaded(err) {
//	        return m.QueryComments().All(ctx)
//	    }
//	    return result, err
//	}
func (g *Generator) genListEdgeMethod(f *jen.File, _ *gen.Type, e *gen.Edge, typeName, _ string) {
	edgePascal := pascal(e.Name)
	targetType := g.graphqlTypeName(e.Type)

	// Direct call to entity-level m.QueryXxx().All(ctx) — the generated
	// QueryXxx() method in entity/ already holds correct SetPath +
	// sqlgraph.NewStep for O2M/M2O traversal. No runtime registry.
	queryMethod := "Query" + edgePascal
	f.Func().Params(
		jen.Id("m").Op("*").Id(typeName),
	).Id(edgePascal).Params(
		jen.Id("ctx").Qual("context", "Context"),
	).Params(
		jen.Index().Op("*").Id(targetType),
		jen.Error(),
	).Block(
		jen.List(jen.Id("result"), jen.Id("err")).Op(":=").Id("m").Dot("Edges").Dot(edgePascal+"OrErr").Call(),
		jen.If(jen.Qual(runtimePkgPath, "IsNotLoaded").Call(jen.Id("err"))).Block(
			jen.Return(
				jen.Id("m").Dot(queryMethod).Call().Dot("All").Call(jen.Id("ctx")),
			),
		),
		jen.Return(jen.Id("result"), jen.Id("err")),
	)
}

// genConnectionEdgeMethod generates a connection edge method with Relay pagination.
//
//	func (m *Category) Products(ctx, after, first, before, last, orderBy) (*ProductConnection, error) {
//	    return m.QueryProducts().(ProductPaginatable).Paginate(ctx, after, first, before, last, WithProductOrder(orderBy))
//	}
func (g *Generator) genConnectionEdgeMethod(f *jen.File, _ *gen.Type, e *gen.Edge, typeName string) {
	edgePascal := pascal(e.Name)
	targetType := g.graphqlTypeName(e.Type)
	connName := targetType + "Connection"
	orderName := targetType + "Order"
	withOrderFunc := "With" + targetType + "Order"
	queryMethod := "Query" + edgePascal
	paginatable := targetType + "Paginatable"

	f.Func().Params(
		jen.Id("m").Op("*").Id(typeName),
	).Id(edgePascal).Params(
		jen.Id("ctx").Qual("context", "Context"),
		jen.Id("after").Op("*").Qual(gqlrelayPkg, "Cursor"),
		jen.Id("first").Op("*").Int(),
		jen.Id("before").Op("*").Qual(gqlrelayPkg, "Cursor"),
		jen.Id("last").Op("*").Int(),
		jen.Id("orderBy").Op("*").Id(orderName),
	).Params(
		jen.Op("*").Id(connName),
		jen.Error(),
	).Block(
		jen.Return(
			jen.Id("m").Dot(queryMethod).Call().Assert(jen.Id(paginatable)).Dot("Paginate").Call(
				jen.Id("ctx"),
				jen.Id("after"),
				jen.Id("first"),
				jen.Id("before"),
				jen.Id("last"),
				jen.Id(withOrderFunc).Call(jen.Id("orderBy")),
			),
		),
	)
}
