package graphql

import (
	"github.com/dave/jennifer/jen"

	"github.com/syssam/velox/compiler/gen"
)

// gqlgenGraphqlPkg is gqlgen's runtime package, needed by the polymorphic
// fast path to inspect the field selection.
const gqlgenGraphqlPkg = "github.com/99designs/gqlgen/graphql"

// genInterfacesShared emits entity/gql_interfaces.go: one Go interface per
// generated GraphQL interface (see generatedInterfaces) with a marker
// method, and that marker on every implementor. gqlgen binds the GraphQL
// interface to the Go interface through @goModel and resolves the concrete
// type by the marker, exactly as it does for unions (gql_unions.go).
func (g *Generator) genInterfacesShared() (*jen.File, error) {
	ifaces, err := g.generatedInterfaces()
	if err != nil {
		return nil, err
	}
	if len(ifaces) == 0 || g.config.ORMPackage == "" {
		return nil, nil
	}
	f := jen.NewFilePathName(g.config.ORMPackage+"/entity", "entity")
	f.HeaderComment("Code generated by velox. DO NOT EDIT.")
	f.Comment("Go interfaces for the GraphQL interfaces velox generates from")
	f.Comment("graphql.InterfaceField groups, plus the marker methods that let gqlgen")
	f.Comment("resolve a value to its concrete type.")
	for _, gi := range ifaces {
		f.Commentf("%s is the Go interface for the %s GraphQL interface.", gi.Name, gi.Name)
		f.Type().Id(gi.Name).Interface(jen.Id("Is" + gi.Name).Params())
		for _, impl := range gi.ImplementorTypes {
			f.Func().Params(jen.Op("*").Id(impl.Name)).Id("Is" + gi.Name).Params().Block()
		}
	}
	return f, nil
}

// genInterfaceFieldMethods emits the resolver methods for t's interface
// fields into its gql_edge file:
//
//   - rename, to-one:  func (m *Todo) Owner(ctx) (*Category, error)
//   - rename, to-many: func (m *User) Items(ctx) ([]*Todo, error)
//   - polymorphic, all to-one: func (m *Bookmark) Item(ctx) (BookmarkItem, error)
//
// A polymorphic field whose edges all keep their foreign key on m and whose
// keys are nullable pointers takes a fast path: the populated key names the
// concrete type and id, so a selection covered by __typename/id is answered
// without a query. A polymorphic field over to-many edges is exposed as an
// interface connection in the SDL and left to an application resolver.
func (g *Generator) genInterfaceFieldMethods(f *jen.File, t *gen.Type, typeName string) error {
	groups, err := g.interfaceFieldGroups(t)
	if err != nil {
		return err
	}
	for _, ifc := range groups {
		method := pascal(ifc.FieldName)
		switch {
		case ifc.IsRename && ifc.Edges[0].Unique:
			g.genRenameUniqueMethod(f, ifc.Edges[0], typeName, method)
		case ifc.IsRename:
			g.genRenameListMethod(f, ifc.Edges[0], typeName, method)
		case ifc.unique():
			g.genPolymorphicUniqueMethod(f, t, ifc, typeName, method)
		}
	}
	return nil
}

func (g *Generator) genRenameUniqueMethod(f *jen.File, e *gen.Edge, typeName, method string) {
	edgePascal := pascal(e.Name)
	f.Commentf("%s returns the %s edge under its interface-field name.", method, e.Name)
	f.Func().Params(jen.Id("m").Op("*").Id(typeName)).Id(method).Params(
		jen.Id("ctx").Qual("context", "Context"),
	).Params(jen.Op("*").Id(g.graphqlTypeName(e.Type)), jen.Error()).Block(
		jen.Return(jen.Id("m").Dot(edgePascal).Call(jen.Id("ctx"))),
	)
}

func (g *Generator) genRenameListMethod(f *jen.File, e *gen.Edge, typeName, method string) {
	edgePascal := pascal(e.Name)
	f.Commentf("%s returns the %s edge under its interface-field name.", method, e.Name)
	f.Func().Params(jen.Id("m").Op("*").Id(typeName)).Id(method).Params(
		jen.Id("ctx").Qual("context", "Context"),
	).Params(jen.Index().Op("*").Id(g.graphqlTypeName(e.Type)), jen.Error()).Block(
		jen.List(jen.Id("result"), jen.Id("err")).Op(":=").Id("m").Dot("Edges").Dot(edgePascal+"OrErr").Call(),
		jen.If(jen.Qual(runtimePkgPath, "IsNotLoaded").Call(jen.Id("err"))).Block(
			jen.Return(jen.Id("m").Dot("Query"+edgePascal).Call().Dot("All").Call(jen.Id("ctx"))),
		),
		jen.Return(jen.Id("result"), jen.Id("err")),
	)
}

// fkPointerField returns the unexported foreign-key struct field on t that
// stores edge e's key, when it is a nullable pointer; "" otherwise.
//
// A foreign key is registered against the edge that DECLARES it, which for a
// pair created by edge.From(...).Ref(...) is the assoc edge on the other
// type: Member's key for its "workspace" edge is registered against
// Workspace's "members" edge and named workspace_members. Matching on the
// edge's own name alone therefore never finds it — the paired edge must be
// considered too, the same way Edge.DeleteAction consults e.Ref. Edge.Ref is
// set in both directions (graph_resolve.go), so one identity check covers
// both. Auto-created keys are always nillable; a key declared with
// .Field("x_id") on a required edge is not, and then there is no fast path.
func fkPointerField(t *gen.Type, e *gen.Edge) string {
	for _, fk := range t.ForeignKeys {
		if fk.Edge == nil || fk.Field == nil || !fk.Field.Nillable {
			continue
		}
		if fk.Edge != e && fk.Edge.Ref != e {
			continue
		}
		return fk.StructField()
	}
	return ""
}

func (g *Generator) genPolymorphicUniqueMethod(f *jen.File, t *gen.Type, ifc *interfaceFieldGroup, typeName, method string) {
	satisfies := []jen.Code{jen.Lit(ifc.InterfaceName)}
	for _, e := range ifc.Edges {
		satisfies = append(satisfies, jen.Lit(g.graphqlTypeName(e.Type)))
	}
	fastPath := ifc.allOwnFK()
	fkFields := map[string]string{}
	for _, e := range ifc.Edges {
		fkFields[e.Name] = fkPointerField(t, e)
		if fkFields[e.Name] == "" {
			fastPath = false
		}
	}
	if fastPath {
		f.ImportName(gqlgenGraphqlPkg, "graphql")
	}

	// probe emits the always-correct path: reuse the eager-loaded edge if
	// present, otherwise query it, and move on to the next edge when this
	// one holds nothing.
	probe := func(body *jen.Group) {
		for _, e := range ifc.Edges {
			edgePascal := pascal(e.Name)
			body.Block(
				jen.List(jen.Id("result"), jen.Id("err")).Op(":=").Id("m").Dot("Edges").Dot(edgePascal+"OrErr").Call(),
				jen.If(jen.Qual(runtimePkgPath, "IsNotLoaded").Call(jen.Id("err"))).Block(
					jen.List(jen.Id("result"), jen.Id("err")).Op("=").Id("m").Dot("Query"+edgePascal).Call().Dot("Only").Call(jen.Id("ctx")),
				),
				jen.Switch().Block(
					jen.Case(jen.Id("err").Op("==").Nil().Op("&&").Id("result").Op("!=").Nil()).Block(jen.Return(jen.Id("result"), jen.Nil())),
					jen.Case(jen.Id("err").Op("!=").Nil().Op("&&").Op("!").Qual(runtimePkgPath, "IsNotFound").Call(jen.Id("err"))).Block(jen.Return(jen.Nil(), jen.Id("err"))),
				),
			)
		}
		body.Return(jen.Nil(), jen.Nil())
	}

	f.Commentf("%s returns the %s value from the first populated edge (%s),", method, ifc.InterfaceName, edgeNames(ifc.Edges))
	f.Comment("using the eager-loaded edge when present and falling back to a query otherwise.")
	if fastPath {
		f.Comment("When the foreign keys were selected, the populated one names the")
		f.Comment("concrete type and id, so a selection covered by __typename/id needs")
		f.Comment("no query at all; with no key loaded the edges are probed instead.")
	}
	f.Func().Params(jen.Id("m").Op("*").Id(typeName)).Id(method).Params(
		jen.Id("ctx").Qual("context", "Context"),
	).Params(jen.Id(ifc.InterfaceName), jen.Error()).BlockFunc(func(body *jen.Group) {
		if !fastPath {
			probe(body)
			return
		}
		body.Switch().BlockFunc(func(sw *jen.Group) {
			for _, e := range ifc.Edges {
				edgePascal := pascal(e.Name)
				target := g.graphqlTypeName(e.Type)
				sw.Case(jen.Id("m").Dot(fkFields[e.Name]).Op("!=").Nil()).Block(
					jen.List(jen.Id("result"), jen.Id("err")).Op(":=").Id("m").Dot("Edges").Dot(edgePascal+"OrErr").Call(),
					jen.If(jen.Id("err").Op("==").Nil()).Block(jen.Return(jen.Id("result"), jen.Nil())),
					jen.If(jen.Op("!").Qual(runtimePkgPath, "IsNotLoaded").Call(jen.Id("err"))).Block(jen.Return(jen.Nil(), jen.Id("err"))),
					jen.If(
						jen.Id("fc").Op(":=").Qual(gqlgenGraphqlPkg, "GetFieldContext").Call(jen.Id("ctx")),
						jen.Id("fc").Op("==").Nil().Op("||").Op("!").Qual(gqlrelayPkg, "InterfaceFieldCoveredByID").Call(
							append([]jen.Code{jen.Id("fc").Dot("Field"), jen.Qual(gqlgenGraphqlPkg, "GetOperationContext").Call(jen.Id("ctx"))}, satisfies...)...,
						),
					).Block(
						jen.List(jen.Id("val"), jen.Id("err")).Op(":=").Id("m").Dot("Query"+edgePascal).Call().Dot("Only").Call(jen.Id("ctx")),
						jen.If(jen.Id("err").Op("!=").Nil()).Block(jen.Return(jen.Nil(), jen.Qual(runtimePkgPath, "MaskNotFound").Call(jen.Id("err")))),
						jen.Return(jen.Id("val"), jen.Nil()),
					),
					jen.Return(jen.Op("&").Id(target).Values(jen.Dict{jen.Id("ID"): jen.Op("*").Id("m").Dot(fkFields[e.Name])}), jen.Nil()),
				)
			}
			// No key loaded — the query did not select the foreign keys, so
			// nothing can be concluded from them. Probe the edges.
			sw.Default().BlockFunc(probe)
		})
	})
}

func edgeNames(edges []*gen.Edge) string {
	s := ""
	for i, e := range edges {
		if i > 0 {
			s += ", "
		}
		s += e.Name
	}
	return s
}
