package graphql

// Pagination generator: generates per-entity Paginate method on root query wrapper.
// Generates clean, direct pagination like Ent — no callback indirection.
// Also contains shared helpers for Relay cursor-based pagination code generation.

import (
	"fmt"
	"math"
	"strings"

	"github.com/dave/jennifer/jen"

	"github.com/syssam/velox/compiler/gen"
)

const gqlrelayPkg = "github.com/syssam/velox/contrib/graphql/gqlrelay"

// genEntityPagination generates a Paginate method on the query/ package query type.
// Direct style (like Ent): apply order → apply cursors → count → fetch → build connection.
// Pagination types (Connection, Edge, Order) are referenced from entity/ package.
func (g *Generator) genEntityPagination(t *gen.Type) *jen.File {
	if g.config.ORMPackage == "" {
		return nil
	}

	queryPkg := g.config.ORMPackage + "/query"
	entityPkg := g.config.ORMPackage + "/entity"
	subEntityPkg := g.entityPkgPath(t)

	f := jen.NewFilePathName(queryPkg, "query")
	f.HeaderComment("Code generated by velox. DO NOT EDIT.")

	f.ImportName("context", "context")
	f.ImportName("fmt", "fmt")
	f.ImportName(gqlrelayPkg, "gqlrelay")
	f.ImportName("github.com/syssam/velox/dialect/sql", "sql")
	f.ImportName(entityPkg, "entity")
	f.ImportName(subEntityPkg, g.entityPkgName(t))

	typeName := g.graphqlTypeName(t)
	queryName := t.QueryName()

	// Pagination types are now in entity/ package.
	connName := typeName + "Connection"
	optName := typeName + "PaginateOption"
	pagerCfg := typeName + "PagerConfig"

	// idColumn is the Go identifier for the entity's ID field constant in
	// the per-entity predicate package (e.g., `todo.FieldID` or
	// `todo.FieldUserID`). Used by the order-by fallback and cursor
	// predicates below.
	idColumn := "FieldID"
	if t.ID != nil && t.ID.Name != "" && t.ID.Name != "id" {
		idColumn = "Field" + pascal(t.ID.Name)
	}

	// Paginate method on query.UserQuery — direct style like Ent.
	f.Commentf("Paginate returns a paginated %s using Relay cursor pagination.", connName)
	f.Func().Params(
		jen.Id("q").Op("*").Id(queryName),
	).Id("Paginate").Params(
		jen.Id("ctx").Qual("context", "Context"),
		jen.Id("after").Op("*").Qual(gqlrelayPkg, "Cursor"),
		jen.Id("first").Op("*").Int(),
		jen.Id("before").Op("*").Qual(gqlrelayPkg, "Cursor"),
		jen.Id("last").Op("*").Int(),
		jen.Id("opts").Op("...").Qual(entityPkg, optName),
	).Params(
		jen.Op("*").Qual(entityPkg, connName),
		jen.Error(),
	).BlockFunc(func(grp *jen.Group) {
		// Validate
		grp.If(jen.Err().Op(":=").Qual(gqlrelayPkg, "ValidateFirstLast").Call(jen.Id("first"), jen.Id("last")), jen.Err().Op("!=").Nil()).Block(
			jen.Return(jen.Nil(), jen.Err()),
		)

		// Apply options
		grp.Id("cfg").Op(":=").Op("&").Qual(entityPkg, pagerCfg).Values()
		grp.For(jen.List(jen.Id("_"), jen.Id("opt")).Op(":=").Range().Id("opts")).Block(
			jen.Id("opt").Call(jen.Id("cfg")),
		)

		// Apply filter. After cycle-break, filter returns a predicate (not a
		// modified query) so we can break the filter/ -> query/ import edge.
		grp.If(jen.Id("cfg").Dot("Filter").Op("!=").Nil()).BlockFunc(func(filterGrp *jen.Group) {
			predicatePkg := g.config.ORMPackage + "/predicate"
			filterGrp.List(jen.Id("f"), jen.Id("ok")).Op(":=").Id("cfg").Dot("Filter").Op(".").Parens(
				jen.Func().Params().Params(jen.Qual(predicatePkg, t.Name), jen.Error()),
			)
			filterGrp.If(jen.Op("!").Id("ok")).Block(
				jen.Return(jen.Nil(), jen.Qual("fmt", "Errorf").Call(
					jen.Lit("pagination: invalid filter type %T"), jen.Id("cfg").Dot("Filter"),
				)),
			)
			filterGrp.List(jen.Id("p"), jen.Id("err")).Op(":=").Id("f").Call()
			filterGrp.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Id("err")),
			)
			filterGrp.If(jen.Id("p").Op("!=").Nil()).Block(
				jen.Id("q").Dot("Where").Call(jen.Id("p")),
			)
		})

		// Apply predicate. After Plan 2 cycle-break, edge methods accept
		// *filter.XxxWhereInput directly and call .Filter() at the call site
		// to get a predicate, then pass it via WithXxxPredicate. No closure
		// indirection, no type assertion. Coexists with cfg.Filter for
		// backward compatibility — both apply if set.
		grp.If(jen.Id("cfg").Dot("Predicate").Op("!=").Nil()).Block(
			jen.Id("q").Dot("Where").Call(jen.Id("cfg").Dot("Predicate")),
		)

		// Apply order — use query builder methods directly (same package).
		grp.If(jen.Id("cfg").Dot("Order").Op("!=").Nil().Op("&&").Id("cfg").Dot("Order").Dot("Field").Op("!=").Nil()).BlockFunc(func(orderGrp *jen.Group) {
			orderGrp.Id("q").Dot("Order").Call(
				jen.Qual("github.com/syssam/velox/dialect/sql", "OrderByField").Call(
					jen.Id("cfg").Dot("Order").Dot("Field").Dot("Column"),
					jen.Qual(gqlrelayPkg, "DirectionOrderTerm").Call(jen.Id("cfg").Dot("Order").Dot("Direction")),
				).Dot("ToFunc").Call(),
			)
			orderGrp.Id("q").Dot("Order").Call(
				jen.Qual("github.com/syssam/velox/dialect/sql", "OrderByField").Call(
					jen.Qual(subEntityPkg, idColumn),
					jen.Qual(gqlrelayPkg, "DirectionOrderTerm").Call(jen.Id("cfg").Dot("Order").Dot("Direction")),
				).Dot("ToFunc").Call(),
			)
		}).Else().Block(
			jen.Id("q").Dot("Order").Call(
				jen.Qual("github.com/syssam/velox/dialect/sql", "OrderByField").Call(
					jen.Qual(subEntityPkg, idColumn),
				).Dot("ToFunc").Call(),
			),
		)

		// Apply cursors
		grp.If(jen.Id("after").Op("!=").Nil().Op("||").Id("before").Op("!=").Nil()).BlockFunc(func(cursorGrp *jen.Group) {
			cursorGrp.Var().Id("orderField").String()
			cursorGrp.Var().Id("orderDir").Qual(gqlrelayPkg, "OrderDirection")
			cursorGrp.If(jen.Id("cfg").Dot("Order").Op("!=").Nil().Op("&&").Id("cfg").Dot("Order").Dot("Field").Op("!=").Nil()).Block(
				jen.Id("orderField").Op("=").Id("cfg").Dot("Order").Dot("Field").Dot("Column"),
				jen.Id("orderDir").Op("=").Id("cfg").Dot("Order").Dot("Direction"),
			)
			cursorGrp.For(jen.List(jen.Id("_"), jen.Id("p")).Op(":=").Range().Qual(gqlrelayPkg, "CursorsPredicate").Call(
				jen.Id("after"), jen.Id("before"), jen.Qual(subEntityPkg, idColumn), jen.Id("orderField"), jen.Id("orderDir"),
			)).Block(
				jen.Id("q").Dot("Where").Call(jen.Id("p")),
			)
		})

		// Count total (before limit). Clone returns UserQuerier which has Count.
		grp.List(jen.Id("totalCount"), jen.Id("err")).Op(":=").Id("q").Dot("Clone").Call().Dot("Count").Call(jen.Id("ctx"))
		grp.If(jen.Err().Op("!=").Nil()).Block(
			jen.Return(jen.Nil(), jen.Err()),
		)

		// Apply limit (+1 probe row for hasNext/hasPrev detection; trimmed in Build*Connection).
		grp.If(jen.Id("first").Op("!=").Nil()).Block(
			jen.Id("q").Dot("Limit").Call(jen.Op("*").Id("first").Op("+").Lit(1)),
		).Else().If(jen.Id("last").Op("!=").Nil()).Block(
			jen.Id("q").Dot("Limit").Call(jen.Op("*").Id("last").Op("+").Lit(1)),
		)

		// Fetch
		grp.List(jen.Id("nodes"), jen.Id("err")).Op(":=").Id("q").Dot("All").Call(jen.Id("ctx"))
		grp.If(jen.Err().Op("!=").Nil()).Block(
			jen.Return(jen.Nil(), jen.Err()),
		)

		// Delegate assembly to entity.BuildXxxConnection — the SAME helper
		// used by edge-resolver fast paths. Keeping one source of truth for
		// cursor/pageInfo/edge construction means the slow path and fast
		// path can't drift (which is exactly what was making the pre-fix
		// velox behave differently from Ent on eager-loaded edges).
		grp.Return(
			jen.Qual(entityPkg, "Build"+connName).Call(
				jen.Id("nodes"),
				jen.Id("totalCount"),
				jen.Id("cfg").Dot("Order"),
				jen.Id("after"),
				jen.Id("first"),
				jen.Id("before"),
				jen.Id("last"),
			),
			jen.Nil(),
		)
	})

	return f
}

// isOrderableField returns true if the field can be used for ordering.
// Text fields (unbounded size, i.e., Size >= math.MaxInt32) are excluded
// because ordering by large text columns is inefficient and rarely useful.
// Orderable types: String (non-Text), Int, Int64, Float32, Float64, Bool, Enum, Time.
func (g *Generator) isOrderableField(field *gen.Field) bool {
	if field.IsString() {
		col := field.Column()
		// Exclude Text fields (field.Text() sets Size = math.MaxInt32).
		if col.Size >= math.MaxInt32 {
			return false
		}
		return true
	}
	return field.IsTime() || field.IsInt() || field.IsInt64() || field.IsBool() || field.IsEnum() || field.Type.Type.Float()
}

// orderableFields returns the orderable fields for a type, filtering out skipped fields.
func (g *Generator) orderableFields(t *gen.Type) []*gen.Field {
	fields := g.filterFields(t.Fields, SkipOrderField)
	var result []*gen.Field
	for _, fld := range fields {
		if g.isOrderableField(fld) {
			result = append(result, fld)
		}
	}
	return result
}

// typeReceiver generates a receiver name for a type following Ent's convention.
func typeReceiver(name string) string {
	s := toSnakeCase(name)
	parts := strings.Split(s, "_")

	var r strings.Builder
	for _, part := range parts {
		if part != "" {
			r.WriteByte(part[0])
		}
	}

	result := r.String()
	if result == "" {
		return strings.ToLower(name[:1])
	}
	return result
}

// genPaginationShared generates shared pagination type aliases for the entity/ package.
func (g *Generator) genPaginationShared() *jen.File {
	f := jen.NewFilePathName(g.config.ORMPackage+"/entity", "entity")
	f.HeaderComment("Code generated by velox. DO NOT EDIT.")

	f.ImportName(gqlrelayPkg, "gqlrelay")

	f.Comment("Shared pagination types from gqlrelay.")
	f.Type().Defs(
		jen.Id("OrderDirection").Op("=").Qual(gqlrelayPkg, "OrderDirection"),
		jen.Id("Cursor").Op("=").Qual(gqlrelayPkg, "Cursor"),
		jen.Id("PageInfo").Op("=").Qual(gqlrelayPkg, "PageInfo"),
	)

	f.Const().Defs(
		jen.Id("OrderDirectionAsc").Op("=").Qual(gqlrelayPkg, "OrderDirectionAsc"),
		jen.Id("OrderDirectionDesc").Op("=").Qual(gqlrelayPkg, "OrderDirectionDesc"),
	)

	f.Var().Id("ErrInvalidPagination").Op("=").Qual(gqlrelayPkg, "ErrInvalidPagination")

	return f
}

// genModelPaginationTypes generates Connection, Edge, Order, OrderField,
// PagerConfig, and PaginateOption types for all entities into
// gql_pagination.go in the entity/ package.
// Entity types live in entity/ so pagination types reference them directly.
func (g *Generator) genModelPaginationTypes(nodes []*gen.Type) *jen.File {
	if g.config.ORMPackage == "" {
		return nil
	}

	f := jen.NewFilePathName(g.config.ORMPackage+"/entity", "entity")
	f.HeaderComment("Code generated by velox. DO NOT EDIT.")

	// Imports
	f.ImportName("io", "io")
	f.ImportName("strconv", "strconv")
	f.ImportName("fmt", "fmt")
	f.ImportName("github.com/syssam/velox", "velox")
	f.ImportName("github.com/syssam/velox/dialect/sql", "sql")
	f.ImportName(gqlrelayPkg, "gqlrelay")

	// All types reference entity structs directly (same package).
	for _, t := range nodes {
		g.genModelPaginationDefs(f, t)
	}

	// Generate Paginatable interfaces for type assertion in edge methods.
	// Edge methods use q.(UserPaginatable).Paginate(...) since the querier
	// interface doesn't include Paginate (it's added by the graphql extension).
	for _, t := range nodes {
		g.genPaginatableInterface(f, t)
	}

	return f
}

// genModelPaginationDefs generates all pagination type definitions for a single entity.
// Types are local to the root package — entity struct references use jen.Id (same package).
func (g *Generator) genModelPaginationDefs(f *jen.File, t *gen.Type) {
	typeName := g.graphqlTypeName(t)
	receiver := typeReceiver(t.Name)
	multiOrder := g.hasMultiOrder(t)

	edgeName := typeName + "Edge"
	connName := typeName + "Connection"
	pagerConfigName := typeName + "PagerConfig"
	optName := typeName + "PaginateOption"
	orderName := typeName + "Order"
	orderFieldName := typeName + "OrderField"
	defaultOrderName := "Default" + typeName + "Order"

	// --- Edge and Connection: non-generic structs to avoid monomorphization ---
	f.Comment(fmt.Sprintf("%s is the edge representation of %s.", edgeName, typeName))
	f.Type().Id(edgeName).Struct(
		jen.Id("Node").Op("*").Id(typeName).Tag(map[string]string{"json": "node"}),
		jen.Id("Cursor").Qual(gqlrelayPkg, "Cursor").Tag(map[string]string{"json": "cursor"}),
	)
	f.Line()

	f.Comment(fmt.Sprintf("%s is the connection containing edges to %s.", connName, typeName))
	f.Type().Id(connName).Struct(
		jen.Id("Edges").Index().Op("*").Id(edgeName).Tag(map[string]string{"json": "edges"}),
		jen.Id("PageInfo").Qual(gqlrelayPkg, "PageInfo").Tag(map[string]string{"json": "pageInfo"}),
		jen.Id("TotalCount").Int().Tag(map[string]string{"json": "totalCount"}),
	)
	f.Line()

	f.Line()

	// --- PaginateOption type ---
	f.Comment(fmt.Sprintf("%s enables pagination customization.", optName))
	f.Type().Id(optName).Func().Params(jen.Op("*").Id(pagerConfigName))
	f.Line()

	// --- PagerConfig struct ---
	predicatePkg := g.config.ORMPackage + "/predicate"
	f.Comment(fmt.Sprintf("%s holds pagination configuration for %s.", pagerConfigName, typeName))
	if multiOrder {
		f.Type().Id(pagerConfigName).Struct(
			jen.Id("Order").Index().Op("*").Id(orderName),
			jen.Comment("Filter is a typed filter function stored as any to avoid circular imports."),
			jen.Comment("The actual type is func(*XxxQuery) (*XxxQuery, error)."),
			jen.Id("Filter").Any(),
			jen.Comment("Predicate is applied directly via q.Where(p) — preferred over Filter."),
			jen.Comment("Set by WithXxxPredicate; coexists with Filter for backward compatibility."),
			jen.Id("Predicate").Qual(predicatePkg, t.Name),
		)
	} else {
		f.Type().Id(pagerConfigName).Struct(
			jen.Id("Order").Op("*").Id(orderName),
			jen.Comment("Filter is a typed filter function stored as any to avoid circular imports."),
			jen.Comment("The actual type is func(*XxxQuery) (*XxxQuery, error)."),
			jen.Id("Filter").Any(),
			jen.Comment("Predicate is applied directly via q.Where(p) — preferred over Filter."),
			jen.Comment("Set by WithXxxPredicate; coexists with Filter for backward compatibility."),
			jen.Id("Predicate").Qual(predicatePkg, t.Name),
		)
	}
	f.Line()

	// --- OrderField struct ---
	f.Comment(fmt.Sprintf("%s defines the ordering field of %s.", orderFieldName, t.Name))
	f.Type().Id(orderFieldName).Struct(
		jen.Id("Column").String(),
		jen.Id("ToCursor").Func().Params(jen.Op("*").Id(typeName)).Qual(gqlrelayPkg, "Cursor"),
	)
	f.Line()

	// --- Order struct ---
	f.Comment(fmt.Sprintf("%s defines the ordering of %s.", orderName, t.Name))
	f.Type().Id(orderName).Struct(
		jen.Id("Direction").Qual(gqlrelayPkg, "OrderDirection").Tag(map[string]string{"json": "direction"}),
		jen.Id("Field").Op("*").Id(orderFieldName).Tag(map[string]string{"json": "field"}),
	)
	f.Line()

	// --- DefaultOrder variable ---
	g.genModelDefaultOrder(f, t, typeName, receiver, orderName, orderFieldName, defaultOrderName)

	// --- OrderField variables for each orderable field ---
	g.genModelOrderFieldVars(f, t, typeName, receiver, orderFieldName)

	// --- OrderField methods (String, MarshalGQL, UnmarshalGQL) ---
	g.genModelOrderFieldMethods(f, t, typeName, orderFieldName)

	// --- ToEdge method on entity ---
	f.Comment(fmt.Sprintf("ToEdge converts %s into %s.", typeName, edgeName))
	f.Func().Params(
		jen.Id(receiver).Op("*").Id(typeName),
	).Id("ToEdge").Params(
		jen.Id("order").Op("*").Id(orderName),
	).Op("*").Id(edgeName).Block(
		jen.If(jen.Id("order").Op("==").Nil()).Block(
			jen.Id("order").Op("=").Id(defaultOrderName),
		),
		jen.Return(jen.Op("&").Id(edgeName).Values(
			jen.Id("Node").Op(":").Id(receiver),
			jen.Id("Cursor").Op(":").Id("order").Dot("Field").Dot("ToCursor").Call(jen.Id(receiver)),
		)),
	)
	f.Line()

	// --- WithOrder function ---
	g.genModelWithOrder(f, typeName, optName, orderName, pagerConfigName, defaultOrderName, multiOrder)

	// --- WithFilter function ---
	g.genModelWithFilter(f, typeName, optName, pagerConfigName)

	// --- WithPredicate function ---
	g.genModelWithPredicate(f, t, typeName, optName, pagerConfigName)

	// --- BuildConnection helper ---
	// Shared "assemble a connection from a node slice" helper. Used by BOTH
	// the slow path (query.XxxQuery.Paginate, which does a fresh DB query)
	// AND the fast path (edge-resolver methods that reuse eager-loaded edges
	// without hitting the database). Before this helper was factored out, the
	// build-connection logic was inlined in Paginate only, which is why edge
	// resolvers had to always go through Paginate — they had no other way to
	// reach the cursor/pageInfo assembly. Keeping a single source of truth
	// here means the fast path is a strict optimization of the slow path and
	// can't drift.
	g.genModelBuildConnection(f, t, typeName, connName, edgeName, orderName, multiOrder)
}

// genModelDefaultOrder generates the DefaultOrder variable in the root package.
func (g *Generator) genModelDefaultOrder(f *jen.File, t *gen.Type, typeName, receiver, orderName, orderFieldName, defaultOrderName string) {
	if t.ID == nil {
		return
	}
	idField := "ID"
	if !strings.EqualFold(t.ID.Name, "id") {
		idField = pascal(t.ID.Name)
	}

	idStorageKey := t.ID.StorageKey()

	f.Comment(fmt.Sprintf("%s is the default ordering of %s.", defaultOrderName, t.Name))
	f.Var().Id(defaultOrderName).Op("=").Op("&").Id(orderName).Values(
		jen.Id("Direction").Op(":").Qual(gqlrelayPkg, "OrderDirectionAsc"),
		jen.Id("Field").Op(":").Op("&").Id(orderFieldName).Values(
			jen.Id("Column").Op(":").Lit(idStorageKey),
			jen.Id("ToCursor").Op(":").Func().Params(jen.Id(receiver).Op("*").Id(typeName)).Qual(gqlrelayPkg, "Cursor").Block(
				jen.Return(jen.Qual(gqlrelayPkg, "Cursor").Values(jen.Id("ID").Op(":").Id(receiver).Dot(idField))),
			),
		),
	)
	f.Line()
}

// genModelOrderFieldVars generates order field variables in the root package.
func (g *Generator) genModelOrderFieldVars(f *jen.File, t *gen.Type, typeName, receiver, orderFieldName string) {
	orderableFields := g.orderableFields(t)
	if len(orderableFields) == 0 {
		return
	}

	f.Var().DefsFunc(func(group *jen.Group) {
		for _, fld := range orderableFields {
			varName := camel(typeName) + "By" + pascal(fld.Name)
			structField := pascal(fld.Name)

			group.Comment(fmt.Sprintf("%s orders %s by %s.", varName, t.Name, fld.Name))
			storageKey := fld.StorageKey()
			group.Id(varName).Op("=").Op("&").Id(orderFieldName).Values(
				jen.Id("Column").Op(":").Lit(storageKey),
				jen.Id("ToCursor").Op(":").Func().Params(jen.Id(receiver).Op("*").Id(typeName)).Qual(gqlrelayPkg, "Cursor").BlockFunc(func(blk *jen.Group) {
					if fld.Nillable {
						// Nillable fields are pointers — dereference safely to avoid nil in cursor serialization.
						blk.Id("cv").Op(":=").Qual(gqlrelayPkg, "Cursor").Values(jen.Id("ID").Op(":").Id(receiver).Dot("ID"))
						blk.If(jen.Id(receiver).Dot(structField).Op("!=").Nil()).Block(
							jen.Id("cv").Dot("Value").Op("=").Op("*").Id(receiver).Dot(structField),
						)
						blk.Return(jen.Id("cv"))
					} else {
						blk.Return(jen.Qual(gqlrelayPkg, "Cursor").Values(
							jen.Id("ID").Op(":").Id(receiver).Dot("ID"),
							jen.Id("Value").Op(":").Id(receiver).Dot(structField),
						))
					}
				}),
			)
		}
	})
	f.Line()
}

// genModelOrderFieldMethods generates String, MarshalGQL, UnmarshalGQL methods
// for the OrderField type in the root package.
func (g *Generator) genModelOrderFieldMethods(f *jen.File, t *gen.Type, typeName, orderFieldName string) {
	orderableFields := g.orderableFields(t)

	// String method
	f.Comment("String implement fmt.Stringer interface.")
	f.Func().Params(jen.Id("f").Id(orderFieldName)).Id("String").Params().String().BlockFunc(func(group *jen.Group) {
		group.Var().Id("str").String()
		group.Switch(jen.Id("f").Dot("Column")).BlockFunc(func(sw *jen.Group) {
			for _, fld := range orderableFields {
				varName := camel(typeName) + "By" + pascal(fld.Name)
				gqlName := g.getOrderFieldName(fld)
				sw.Case(jen.Id(varName).Dot("Column")).Block(
					jen.Id("str").Op("=").Lit(gqlName),
				)
			}
			sw.Default().Block(
				jen.Qual("log/slog", "Warn").Call(
					jen.Lit("unknown "+orderFieldName+" column"),
					jen.Lit("column"), jen.Id("f").Dot("Column"),
				),
			)
		})
		group.Return(jen.Id("str"))
	})
	f.Line()

	// MarshalGQL method
	f.Comment("MarshalGQL implements graphql.Marshaler interface.")
	f.Func().Params(jen.Id("f").Id(orderFieldName)).Id("MarshalGQL").Params(
		jen.Id("w").Qual("io", "Writer"),
	).Block(
		jen.Qual("io", "WriteString").Call(jen.Id("w"), jen.Qual("strconv", "Quote").Call(jen.Id("f").Dot("String").Call())),
	)
	f.Line()

	// UnmarshalGQL method
	f.Comment("UnmarshalGQL implements graphql.Unmarshaler interface.")
	f.Func().Params(jen.Id("f").Op("*").Id(orderFieldName)).Id("UnmarshalGQL").Params(
		jen.Id("v").Any(),
	).Error().BlockFunc(func(group *jen.Group) {
		group.List(jen.Id("str"), jen.Id("ok")).Op(":=").Id("v").Assert(jen.String())
		group.If(jen.Op("!").Id("ok")).Block(
			jen.Return(jen.Qual("fmt", "Errorf").Call(jen.Lit(orderFieldName+" %T must be a string"), jen.Id("v"))),
		)
		group.Switch(jen.Id("str")).BlockFunc(func(sw *jen.Group) {
			for _, fld := range orderableFields {
				varName := camel(typeName) + "By" + pascal(fld.Name)
				gqlName := g.getOrderFieldName(fld)
				sw.Case(jen.Lit(gqlName)).Block(
					jen.Op("*").Id("f").Op("=").Op("*").Id(varName),
				)
			}
			sw.Default().Block(
				jen.Return(jen.Qual("fmt", "Errorf").Call(jen.Lit("%s is not a valid "+orderFieldName), jen.Id("str"))),
			)
		})
		group.Return(jen.Nil())
	})
	f.Line()
}

// genModelWithOrder generates the WithOrder function in the root package.
func (g *Generator) genModelWithOrder(f *jen.File, typeName, optName, orderName, pagerConfigName, defaultOrderName string, multiOrder bool) {
	optOrderName := "With" + typeName + "Order"
	f.Comment(fmt.Sprintf("%s configures pagination ordering.", optOrderName))

	if multiOrder {
		f.Func().Id(optOrderName).Params(
			jen.Id("order").Index().Op("*").Id(orderName),
		).Params(jen.Id(optName), jen.Error()).BlockFunc(func(grp *jen.Group) {
			grp.For(jen.List(jen.Id("_"), jen.Id("o")).Op(":=").Range().Id("order")).Block(
				jen.If(jen.Id("err").Op(":=").Id("o").Dot("Direction").Dot("Validate").Call(), jen.Id("err").Op("!=").Nil()).Block(
					jen.Return(jen.Nil(), jen.Id("err")),
				),
			)
			grp.Return(jen.Func().Params(jen.Id("cfg").Op("*").Id(pagerConfigName)).Block(
				jen.Id("cfg").Dot("Order").Op("=").Append(jen.Id("cfg").Dot("Order"), jen.Id("order").Op("...")),
			), jen.Nil())
		})
	} else {
		f.Func().Id(optOrderName).Params(
			jen.Id("order").Op("*").Id(orderName),
		).Id(optName).Block(
			jen.Return(jen.Func().Params(jen.Id("cfg").Op("*").Id(pagerConfigName)).Block(
				jen.If(jen.Id("order").Op("==").Nil()).Block(
					jen.Id("order").Op("=").Id(defaultOrderName),
				),
				jen.Id("cfg").Dot("Order").Op("=").Id("order"),
			)),
		)
	}
	f.Line()
}

// genModelWithFilter generates WithXxxFilter function.
// The filter is stored as `any` in PagerConfig to avoid circular imports
// (entity/ package cannot import filter/ without re-introducing the cycle).
// After the cycle-break refactor, the expected filter type is
// func() (predicate.Xxx, error) — Paginate type-asserts to this shape.
func (g *Generator) genModelWithFilter(f *jen.File, typeName, optName, pagerConfigName string) {
	optFilterName := "With" + typeName + "Filter"
	f.Commentf("%s sets a filter function for %s pagination.", optFilterName, typeName)
	f.Commentf("The filter parameter should be func() (predicate.%s, error).", typeName)
	f.Func().Id(optFilterName).Params(
		jen.Id("filter").Any(),
	).Id(optName).Block(
		jen.Return(jen.Func().Params(jen.Id("cfg").Op("*").Id(pagerConfigName)).Block(
			jen.Id("cfg").Dot("Filter").Op("=").Id("filter"),
		)),
	)
	f.Line()
}

// genModelWithPredicate generates WithXxxPredicate function — the typed
// successor to WithXxxFilter. Plan 2 broke the entity -> filter -> query
// import cycle, so filter/.WhereInput.Filter() now returns a typed
// predicate.Xxx directly (no closure-of-closure shape). The edge method
// can call Filter() at the call site and pass the resulting predicate
// to Paginate via this option, skipping the type-assertion dance that
// the legacy Filter (any) field forces.
//
// WithXxxFilter coexists for backward compatibility: callers that built
// against the Plan 1/Plan 2 surface keep working without recompilation.
func (g *Generator) genModelWithPredicate(f *jen.File, t *gen.Type, typeName, optName, pagerConfigName string) {
	predicatePkg := g.config.ORMPackage + "/predicate"
	optPredicateName := "With" + typeName + "Predicate"
	f.Commentf("%s sets a predicate to apply during %s pagination.", optPredicateName, typeName)
	f.Func().Id(optPredicateName).Params(
		jen.Id("p").Qual(predicatePkg, t.Name),
	).Id(optName).Block(
		jen.Return(jen.Func().Params(jen.Id("cfg").Op("*").Id(pagerConfigName)).Block(
			jen.Id("cfg").Dot("Predicate").Op("=").Id("p"),
		)),
	)
	f.Line()
}

// genPaginatableInterface generates the Paginatable interface for an entity.
// Edge methods use type assertion to call Paginate on querier results:
//
//	p, ok := q.(entity.UserPaginatable)
//	return p.Paginate(ctx, after, first, before, last, opts...)
func (g *Generator) genPaginatableInterface(f *jen.File, t *gen.Type) {
	typeName := g.graphqlTypeName(t)
	ifaceName := typeName + "Paginatable"
	connName := typeName + "Connection"
	optName := typeName + "PaginateOption"

	f.Commentf("%s is implemented by query types that support Relay cursor pagination.", ifaceName)
	f.Type().Id(ifaceName).Interface(
		jen.Id("Paginate").Params(
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("after").Op("*").Qual(gqlrelayPkg, "Cursor"),
			jen.Id("first").Op("*").Int(),
			jen.Id("before").Op("*").Qual(gqlrelayPkg, "Cursor"),
			jen.Id("last").Op("*").Int(),
			jen.Id("opts").Op("...").Id(optName),
		).Params(
			jen.Op("*").Id(connName),
			jen.Error(),
		),
	)
}

// genRootPaginationHelpers generates root-package helpers for pagination
// (WithXxxOrder, WithXxxFilter convenience re-exports).
// Returns nil when no helpers are needed (@goModel points directly to entity/).
func (g *Generator) genRootPaginationHelpers(_ []*gen.Type) *jen.File {
	// @goModel directives point directly to entity/ sub-package.
	// No root re-exports needed.
	return nil
}

// genModelBuildConnection emits BuildXxxConnection — the shared in-memory
// assembly helper used by both the slow path (full Paginate with fresh DB
// query) and the fast path (edge resolvers reusing eager-loaded edges).
//
// The helper takes a raw node slice (possibly with +1 probe row, possibly
// just the full eager-loaded set), a known totalCount (or 0 to default to
// len(nodes)), an order spec for cursor generation, and the Relay cursor
// args — and returns a fully populated *XxxConnection.
//
// Matches the semantics of Ent's `func (c *XxxConnection) build(nodes, pager,
// after, first, before, last)` (entgql/internal/todogotype/ent/gql_pagination.go:
// CategoryConnection.build). Ent uses a method on connection plus a private
// pager; velox uses a free function plus the public *XxxOrder — mechanically
// the same output.
func (g *Generator) genModelBuildConnection(f *jen.File, t *gen.Type, typeName, connName, edgeName, orderName string, multiOrder bool) {
	// BuildXxxConnection(nodes, totalCount, order, after, first, before, last) *XxxConnection
	orderParamType := jen.Op("*").Id(orderName)
	if multiOrder {
		orderParamType = jen.Index().Op("*").Id(orderName)
	}

	// Derive the Go field name for the entity's primary key for use in the
	// fallback cursor (when no order field is provided). For the default
	// `id` column this is `ID`; for a schema that overrides the PK name to
	// something like `user_id`, it becomes `UserID`. Matches the rule used
	// by the old inlined Paginate body so the emitted code is byte-for-byte
	// equivalent to the pre-refactor output.
	idField := "ID"
	if t != nil && t.ID != nil && t.ID.Name != "" && t.ID.Name != "id" {
		idField = pascal(t.ID.Name)
	}

	f.Commentf("Build%s assembles a %s from an in-memory node slice, without",
		connName, connName)
	f.Commentf("hitting the database. Shared by query.%sQuery.Paginate (slow",
		typeName)
	f.Comment("path, fresh DB query) and edge-resolver fast paths (reuse of")
	f.Commentf("eager-loaded edges). Input contract matches Ent's CategoryConnection.build:")
	f.Comment("  - nodes may include one probe row (+1 for first/last) — helper trims it")
	f.Comment("    and sets HasNextPage / HasPreviousPage accordingly")
	f.Comment("  - totalCount of 0 defaults to len(nodes) — only correct when the caller")
	f.Comment("    has the full set (e.g. eager-loaded edges). The slow path always")
	f.Comment("    passes a real count.")
	f.Commentf("  - order is used only for cursor generation (order.Field.ToCursor); it")
	f.Comment("    does NOT filter or sort — callers must pass nodes already in the right")
	f.Comment("    order, because in-memory resorting would silently disagree with the")
	f.Comment("    cursor comparator at the DB level.")

	f.Func().Id("Build"+connName).Params(
		jen.Id("nodes").Index().Op("*").Id(typeName),
		jen.Id("totalCount").Int(),
		jen.Id("order").Add(orderParamType),
		jen.Id("after").Op("*").Qual(gqlrelayPkg, "Cursor"),
		jen.Id("first").Op("*").Int(),
		jen.Id("before").Op("*").Qual(gqlrelayPkg, "Cursor"),
		jen.Id("last").Op("*").Int(),
	).Op("*").Id(connName).BlockFunc(func(grp *jen.Group) {
		grp.Id("conn").Op(":=").Op("&").Id(connName).Values(jen.Dict{
			jen.Id("TotalCount"): jen.Id("totalCount"),
		})

		// Trim probe row and set HasNextPage / HasPreviousPage.
		grp.Id("limit").Op(":=").Len(jen.Id("nodes"))
		grp.If(jen.Id("first").Op("!=").Nil().Op("&&").Id("limit").Op(">").Op("*").Id("first")).Block(
			jen.Id("nodes").Op("=").Id("nodes").Index(jen.Empty(), jen.Op("*").Id("first")),
			jen.Id("conn").Dot("PageInfo").Dot("HasNextPage").Op("=").True(),
		)
		grp.If(jen.Id("last").Op("!=").Nil().Op("&&").Id("limit").Op(">").Op("*").Id("last")).Block(
			jen.Id("nodes").Op("=").Id("nodes").Index(jen.Id("limit").Op("-").Op("*").Id("last"), jen.Empty()),
			jen.Id("conn").Dot("PageInfo").Dot("HasPreviousPage").Op("=").True(),
		)
		grp.If(jen.Id("before").Op("!=").Nil()).Block(
			jen.Id("conn").Dot("PageInfo").Dot("HasNextPage").Op("=").True(),
		)
		grp.If(jen.Id("after").Op("!=").Nil()).Block(
			jen.Id("conn").Dot("PageInfo").Dot("HasPreviousPage").Op("=").True(),
		)

		// Resolve the cursor-generation function ONCE outside the edge
		// loop. Before this hoist, the loop had 3 nil checks per iteration
		// (order/order.Field/order.Field.ToCursor) which predictably
		// short-circuit to the same branch across all edges — branch
		// prediction handles it but the code is cleaner this way, and
		// matches Ent's pager.toCursor abstraction. Also critical for
		// the `last` handling below — we index backward through the
		// same function.
		var orderExpr *jen.Statement
		if multiOrder {
			orderExpr = jen.Id("order").Index(jen.Lit(0))
		} else {
			orderExpr = jen.Id("order")
		}
		var orderPresent *jen.Statement
		if multiOrder {
			orderPresent = jen.Len(jen.Id("order")).Op(">").Lit(0)
		} else {
			orderPresent = jen.Id("order").Op("!=").Nil()
		}
		grp.Var().Id("cursorFn").Func().Params(jen.Op("*").Id(typeName)).Qual(gqlrelayPkg, "Cursor")
		grp.If(
			orderPresent.Op("&&").Add(orderExpr.Clone().Dot("Field")).Op("!=").Nil().Op("&&").Add(orderExpr.Clone().Dot("Field").Dot("ToCursor")).Op("!=").Nil(),
		).Block(
			jen.Id("cursorFn").Op("=").Add(orderExpr.Clone()).Dot("Field").Dot("ToCursor"),
		).Else().Block(
			jen.Id("cursorFn").Op("=").Func().Params(jen.Id("n").Op("*").Id(typeName)).Qual(gqlrelayPkg, "Cursor").Block(
				jen.Return(jen.Qual(gqlrelayPkg, "Cursor").Values(jen.Dict{
					jen.Id("ID"): jen.Id("n").Dot(idField),
				})),
			),
		)

		// Build edges. For `last != nil`, we index backward through the
		// input slice WITHOUT mutating it — nodes may be pointer-shared
		// with obj.Edges.Xxx on the fast path, and an in-place reverse
		// would corrupt the caller's eager-loaded cache. Matches Ent's
		// CategoryConnection.build which uses a nodeAt() index function
		// for the same reason.
		grp.Id("conn").Dot("Edges").Op("=").Make(jen.Index().Op("*").Id(edgeName), jen.Len(jen.Id("nodes")))
		grp.If(jen.Id("last").Op("!=").Nil()).Block(
			// Reverse iteration: output[i] = input[len-1-i], no mutation.
			jen.Id("n").Op(":=").Len(jen.Id("nodes")).Op("-").Lit(1),
			jen.For(jen.Id("i").Op(":=").Range().Id("nodes")).Block(
				jen.Id("node").Op(":=").Id("nodes").Index(jen.Id("n").Op("-").Id("i")),
				jen.Id("conn").Dot("Edges").Index(jen.Id("i")).Op("=").Op("&").Id(edgeName).Values(jen.Dict{
					jen.Id("Node"):   jen.Id("node"),
					jen.Id("Cursor"): jen.Id("cursorFn").Call(jen.Id("node")),
				}),
			),
		).Else().Block(
			jen.For(jen.List(jen.Id("i"), jen.Id("node")).Op(":=").Range().Id("nodes")).Block(
				jen.Id("conn").Dot("Edges").Index(jen.Id("i")).Op("=").Op("&").Id(edgeName).Values(jen.Dict{
					jen.Id("Node"):   jen.Id("node"),
					jen.Id("Cursor"): jen.Id("cursorFn").Call(jen.Id("node")),
				}),
			),
		)

		// Set start/end cursors.
		grp.If(jen.Len(jen.Id("conn").Dot("Edges")).Op(">").Lit(0)).Block(
			jen.Id("conn").Dot("PageInfo").Dot("StartCursor").Op("=").Op("&").Id("conn").Dot("Edges").Index(jen.Lit(0)).Dot("Cursor"),
			jen.Id("conn").Dot("PageInfo").Dot("EndCursor").Op("=").Op("&").Id("conn").Dot("Edges").Index(jen.Len(jen.Id("conn").Dot("Edges")).Op("-").Lit(1)).Dot("Cursor"),
		)

		// Default totalCount = len(edges) when 0 — only meaningful for the
		// fast path where the caller doesn't know the true count yet but has
		// the full eager-loaded slice. The slow path always passes a real
		// count from COUNT(*), so conn.TotalCount != 0 at that point.
		grp.If(jen.Id("conn").Dot("TotalCount").Op("==").Lit(0)).Block(
			jen.Id("conn").Dot("TotalCount").Op("=").Len(jen.Id("conn").Dot("Edges")),
		)

		grp.Return(jen.Id("conn"))
	})
	f.Line()
}
