package graphql

// Node generator: generates per-entity Node/IsNode and registry-based dispatch.
// Output: {entity}/gql_node.go (~20 lines instead of ~155)
// Root gql_node.go: ~50 lines instead of ~9,000

import (
	"github.com/dave/jennifer/jen"

	"github.com/syssam/velox/compiler/gen"
	"github.com/syssam/velox/schema/field"
)

// genEntityNode generates a per-entity node file for the entity sub-package.
// Registers the entity's node resolver at init time and provides IsNode marker.
func (g *Generator) genEntityNode(t *gen.Type) *jen.File {
	f := jen.NewFilePath(g.entityPkgPath(t))
	f.HeaderComment("Code generated by velox. DO NOT EDIT.")

	f.ImportName(runtimePkgPath, "runtime")

	// Implementors variable
	interfaces := g.collectInterfaces(t)
	f.Comment("Implementors lists the GraphQL interfaces this entity implements.")
	f.Var().Id("Implementors").Op("=").Index().String().ValuesFunc(func(vals *jen.Group) {
		for _, iface := range interfaces {
			vals.Lit(iface)
		}
	})

	// Generate Node(ctx) method for NodeDescriptor introspection (like Ent's WithNodeDescriptor).
	if g.config.NodeDescriptor {
		g.genEntityNodeDescriptor(f, t)
	}

	return f
}

// genEntityNodeDescriptor generates the Node(ctx) method on an entity type.
// The method returns a NodeDescriptor with JSON-serialized field values and edge IDs.
// This enables admin-tool introspection like Ent's gql_node_descriptor.go.
func (g *Generator) genEntityNodeDescriptor(f *jen.File, t *gen.Type) {
	typeName := t.Name
	fields := g.filterFields(t.Fields, SkipType)
	edges := g.filterEdges(t.Edges, SkipType)

	f.ImportName("context", "context")
	f.ImportName("encoding/json", "json")
	f.ImportName(gqlrelayPkg, "gqlrelay")

	f.Commentf("Node returns a NodeDescriptor for admin-tool introspection of %s.", typeName)
	f.Func().Params(
		jen.Id("e").Op("*").Id(typeName),
	).Id("Node").Params(
		jen.Id("ctx").Qual("context", "Context"),
	).Params(
		jen.Op("*").Qual(gqlrelayPkg, "NodeDescriptor"),
		jen.Error(),
	).BlockFunc(func(grp *jen.Group) {
		grp.Id("node").Op(":=").Op("&").Qual(gqlrelayPkg, "NodeDescriptor").Values(jen.Dict{
			jen.Id("ID"):     jen.Id("e").Dot("ID"),
			jen.Id("Type"):   jen.Lit(typeName),
			jen.Id("Fields"): jen.Make(jen.Index().Op("*").Qual(gqlrelayPkg, "FieldDescriptor"), jen.Lit(0), jen.Lit(len(fields))),
			jen.Id("Edges"):  jen.Make(jen.Index().Op("*").Qual(gqlrelayPkg, "EdgeDescriptor"), jen.Lit(0), jen.Lit(len(edges))),
		})

		// Marshal each field value to JSON
		if len(fields) > 0 {
			grp.Var().Id("buf").Index().Byte()
			for _, fd := range fields {
				fieldName := pascal(fd.Name)
				grp.List(jen.Id("buf"), jen.Id("err")).Op("=").Qual("encoding/json", "Marshal").Call(
					jen.Id("e").Dot(fieldName),
				)
				grp.If(jen.Id("err").Op("!=").Nil()).Block(
					jen.Return(jen.Nil(), jen.Qual("fmt", "Errorf").Call(
						jen.Lit("marshal field "+fd.Name+": %w"), jen.Id("err"),
					)),
				)
				grp.Id("node").Dot("Fields").Op("=").Append(
					jen.Id("node").Dot("Fields"),
					jen.Op("&").Qual(gqlrelayPkg, "FieldDescriptor").Values(jen.Dict{
						jen.Id("Name"):  jen.Lit(fd.Name),
						jen.Id("Type"):  jen.Lit(fd.Type.String()),
						jen.Id("Value"): jen.String().Call(jen.Id("buf")),
					}),
				)
			}
		}

		// Load edge IDs
		for _, e := range edges {
			edgeName := pascal(e.Name)
			grp.Id("edge"+edgeName).Op(":=").Op("&").Qual(gqlrelayPkg, "EdgeDescriptor").Values(jen.Dict{
				jen.Id("Name"): jen.Lit(e.Name),
				jen.Id("Type"): jen.Lit(e.Type.Name),
			})
			// Use QueryXxx().IDs(ctx) to load edge IDs
			grp.List(jen.Id("ids"), jen.Id("err")).Op(":=").Id("e").Dot("Query" + edgeName).Call().Dot("IDs").Call(jen.Id("ctx"))
			grp.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Id("err")),
			)
			// Convert to []any for the descriptor
			grp.Id("edgeIDs").Op(":=").Make(jen.Index().Any(), jen.Len(jen.Id("ids")))
			grp.For(jen.List(jen.Id("i"), jen.Id("v")).Op(":=").Range().Id("ids")).Block(
				jen.Id("edgeIDs").Index(jen.Id("i")).Op("=").Id("v"),
			)
			grp.Id("edge" + edgeName).Dot("IDs").Op("=").Id("edgeIDs")
			grp.Id("node").Dot("Edges").Op("=").Append(
				jen.Id("node").Dot("Edges"),
				jen.Id("edge"+edgeName),
			)
		}

		grp.Return(jen.Id("node"), jen.Nil())
	})
}

// genNodeShared generates the root-package node dispatch using the registry pattern.
// ~50 lines instead of ~9,000 (no type-switch over all entities).
func (g *Generator) genNodeShared() *jen.File {
	f := jen.NewFile(g.config.Package)
	f.HeaderComment("Code generated by velox. DO NOT EDIT.")

	f.ImportName("context", "context")
	f.ImportName("fmt", "fmt")
	f.ImportName(runtimePkgPath, "runtime")
	f.ImportName(gqlrelayPkg, "gqlrelay")

	idType := g.graphIDType()

	// Noder interface — defined directly (not as type alias) so gqlgen
	// recognizes it as an interface for @goModel binding.
	f.Comment("Noder is the interface for Relay Node resolution.")
	f.Type().Id("Noder").Interface(
		jen.Id("IsNode").Params(),
	)

	// Error vars
	f.Var().Id("ErrNodeNotFound").Op("=").Qual(gqlrelayPkg, "ErrNodeNotFound")

	// Client.Noder — registry-based dispatch
	f.Comment("Noder returns a Node by its ID using the registered node resolvers.")
	f.Comment("It tries each registered resolver until one succeeds.")
	f.Comment("Not-found errors are skipped; all other errors (e.g., database failures) are returned immediately.")
	f.Func().Params(
		jen.Id("c").Add(g.clientPtrType()),
	).Id("Noder").Params(
		jen.Id("ctx").Qual("context", "Context"),
		jen.Id("id").Add(idType),
	).Params(
		jen.Id("Noder"),
		jen.Error(),
	).Block(
		jen.Id("ctx").Op("=").Qual(runtimePkgPath, "WithConfigContext").Call(jen.Id("ctx"), jen.Id("c").Dot("RuntimeConfig").Call()),
		jen.For(jen.List(jen.Id("_"), jen.Id("resolver")).Op(":=").Range().Qual(runtimePkgPath, "NodeResolvers").Call()).Block(
			jen.List(jen.Id("result"), jen.Id("err")).Op(":=").Id("resolver").Dot("Resolve").Call(jen.Id("ctx"), jen.Id("id")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(
				// Only skip not-found errors; return real errors immediately
				jen.If(jen.Qual(runtimePkgPath, "IsNotFound").Call(jen.Id("err"))).Block(
					jen.Continue(),
				),
				jen.Return(jen.Nil(), jen.Id("err")),
			),
			jen.If(
				jen.List(jen.Id("noder"), jen.Id("ok")).Op(":=").Id("result").Op(".").Parens(jen.Id("Noder")),
				jen.Id("ok"),
			).Block(
				jen.Return(jen.Id("noder"), jen.Nil()),
			),
		),
		jen.Return(jen.Nil(), jen.Id("ErrNodeNotFound")),
	)

	// Client.Noders — batch node resolution.
	// Per the Relay spec, nodes(ids: [ID!]!): [Node]! returns null entries
	// for IDs that cannot be resolved. Real errors are returned immediately.
	f.Comment("Noders returns Nodes by their IDs, resolving each via the registered resolvers.")
	f.Comment("Unresolvable IDs produce nil entries (per Relay spec). Real errors are returned immediately.")
	f.Func().Params(
		jen.Id("c").Add(g.clientPtrType()),
	).Id("Noders").Params(
		jen.Id("ctx").Qual("context", "Context"),
		jen.Id("ids").Index().Add(idType),
	).Params(
		jen.Index().Id("Noder"),
		jen.Error(),
	).Block(
		jen.Id("ctx").Op("=").Qual(runtimePkgPath, "WithConfigContext").Call(jen.Id("ctx"), jen.Id("c").Dot("RuntimeConfig").Call()),
		jen.Id("resolvers").Op(":=").Qual(runtimePkgPath, "NodeResolvers").Call(),
		jen.Id("nodes").Op(":=").Make(jen.Index().Id("Noder"), jen.Len(jen.Id("ids"))),
		jen.For(jen.List(jen.Id("i"), jen.Id("id")).Op(":=").Range().Id("ids")).Block(
			jen.For(jen.List(jen.Id("_"), jen.Id("resolver")).Op(":=").Range().Id("resolvers")).Block(
				jen.List(jen.Id("result"), jen.Id("err")).Op(":=").Id("resolver").Dot("Resolve").Call(jen.Id("ctx"), jen.Id("id")),
				jen.If(jen.Id("err").Op("!=").Nil()).Block(
					jen.If(jen.Qual(runtimePkgPath, "IsNotFound").Call(jen.Id("err"))).Block(
						jen.Continue(),
					),
					jen.Return(jen.Nil(), jen.Id("err")),
				),
				jen.If(
					jen.List(jen.Id("noder"), jen.Id("ok")).Op(":=").Id("result").Op(".").Parens(jen.Id("Noder")),
					jen.Id("ok"),
				).Block(
					jen.Id("nodes").Index(jen.Id("i")).Op("=").Id("noder"),
					jen.Break(),
				),
			),
			jen.Comment("nodes[i] remains nil if no resolver found (per Relay spec)"),
		),
		jen.Return(jen.Id("nodes"), jen.Nil()),
	)

	// NodeDescriptor type aliases
	f.Type().Defs(
		jen.Id("NodeDescriptor").Op("=").Qual(gqlrelayPkg, "NodeDescriptor"),
		jen.Id("FieldDescriptor").Op("=").Qual(gqlrelayPkg, "FieldDescriptor"),
		jen.Id("EdgeDescriptor").Op("=").Qual(gqlrelayPkg, "EdgeDescriptor"),
	)

	// Client.Node — resolve by ID and return NodeDescriptor for admin introspection.
	// Only generated when NodeDescriptor is enabled (like Ent's WithNodeDescriptor).
	if g.config.NodeDescriptor {
		f.Comment("Node returns a NodeDescriptor for the entity with the given ID.")
		f.Comment("Useful for building admin tools that browse all entity types.")
		f.Func().Params(
			jen.Id("c").Add(g.clientPtrType()),
		).Id("Node").Params(
			jen.Id("ctx").Qual("context", "Context"),
			jen.Id("id").Add(idType),
		).Params(
			jen.Op("*").Id("NodeDescriptor"),
			jen.Error(),
		).Block(
			jen.List(jen.Id("n"), jen.Id("err")).Op(":=").Id("c").Dot("Noder").Call(jen.Id("ctx"), jen.Id("id")),
			jen.If(jen.Id("err").Op("!=").Nil()).Block(
				jen.Return(jen.Nil(), jen.Id("err")),
			),
			jen.Type().Id("noder").Interface(
				jen.Id("Node").Params(jen.Qual("context", "Context")).Params(jen.Op("*").Id("NodeDescriptor"), jen.Error()),
			),
			jen.List(jen.Id("nd"), jen.Id("ok")).Op(":=").Id("n").Op(".").Parens(jen.Id("noder")),
			jen.If(jen.Op("!").Id("ok")).Block(
				jen.Return(jen.Nil(), jen.Qual("fmt", "Errorf").Call(jen.Lit("type %T does not implement Node(context.Context) method"), jen.Id("n"))),
			),
			jen.Return(jen.Id("nd").Dot("Node").Call(jen.Id("ctx"))),
		)
	}

	return f
}

// collectInterfaces returns the list of GraphQL interfaces for a type.
func (g *Generator) collectInterfaces(t *gen.Type) []string {
	interfaces := []string{g.graphqlTypeName(t), "Node"}
	// Add custom interfaces from annotations
	ann := g.getTypeAnnotation(t)
	if ann.Implements != nil {
		interfaces = append(interfaces, ann.Implements...)
	}
	return interfaces
}

// clientPtrType returns *Client pointer type.
func (g *Generator) clientPtrType() jen.Code {
	return jen.Op("*").Id("Client")
}

// graphIDType returns the jen.Code for the graph-level ID type.
func (g *Generator) graphIDType() jen.Code {
	if g.graph.IDType != nil {
		switch g.graph.IDType.Type {
		case field.TypeInt:
			return jen.Int()
		case field.TypeInt64:
			return jen.Int64()
		case field.TypeString:
			return jen.String()
		case field.TypeUUID:
			return jen.Qual("github.com/google/uuid", "UUID")
		default:
			return jen.Int()
		}
	}
	return jen.Int() // Default to int like Ent
}
