package graphql

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	entgen "github.com/syssam/velox/compiler/gen"
	"github.com/syssam/velox/schema/field"
)

func TestGenerator_Generate_Integration(t *testing.T) {
	// Create temp directory
	tmpDir, err := os.MkdirTemp("", "graphql-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	g := mockGraph()
	gen := NewGenerator(g, Config{
		OutDir:          tmpDir,
		Package:         "graphql",
		RelayConnection: true,
		WhereInputs:     true,
		Mutations:       true,
		Ordering:        true,
		RelaySpec:       true,
		SchemaGenerator: true,
		ORMPackage:      "example/ent",
	})

	if genErr := gen.Generate(context.Background()); genErr != nil {
		t.Fatalf("Generate() error = %v", genErr)
	}

	// Check that expected files were created
	// Note: models_gen.go, resolvers.go are generated by gqlgen
	// gqlgen.yml is user-created (not generated)
	// Note: gql_transaction.go is NOT generated - users implement their own transaction middleware
	// Note: gql_node_resolver.go is NOT generated - node resolution is in gql_node.go
	expectedFiles := []string{
		"schema.graphql",
		// Shared files (root package)
		"gql_node.go",
		// gqlfilter/ sub-package
		"gqlfilter/filter.go",
		"gqlfilter/user.go",
		"gqlfilter/post.go",
		// Per-entity files (entity sub-packages)
		"user/gql_node.go",
		"post/gql_node.go",
		"user/gql_collection.go",
		"post/gql_collection.go",
		"query/gql_pagination_user.go",
		"query/gql_pagination_post.go",
		"user/gql_mutation_input.go",
		"post/gql_mutation_input.go",
	}

	for _, file := range expectedFiles {
		path := filepath.Join(tmpDir, file)
		if _, statErr := os.Stat(path); os.IsNotExist(statErr) {
			t.Errorf("expected file %q was not created", file)
		}
	}

	// Verify schema.graphql content
	schemaContent, err := os.ReadFile(filepath.Join(tmpDir, "schema.graphql"))
	if err != nil {
		t.Fatalf("failed to read schema.graphql: %v", err)
	}

	if !strings.Contains(string(schemaContent), "type User") {
		t.Error("schema.graphql should contain User type")
	}
	if !strings.Contains(string(schemaContent), "type Post") {
		t.Error("schema.graphql should contain Post type")
	}

	// Verify gql_node.go content (shared node types)
	nodeContent, err := os.ReadFile(filepath.Join(tmpDir, "gql_node.go"))
	if err != nil {
		t.Fatalf("failed to read gql_node.go: %v", err)
	}
	nodeStr := string(nodeContent)
	if !strings.Contains(nodeStr, "Noder") {
		t.Error("gql_node.go should contain Noder type alias")
	}
	if !strings.Contains(nodeStr, "gqlrelay") {
		t.Error("gql_node.go should reference gqlrelay package")
	}

	// Verify per-entity node files contain Implementors variable
	userNodeContent, err := os.ReadFile(filepath.Join(tmpDir, "user", "gql_node.go"))
	if err != nil {
		t.Fatalf("failed to read user/gql_node.go: %v", err)
	}
	if !strings.Contains(string(userNodeContent), "Implementors") {
		t.Error("user/gql_node.go should contain Implementors variable")
	}
}

// Note: Tests for complexity, dataloaders, error handling removed
// These are handled by gqlgen or external libraries (graph-gophers/dataloader)

func TestGenerator_SystemManagedFieldFiltering(t *testing.T) {
	// Create a graph with system-managed fields
	// Note: Uses opt-in mutations (Annotation with Mutations set)
	mutationAnnotation := map[string]any{
		"graphql": Annotation{
			Mutations:       mutCreate | mutUpdate,
			HasMutationsSet: true,
		},
	}
	g := &entgen.Graph{
		Config: &entgen.Config{
			Package: "example/ent",
		},
		Nodes: []*entgen.Type{
			{
				Name: "Post",
				ID: &entgen.Field{
					Name: "id",
					Type: &field.TypeInfo{Type: field.TypeInt64},
				},
				Fields: []*entgen.Field{
					{Name: "title", Type: &field.TypeInfo{Type: field.TypeString}},
					{Name: "content", Type: &field.TypeInfo{Type: field.TypeString}},
					// System-managed time fields with defaults
					{Name: "created_at", Type: &field.TypeInfo{Type: field.TypeTime}, Default: true},
					{Name: "updated_at", Type: &field.TypeInfo{Type: field.TypeTime}, UpdateDefault: true},
					// Optional field that should be included
					{Name: "published_at", Type: &field.TypeInfo{Type: field.TypeTime}, Optional: true},
				},
				Annotations: mutationAnnotation,
			},
		},
	}

	gen := NewGenerator(g, Config{
		Package:    "graphql",
		ORMPackage: "example/ent",
		Mutations:  true,
	})

	// Generate mutation input Go structs for the Post type
	if len(g.Nodes) == 0 {
		t.Fatal("no nodes in graph")
	}
	f := gen.genEntityMutationInput(g.Nodes[0])
	if f == nil {
		t.Fatal("genEntityMutationInput returned nil")
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		t.Fatalf("failed to render mutation input: %v", err)
	}
	code := buf.String()

	// Test CreatePostInput - should exclude created_at (time with default)
	if strings.Contains(code, "CreatePostInput") {
		// Check that CreatedAt is NOT in the struct
		if strings.Contains(code, "CreatedAt") && strings.Contains(code, "CreatePostInput") {
			// Make sure CreatedAt isn't between CreatePostInput and the next type
			createInputIdx := strings.Index(code, "type CreatePostInput struct")
			updateInputIdx := strings.Index(code, "type UpdatePostInput struct")
			if createInputIdx >= 0 && updateInputIdx > createInputIdx {
				createSection := code[createInputIdx:updateInputIdx]
				if strings.Contains(createSection, "CreatedAt") {
					t.Error("CreatePostInput should NOT contain CreatedAt (system-managed)")
				}
			}
		}

		if !strings.Contains(code, "Title") {
			t.Error("CreatePostInput should contain Title")
		}
		if !strings.Contains(code, "PublishedAt") {
			t.Error("CreatePostInput should contain PublishedAt (optional time, not system-managed)")
		}
	} else {
		t.Error("should generate CreatePostInput struct")
	}

	// Test UpdatePostInput - should exclude updated_at (has UpdateDefault)
	if strings.Contains(code, "UpdatePostInput") {
		updateInputIdx := strings.Index(code, "type UpdatePostInput struct")
		if updateInputIdx >= 0 {
			// Get section from UpdatePostInput to end or next major type
			updateSection := code[updateInputIdx:]
			nextTypeIdx := strings.Index(updateSection[1:], "\ntype ")
			if nextTypeIdx > 0 {
				updateSection = updateSection[:nextTypeIdx+1]
			}

			if strings.Contains(updateSection, "UpdatedAt") {
				t.Error("UpdatePostInput should NOT contain UpdatedAt (has UpdateDefault)")
			}
			if strings.Contains(updateSection, "CreatedAt") {
				t.Error("UpdatePostInput should NOT contain CreatedAt (system-managed)")
			}
		}

		if !strings.Contains(code, "Title") {
			t.Error("UpdatePostInput should contain Title")
		}
	} else {
		t.Error("should generate UpdatePostInput struct")
	}
}

// TestGenerator_MutationInputEdges tests edge handling in mutation inputs.
// This includes:
// - Inverse edges that own FK (M2O) should be included
// - Required unique edges should use non-pointer types
// - Optional unique edges should use pointer types
// - Non-unique edges should use Add/Remove patterns
func TestGenerator_MutationInputEdges(t *testing.T) {
	// Note: Uses opt-in mutations (Annotation with Mutations set)
	mutationAnnotation := map[string]any{
		"graphql": Annotation{
			Mutations:       mutCreate | mutUpdate,
			HasMutationsSet: true,
		},
	}

	// Create a graph with various edge types
	userType := &entgen.Type{
		Name: "User",
		ID: &entgen.Field{
			Name: "id",
			Type: &field.TypeInfo{Type: field.TypeInt64},
		},
		Fields:      []*entgen.Field{},
		Annotations: map[string]any{},
	}

	categoryType := &entgen.Type{
		Name: "Category",
		ID: &entgen.Field{
			Name: "id",
			Type: &field.TypeInfo{Type: field.TypeInt64},
		},
		Fields:      []*entgen.Field{},
		Annotations: map[string]any{},
	}

	tagType := &entgen.Type{
		Name: "Tag",
		ID: &entgen.Field{
			Name: "id",
			Type: &field.TypeInfo{Type: field.TypeInt64},
		},
		Fields:      []*entgen.Field{},
		Annotations: map[string]any{},
	}

	postType := &entgen.Type{
		Name: "Post",
		ID: &entgen.Field{
			Name: "id",
			Type: &field.TypeInfo{Type: field.TypeInt64},
		},
		Fields: []*entgen.Field{
			{Name: "title", Type: &field.TypeInfo{Type: field.TypeString}},
		},
		Annotations: mutationAnnotation,
	}

	// Set up edge relationships
	// 1. User -> Posts (O2M, owner side)
	userType.Edges = []*entgen.Edge{
		{
			Name:   "posts",
			Type:   postType,
			Unique: false,
		},
	}

	// 2. Post -> Author (M2O, inverse side, OwnFK=true)
	// 3. Post -> Category (M2O, optional)
	// 4. Post -> Tags (M2M)
	authorEdge := &entgen.Edge{
		Name:     "author",
		Type:     userType,
		Unique:   true,
		Optional: false, // Required
		Inverse:  "posts",
		Rel: entgen.Relation{
			Type: entgen.M2O,
		},
	}

	categoryEdge := &entgen.Edge{
		Name:     "category",
		Type:     categoryType,
		Unique:   true,
		Optional: true, // Optional
		Inverse:  "posts",
		Rel: entgen.Relation{
			Type: entgen.M2O,
		},
	}

	tagsEdge := &entgen.Edge{
		Name:   "tags",
		Type:   tagType,
		Unique: false,
		Rel: entgen.Relation{
			Type: entgen.M2M,
		},
	}

	postType.Edges = []*entgen.Edge{authorEdge, categoryEdge, tagsEdge}

	g := &entgen.Graph{
		Config: &entgen.Config{
			Package: "example/ent",
		},
		Nodes: []*entgen.Type{userType, postType, categoryType, tagType},
	}

	gen := NewGenerator(g, Config{
		Package:    "graphql",
		ORMPackage: "example/ent",
		Mutations:  true,
	})

	var buf bytes.Buffer
	for _, typ := range g.Nodes {
		f := gen.genEntityMutationInput(typ)
		if f == nil {
			t.Fatalf("genEntityMutationInput(%s) returned nil", typ.Name)
		}
		if err := f.Render(&buf); err != nil {
			t.Fatalf("failed to render mutation input for %s: %v", typ.Name, err)
		}
	}
	code := buf.String()

	// Test CreatePostInput
	t.Run("CreatePostInput", func(t *testing.T) {
		// Extract CreatePostInput struct section
		createIdx := strings.Index(code, "type CreatePostInput struct")
		if createIdx < 0 {
			t.Fatal("CreatePostInput not found")
		}
		nextTypeIdx := strings.Index(code[createIdx+1:], "\ntype ")
		endIdx := createIdx + 1 + nextTypeIdx
		if nextTypeIdx < 0 {
			endIdx = len(code)
		}
		createSection := code[createIdx:endIdx]

		// 1. Should include AuthorID (M2O edge that owns FK)
		if !strings.Contains(createSection, "AuthorID") {
			t.Error("CreatePostInput should contain AuthorID (M2O edge with OwnFK)")
		}

		// 2. AuthorID should be non-pointer (required edge)
		// Look for "AuthorID int64" (non-pointer) not "AuthorID *int64" (pointer)
		if strings.Contains(createSection, "AuthorID *") {
			t.Error("AuthorID should be non-pointer in CreatePostInput (required edge)")
		}
		// Check for AuthorID followed by int64 (with possible whitespace/tabs)
		if !strings.Contains(createSection, "AuthorID") {
			t.Error("CreatePostInput should contain AuthorID")
		}

		// 3. Should include CategoryID (optional M2O edge)
		if !strings.Contains(createSection, "CategoryID") {
			t.Error("CreatePostInput should contain CategoryID (optional M2O edge)")
		}

		// 4. CategoryID should be pointer (optional edge)
		if !strings.Contains(createSection, "CategoryID *int64") {
			t.Error("CategoryID should be *int64 (pointer) in CreatePostInput for optional edge")
		}

		// 5. Should include TagIDs (M2M edge)
		if !strings.Contains(createSection, "TagIDs") {
			t.Error("CreatePostInput should contain TagIDs (M2M edge)")
		}
	})

	t.Run("UpdatePostInput", func(t *testing.T) {
		// Extract UpdatePostInput struct section
		updateIdx := strings.Index(code, "type UpdatePostInput struct")
		if updateIdx < 0 {
			t.Fatal("UpdatePostInput not found")
		}
		nextTypeIdx := strings.Index(code[updateIdx+1:], "\ntype ")
		endIdx := updateIdx + 1 + nextTypeIdx
		if nextTypeIdx < 0 {
			endIdx = len(code)
		}
		updateSection := code[updateIdx:endIdx]

		// 1. Should NOT include ClearAuthor (required edge cannot be cleared)
		if strings.Contains(updateSection, "ClearAuthor") {
			t.Error("UpdatePostInput should NOT contain ClearAuthor (required edge)")
		}

		// 2. Should include ClearCategory (optional edge can be cleared)
		if !strings.Contains(updateSection, "ClearCategory") {
			t.Error("UpdatePostInput should contain ClearCategory")
		}

		// 3. AuthorID should be pointer in update input (all fields optional in updates)
		if !strings.Contains(updateSection, "AuthorID") {
			t.Error("UpdatePostInput should contain AuthorID")
		}
		// Check that AuthorID is followed by a pointer type (*int64)
		// The generated code formats as "AuthorID    *int64" with tabs/spaces
		authorIdx := strings.Index(updateSection, "AuthorID")
		if authorIdx >= 0 {
			// Get the text after "AuthorID" up to the newline
			afterAuthor := updateSection[authorIdx+len("AuthorID"):]
			newlineIdx := strings.Index(afterAuthor, "\n")
			if newlineIdx > 0 {
				afterAuthor = afterAuthor[:newlineIdx]
			}
			if !strings.Contains(afterAuthor, "*") {
				t.Error("AuthorID should be a pointer type in UpdatePostInput")
			}
		}

		// 4. Should include AddTagIDs and RemoveTagIDs for M2M
		if !strings.Contains(updateSection, "AddTagIDs") {
			t.Error("UpdatePostInput should contain AddTagIDs")
		}
		if !strings.Contains(updateSection, "RemoveTagIDs") {
			t.Error("UpdatePostInput should contain RemoveTagIDs")
		}
	})

	t.Run("MutateMethod", func(t *testing.T) {
		// Check that Mutate method is generated for CreatePostInput
		// When generating into entity sub-package, the mutation type is unqualified
		if !strings.Contains(code, "func (i *CreatePostInput) Mutate(m *PostMutation)") {
			t.Error("CreatePostInput should have Mutate method")
		}

		// Check that Mutate method is generated for UpdatePostInput
		if !strings.Contains(code, "func (i *UpdatePostInput) Mutate(m *PostMutation)") {
			t.Error("UpdatePostInput should have Mutate method")
		}
	})
}

// TestGenerator_MutationInputSkipInverseEdges tests that inverse edges without OwnFK are skipped.
func TestGenerator_MutationInputSkipInverseEdges(t *testing.T) {
	// Note: Uses opt-in mutations (Annotation with Mutations set)
	mutationAnnotation := map[string]any{
		"graphql": Annotation{
			Mutations:       mutCreate | mutUpdate,
			HasMutationsSet: true,
		},
	}

	// Create a simple O2M relationship where the FK is NOT on this table
	parentType := &entgen.Type{
		Name: "Parent",
		ID: &entgen.Field{
			Name: "id",
			Type: &field.TypeInfo{Type: field.TypeInt64},
		},
		Fields:      []*entgen.Field{},
		Annotations: mutationAnnotation,
	}

	childType := &entgen.Type{
		Name: "Child",
		ID: &entgen.Field{
			Name: "id",
			Type: &field.TypeInfo{Type: field.TypeInt64},
		},
		Fields:      []*entgen.Field{},
		Annotations: mutationAnnotation,
	}

	// Parent -> Children (O2M, owner side) - should include ChildIDs
	parentType.Edges = []*entgen.Edge{
		{
			Name:   "children",
			Type:   childType,
			Unique: false,
			Rel: entgen.Relation{
				Type: entgen.O2M,
			},
		},
	}

	// Child -> Parent (M2O, inverse side with OwnFK) - should include ParentID
	childType.Edges = []*entgen.Edge{
		{
			Name:    "parent",
			Type:    parentType,
			Unique:  true,
			Inverse: "children",
			Rel: entgen.Relation{
				Type: entgen.M2O,
			},
		},
	}

	g := &entgen.Graph{
		Config: &entgen.Config{
			Package: "example/ent",
		},
		Nodes: []*entgen.Type{parentType, childType},
	}

	gen := NewGenerator(g, Config{
		Package:    "graphql",
		ORMPackage: "example/ent",
		Mutations:  true,
	})

	var buf bytes.Buffer
	for _, typ := range g.Nodes {
		f := gen.genEntityMutationInput(typ)
		if f == nil {
			t.Fatalf("genEntityMutationInput(%s) returned nil", typ.Name)
		}
		if err := f.Render(&buf); err != nil {
			t.Fatalf("failed to render mutation input for %s: %v", typ.Name, err)
		}
	}
	code := buf.String()

	// CreateParentInput should have ChildIDs (O2M owner side)
	createParentIdx := strings.Index(code, "type CreateParentInput struct")
	if createParentIdx < 0 {
		t.Fatal("CreateParentInput not found")
	}
	nextIdx := strings.Index(code[createParentIdx+1:], "\ntype ")
	createParentSection := code[createParentIdx : createParentIdx+1+nextIdx]

	if !strings.Contains(createParentSection, "ChildIDs") {
		t.Error("CreateParentInput should contain ChildIDs (O2M owner side)")
	}

	// CreateChildInput should have ParentID (M2O inverse with OwnFK)
	createChildIdx := strings.Index(code, "type CreateChildInput struct")
	if createChildIdx < 0 {
		t.Fatal("CreateChildInput not found")
	}
	nextIdx = strings.Index(code[createChildIdx+1:], "\ntype ")
	var createChildSection string
	if nextIdx < 0 {
		createChildSection = code[createChildIdx:]
	} else {
		createChildSection = code[createChildIdx : createChildIdx+1+nextIdx]
	}

	if !strings.Contains(createChildSection, "ParentID") {
		t.Error("CreateChildInput should contain ParentID (M2O inverse with OwnFK)")
	}
}

// TestGenerator_MutationInputFieldOrdering tests that fields are ordered correctly.
func TestGenerator_MutationInputFieldOrdering(t *testing.T) {
	// Note: Uses opt-in mutations (Annotation with Mutations set)
	mutationAnnotation := map[string]any{
		"graphql": Annotation{
			Mutations:       mutCreate | mutUpdate,
			HasMutationsSet: true,
		},
	}

	// Create a type with nillable fields to test Clear/Set/Append ordering
	todoType := &entgen.Type{
		Name: "Todo",
		ID: &entgen.Field{
			Name: "id",
			Type: &field.TypeInfo{Type: field.TypeInt64},
		},
		Fields: []*entgen.Field{
			{Name: "title", Type: &field.TypeInfo{Type: field.TypeString}},
			{Name: "description", Type: &field.TypeInfo{Type: field.TypeString}, Optional: true, Nillable: true},
		},
		Annotations: mutationAnnotation,
	}

	g := &entgen.Graph{
		Config: &entgen.Config{
			Package: "example/ent",
		},
		Nodes: []*entgen.Type{todoType},
	}

	gen := NewGenerator(g, Config{
		Package:    "graphql",
		ORMPackage: "example/ent",
		Mutations:  true,
	})

	if len(g.Nodes) == 0 {
		t.Fatal("no nodes in graph")
	}
	f := gen.genEntityMutationInput(g.Nodes[0])
	if f == nil {
		t.Fatal("genEntityMutationInput returned nil")
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		t.Fatalf("failed to render mutation input: %v", err)
	}
	code := buf.String()

	// For UpdateTodoInput, Clear should come before Set
	updateIdx := strings.Index(code, "type UpdateTodoInput struct")
	if updateIdx < 0 {
		t.Fatal("UpdateTodoInput not found")
	}
	nextIdx := strings.Index(code[updateIdx+1:], "\ntype ")
	var updateSection string
	if nextIdx < 0 {
		updateSection = code[updateIdx:]
	} else {
		updateSection = code[updateIdx : updateIdx+1+nextIdx]
	}

	clearIdx := strings.Index(updateSection, "ClearDescription")
	// Look for "Description" followed by pointer marker - could be "Description *" or "Description\t*"
	descIdx := strings.Index(updateSection, "\n\tDescription")
	if descIdx < 0 {
		descIdx = strings.Index(updateSection, "Description ")
	}

	if clearIdx < 0 {
		t.Error("UpdateTodoInput should contain ClearDescription")
	}
	if descIdx < 0 {
		t.Error("UpdateTodoInput should contain Description field")
	}
	if clearIdx >= 0 && descIdx >= 0 && clearIdx >= descIdx {
		t.Error("ClearDescription should come before Description field in UpdateTodoInput")
	}
}
