package graphql

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestSchemaSplitMode_Constants(t *testing.T) {
	var mode SchemaSplitMode
	if mode != SchemaSplitNone {
		t.Errorf("zero value should be SchemaSplitNone, got %d", mode)
	}
	if SchemaSplitNone != 0 {
		t.Errorf("SchemaSplitNone should be 0, got %d", SchemaSplitNone)
	}
	if SchemaSplitByCategory != 1 {
		t.Errorf("SchemaSplitByCategory should be 1, got %d", SchemaSplitByCategory)
	}
	if SchemaSplitPerEntity != 2 {
		t.Errorf("SchemaSplitPerEntity should be 2, got %d", SchemaSplitPerEntity)
	}
}

func TestExtension_WithSchemaSplitMode(t *testing.T) {
	ex, err := NewExtension(
		WithSchemaSplitMode(SchemaSplitPerEntity),
	)
	if err != nil {
		t.Fatalf("NewExtension() error = %v", err)
	}
	if ex.config.SchemaSplitMode != SchemaSplitPerEntity {
		t.Errorf("SchemaSplitMode = %d, want %d", ex.config.SchemaSplitMode, SchemaSplitPerEntity)
	}
}

func TestExtension_WithSplitSchema_BackwardCompat(t *testing.T) {
	ex, err := NewExtension(
		WithSplitSchema(true),
	)
	if err != nil {
		t.Fatalf("NewExtension() error = %v", err)
	}
	if ex.config.SchemaSplitMode != SchemaSplitByCategory {
		t.Errorf("SchemaSplitMode = %d, want SchemaSplitByCategory(%d)", ex.config.SchemaSplitMode, SchemaSplitByCategory)
	}

	ex2, err := NewExtension(
		WithSplitSchema(false),
	)
	if err != nil {
		t.Fatalf("NewExtension() error = %v", err)
	}
	if ex2.config.SchemaSplitMode != SchemaSplitNone {
		t.Errorf("SchemaSplitMode = %d, want SchemaSplitNone(%d)", ex2.config.SchemaSplitMode, SchemaSplitNone)
	}
}

func TestGenerator_GenPerEntityRootSchema(t *testing.T) {
	g := mockGraph()
	gen := NewGenerator(g, Config{
		Package:         "graphql",
		ORMPackage:      "example/ent",
		RelayConnection: true,
		WhereInputs:     true,
		Mutations:       true,
		Ordering:        true,
		RelaySpec:       true,
	})

	schema := gen.genPerEntityRootSchema()

	// Should contain shared types only (no entity types or enums)
	for _, want := range []string{
		"Code generated by velox",
		"directive @goField",
		"directive @goModel",
		"scalar Cursor",
		"scalar Time",
		"interface Node",
		"enum OrderDirection",
		"type PageInfo",
		"type Query",
		"type Mutation",
		"users",
	} {
		if !strings.Contains(schema, want) {
			t.Errorf("should contain %q", want)
		}
	}

	// Should NOT contain entity types, enums, or entity-specific type definitions
	// Note: type references (e.g., ": UserConnection!" in Query) are expected
	for _, notwant := range []string{
		"type User implements",
		"type Post implements",
		"enum UserStatus",
		"input UserWhereInput",
		"input PostWhereInput",
		"input CreateUserInput",
		"input UpdateUserInput",
		"input UserOrder ",
		"enum UserOrderField",
		"type UserConnection",
		"type UserEdge",
	} {
		if strings.Contains(schema, notwant) {
			t.Errorf("should NOT contain type definition %q (belongs in per-entity file)", notwant)
		}
	}
}

func TestGenerator_GenEntitySchemaFile(t *testing.T) {
	g := mockGraph()
	gen := NewGenerator(g, Config{
		Package:         "graphql",
		ORMPackage:      "example/ent",
		RelayConnection: true,
		WhereInputs:     true,
		Mutations:       true,
		Ordering:        true,
		RelaySpec:       true,
	})

	userType := g.Nodes[0] // User
	schema := gen.genEntitySchemaFile(userType)

	// Should contain entity type, enums, WhereInput, OrderBy, Connection/Edge, and mutation inputs
	for _, want := range []string{
		"Code generated by velox",
		"type User",
		"enum UserStatus",
		"UserWhereInput",
		"UserOrder",
		"UserOrderField",
		"UserConnection",
		"UserEdge",
		"CreateUserInput",
		"UpdateUserInput",
	} {
		if !strings.Contains(schema, want) {
			t.Errorf("should contain %q", want)
		}
	}

	// Should NOT contain shared types (those are in root)
	for _, notwant := range []string{
		"type Query",
		"scalar Cursor",
		"enum OrderDirection",
	} {
		if strings.Contains(schema, notwant) {
			t.Errorf("should NOT contain %q", notwant)
		}
	}
}

func TestGenerator_Generate_SplitPerEntity(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "graphql-split-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	g := mockGraph()
	gen := NewGenerator(g, Config{
		OutDir:          tmpDir,
		Package:         "graphql",
		RelayConnection: true,
		WhereInputs:     true,
		Mutations:       true,
		Ordering:        true,
		RelaySpec:       true,
		SchemaGenerator: true,
		SchemaSplitMode: SchemaSplitPerEntity,
		ORMPackage:      "example/ent",
	})

	if genErr := gen.Generate(context.Background()); genErr != nil {
		t.Fatalf("Generate() error = %v", genErr)
	}

	// Root file should exist
	rootPath := filepath.Join(tmpDir, "schema.graphql")
	rootContent, err := os.ReadFile(rootPath)
	if err != nil {
		t.Fatalf("root schema file not created: %v", err)
	}
	rootStr := string(rootContent)

	// Root should contain shared types only (no entity types or enums)
	for _, want := range []string{
		"directive @goField", "scalar Cursor", "interface Node",
		"enum OrderDirection", "type PageInfo", "type Query", "type Mutation",
	} {
		if !strings.Contains(rootStr, want) {
			t.Errorf("root schema should contain %q", want)
		}
	}

	// Root should NOT contain entity types, enums, or entity-specific type definitions
	// Note: type references (e.g., ": UserConnection!" in Query) are expected
	for _, notwant := range []string{
		"type User implements", "type Post implements", "enum UserStatus",
		"input UserWhereInput", "input CreateUserInput", "input UpdateUserInput",
		"input UserOrder ", "enum UserOrderField", "type UserConnection", "type UserEdge",
	} {
		if strings.Contains(rootStr, notwant) {
			t.Errorf("root schema should NOT contain type definition %q (belongs in per-entity file)", notwant)
		}
	}

	// Per-entity files should exist (mockGraph has User and Post only)
	for _, entity := range []string{"user", "post"} {
		entityPath := filepath.Join(tmpDir, fmt.Sprintf("velox_%s.graphql", entity))
		content, readErr := os.ReadFile(entityPath)
		if readErr != nil {
			t.Errorf("entity file velox_%s.graphql not created: %v", entity, readErr)
			continue
		}
		contentStr := string(content)

		if !strings.Contains(contentStr, "Code generated by velox") {
			t.Errorf("velox_%s.graphql should contain generated header", entity)
		}
	}

	// Verify User entity file has WhereInput + mutation inputs
	userContent, err := os.ReadFile(filepath.Join(tmpDir, "velox_user.graphql"))
	if err != nil {
		t.Fatalf("velox_user.graphql not readable: %v", err)
	}
	userStr := string(userContent)

	for _, want := range []string{
		"type User", "enum UserStatus",
		"UserWhereInput", "CreateUserInput", "UpdateUserInput",
		"UserOrder", "UserOrderField", "UserConnection", "UserEdge",
	} {
		if !strings.Contains(userStr, want) {
			t.Errorf("velox_user.graphql should contain %q", want)
		}
	}

	// User file should NOT contain shared types
	for _, notwant := range []string{
		"type Query", "scalar Cursor", "enum OrderDirection",
	} {
		if strings.Contains(userStr, notwant) {
			t.Errorf("velox_user.graphql should NOT contain %q", notwant)
		}
	}

	// Go files should still be generated (shared + per-entity)
	goFiles := []string{
		"gql_node.go",
		// gqlfilter/ sub-package
		"gqlfilter/filter.go",
		"gqlfilter/user.go", "gqlfilter/post.go",
		// Per-entity files (entity sub-packages)
		"user/gql_node.go", "post/gql_node.go",
		"user/gql_collection.go", "post/gql_collection.go",
		"query/gql_pagination_user.go", "query/gql_pagination_post.go",
		"user/gql_mutation_input.go", "post/gql_mutation_input.go",
	}
	for _, goFile := range goFiles {
		if _, statErr := os.Stat(filepath.Join(tmpDir, goFile)); os.IsNotExist(statErr) {
			t.Errorf("expected Go file %q was not created", goFile)
		}
	}
}

func TestGenerator_Generate_SplitPerEntity_SchemaFilenames(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "graphql-hook-test-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	g := mockGraph()
	gen := NewGenerator(g, Config{
		OutDir:          tmpDir,
		Package:         "graphql",
		RelayConnection: true,
		WhereInputs:     true,
		Mutations:       true,
		Ordering:        true,
		RelaySpec:       true,
		SchemaGenerator: true,
		SchemaSplitMode: SchemaSplitPerEntity,
		ORMPackage:      "example/ent",
		SchemaFilename:  "velox.graphql",
	})

	if genErr := gen.Generate(context.Background()); genErr != nil {
		t.Fatalf("Generate() error = %v", genErr)
	}

	// Verify root file uses custom SchemaFilename
	if _, statErr := os.Stat(filepath.Join(tmpDir, "velox.graphql")); os.IsNotExist(statErr) {
		t.Error("root file should use SchemaFilename 'velox.graphql'")
	}

	// Verify entity files exist
	if _, statErr := os.Stat(filepath.Join(tmpDir, "velox_user.graphql")); os.IsNotExist(statErr) {
		t.Error("velox_user.graphql should exist")
	}
	if _, statErr := os.Stat(filepath.Join(tmpDir, "velox_post.graphql")); os.IsNotExist(statErr) {
		t.Error("velox_post.graphql should exist")
	}

	// Verify no unexpected entity files
	if _, statErr := os.Stat(filepath.Join(tmpDir, "velox_comment.graphql")); !os.IsNotExist(statErr) {
		t.Error("velox_comment.graphql should NOT exist (no Comment entity in graph)")
	}
}

func TestGenerator_WriteSchema_SkipsUnchanged(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "graphql-incremental-*")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	g := mockGraph()
	gen := NewGenerator(g, Config{
		OutDir:          tmpDir,
		Package:         "graphql",
		SchemaGenerator: true,
		ORMPackage:      "example/ent",
		RelayConnection: true,
		WhereInputs:     true,
		Mutations:       true,
		Ordering:        true,
		RelaySpec:       true,
	})

	content := "# Test schema\ntype Query { hello: String }\n"

	// First write
	if writeErr := gen.writeSchema(context.Background(), content, "", "test.graphql"); writeErr != nil {
		t.Fatalf("first writeSchema() error = %v", writeErr)
	}

	path := filepath.Join(tmpDir, "test.graphql")
	info1, err := os.Stat(path)
	if err != nil {
		t.Fatalf("file not created: %v", err)
	}
	mtime1 := info1.ModTime()

	// Ensure filesystem can detect time difference
	time.Sleep(50 * time.Millisecond)

	// Second write with same content — should be skipped
	if writeErr := gen.writeSchema(context.Background(), content, "", "test.graphql"); writeErr != nil {
		t.Fatalf("second writeSchema() error = %v", writeErr)
	}

	info2, err := os.Stat(path)
	if err != nil {
		t.Fatalf("file not found after second write: %v", err)
	}
	mtime2 := info2.ModTime()

	if !mtime1.Equal(mtime2) {
		t.Errorf("mtime changed on unchanged content: %v -> %v", mtime1, mtime2)
	}

	// Third write with different content — should update
	newContent := "# Updated schema\ntype Query { world: String }\n"
	if writeErr := gen.writeSchema(context.Background(), newContent, "", "test.graphql"); writeErr != nil {
		t.Fatalf("third writeSchema() error = %v", writeErr)
	}

	written, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read file: %v", err)
	}
	if string(written) != newContent {
		t.Errorf("file content not updated: got %q, want %q", string(written), newContent)
	}
}
