// Package graphql provides GraphQL code generation for Velox schemas.
//
// This package generates GraphQL schema (SDL), Go models, and resolver stubs
// compatible with gqlgen. It follows the patterns established by the Velox GraphQL extension.
//
// # Basic Usage
//
// Most settings are controlled per-entity via schema annotations. The extension
// only needs global settings like the gqlgen.yml path:
//
//	import "github.com/syssam/velox/contrib/graphql"
//
//	ex, err := graphql.NewExtension(
//	    graphql.WithConfigPath("./gqlgen.yml"),  // Enable auto model binding
//	)
//	// OutDir, Package, ORMPackage are auto-inferred from graph.Config
//	err = graphql.Generate(graph, ex.Config())
//
// # Per-Entity Control via Schema Annotations
//
// Features like RelayConnection, Mutations, Ordering are enabled by default
// and can be controlled per-entity using schema annotations:
//
//	func (User) Annotations() []velox.Annotation {
//	    return []velox.Annotation{
//	        graphql.RelayConnection(),              // Enable Relay connections
//	        graphql.Mutations(                      // Control mutations
//	            graphql.MutationCreate(),
//	            graphql.MutationUpdate(),
//	        ),
//	        graphql.Skip(graphql.SkipWhereInput),   // Skip WhereInput generation
//	    }
//	}
//
// # Direct Config Usage
//
// For direct config usage without the extension:
//
//	err := graphql.Generate(graph, graphql.Config{
//	    OutDir:     "./velox",
//	    ORMPackage: "myapp/velox",
//	    // All features enabled by default
//	})
//
// Generated output structure (following entgql patterns):
//
//	{output}/
//	├── schema.graphql           # GraphQL SDL schema (root)
//	├── velox_{entity}.graphql   # (if SchemaSplitPerEntity) Entity type, enums, WhereInput, OrderBy, Connection/Edge, mutations
//	├── schema/                  # (if SchemaSplitByCategory)
//	│   ├── types.graphql           # Entity types
//	│   ├── inputs.graphql          # Input types (WhereInput, OrderBy, mutations)
//	│   ├── connections.graphql     # Relay connection types
//	│   └── scalars.graphql         # Custom scalars
//	├── gql_node.go              # Relay Node interface implementation
//	├── gql_collection.go        # Field collection for eager loading
//	├── gql_pagination.go        # Relay cursor pagination
//	├── gql_scalars.go           # Scalar marshalers for typed JSON fields
//	├── filter/                  # WhereInput to predicate converters (per-entity)
//	├── gql_pagination.go        # Pagination types (Connection, Edge, Order)
//	└── {entity}/                # Per-entity sub-packages
//	    ├── gql_node.go              # Node implementors
//	    ├── gql_collection.go        # CollectFields
//	    ├── gql_pagination.go        # Paginate, pager, paginate args
//	    └── gql_mutation_input.go    # Mutation input structs + SetInput
//
// Note: The following are handled by gqlgen or external libraries:
//   - gqlgen.yml: User creates their own gqlgen config
//   - models_gen.go, resolvers.go: generated by gqlgen
//   - Enum marshalers: gqlgen handles with model binding
//   - Complexity calculation: gqlgen has built-in support
//   - DataLoaders: use graph-gophers/dataloader
//   - Error handling: use gqlgen's gqlerror package
package graphql

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/sync/errgroup"

	"github.com/syssam/velox/compiler/gen"
)

// SchemaSplitMode controls how GraphQL schema files are split.
type SchemaSplitMode int

const (
	// SchemaSplitNone generates a single schema file (default).
	SchemaSplitNone SchemaSplitMode = iota

	// SchemaSplitByCategory splits into types.graphql, inputs.graphql,
	// connections.graphql, scalars.graphql (existing behavior).
	SchemaSplitByCategory

	// SchemaSplitPerEntity generates one file per entity plus a shared root file.
	// Each entity file contains its type, enums, inputs, and connections.
	SchemaSplitPerEntity
)

// Config holds GraphQL generation configuration.
//
// Most options are global defaults that can be overridden per-entity using
// schema annotations (graphql.RelayConnection, graphql.Mutations, etc.).
type Config struct {
	// OutDir is the output directory for generated Go files (gql_*.go).
	// Auto-inferred from graph.Config.Target if not set.
	OutDir string

	// SchemaOutDir is the output directory for GraphQL schema files (.graphql).
	// If not set, defaults to OutDir.
	SchemaOutDir string

	// SchemaFilename is the name of the generated schema file.
	// Default: "schema.graphql". Set via WithSchemaPath().
	SchemaFilename string

	// Package is the Go package name for generated code.
	// Auto-inferred from graph.Config.Package if not set.
	Package string

	// ORMPackage is the import path of the generated ORM package.
	// Auto-inferred from graph.Config.Package if not set.
	ORMPackage string

	// SchemaSplitMode controls how schema files are organized.
	// Default zero value (SchemaSplitNone) produces a single file.
	SchemaSplitMode SchemaSplitMode

	// --- Global defaults (typically controlled per-entity via annotations) ---

	// RelayConnection enables Relay-style cursor connections globally.
	// Default: true. Per-entity: graphql.RelayConnection() annotation.
	RelayConnection bool

	// WhereInputs enables WhereInput filter generation globally.
	// Default: true. Per-entity: graphql.Skip(graphql.SkipWhereInput).
	WhereInputs bool

	// Mutations enables mutation generation globally.
	// Default: true. Per-entity: graphql.Mutations() annotation.
	Mutations bool

	// Ordering enables OrderBy enum generation globally.
	// Default: true. Per-entity: graphql.Skip(graphql.SkipOrderField).
	Ordering bool

	// RelaySpec enables Relay specification support (Node interface, connections, etc.).
	// Default: true. Per-entity: graphql.Skip(graphql.SkipType).
	RelaySpec bool

	// --- Advanced options ---

	// MapScalarFunc is an optional function that maps a field to a custom GraphQL scalar.
	// If the function returns an empty string, the default scalar mapping is used.
	// This follows Ent's entgql.WithMapScalarFunc pattern.
	MapScalarFunc func(*gen.Type, *gen.Field) string

	// NullableInputOmittable makes all nullable/optional input fields use
	// graphql.Omittable[*T] for PATCH-style three-state handling.
	// Auto-detected from gqlgen.yml nullable_input_omittable setting.
	NullableInputOmittable bool

	// NodeDescriptor enables NodeDescriptor generation for admin-tool introspection.
	// When enabled, each entity gets a Node(ctx) method that returns a structured
	// NodeDescriptor with fields and edges serialized as JSON values.
	// Equivalent to Ent's WithNodeDescriptor() option.
	// Default: false. Use WithNodeDescriptor() to enable.
	NodeDescriptor bool

	// MaxFilterDepth sets the maximum nesting depth for WhereInput filters.
	// Limits recursive and/or/not and HasXxxWith predicate depth.
	// Default: 0 (uses DefaultMaxFilterDepth = 5). Use WithMaxFilterDepth() to override.
	MaxFilterDepth int

	// Federation enables Apollo Federation v2 schema directives.
	// When true, the schema includes the @link directive and federation entities
	// are annotated with @key. Auto-detected if any entity has @key directives.
	Federation bool

	// SchemaGenerator enables GraphQL schema file generation (.graphql files).
	// When false, only Go files are generated.
	// Default: false. Use WithSchemaGenerator() to enable.
	SchemaGenerator bool

	// schemaHooks are hooks applied to the typed *ast.Schema after generation.
	// Set internally by the Extension; not part of the public API.
	schemaHooks []SchemaHook

	// outputWriter is an optional custom writer for the *ast.Schema.
	// When set, the schema is passed to this function instead of being
	// written to a file. Set via WithOutputWriter().
	outputWriter SchemaOutputWriter

	// graph is the generation graph, passed to schema hooks.
	// Set internally by the Extension; not part of the public API.
	graph *gen.Graph
}

// enumSource records where a GraphQL enum name originates from.
type enumSource struct {
	typeName  string   // entity name (e.g., "Asset")
	fieldName string   // field name (e.g., "depreciation_method")
	values    []string // sorted enum values (e.g., ["ACTIVE", "INACTIVE"])
}

// Generator generates GraphQL schema and code from Velox schemas.
type Generator struct {
	graph   *gen.Graph
	config  Config
	workers int

	// samePackage is true when generating into the same package as the ORM
	// In this case, we use unqualified type references instead of imports
	samePackage bool

	// enumNames caches all generated enum type names for O(1) lookup in isValidInputType.
	// Built once at construction time to avoid O(N*F) iteration per call.
	enumNames map[string]bool

	// sharedEnums tracks enum names that are shared across multiple entities
	// because they collide but have identical values. The value is the first
	// entity's type that should emit the definition.
	sharedEnums map[string]string

	// enumSources tracks all sources for each enum name, used by validateEnumNames
	// to detect conflicting definitions. Built by buildEnumNamesCache.
	enumSources map[string][]enumSource

	// typedJSONScalars caches the result of collectTypedJSONScalars to avoid
	// redundant iteration when called from multiple generation paths.
	typedJSONScalars map[string]typedJSONScalar
}

// NewGenerator creates a new GraphQL generator.
func NewGenerator(g *gen.Graph, cfg Config) *Generator {
	// Auto-infer from graph.Config if not set
	if g.Config != nil {
		if cfg.OutDir == "" {
			cfg.OutDir = g.Target
		}
		if cfg.ORMPackage == "" {
			cfg.ORMPackage = g.Package
		}
		if cfg.Package == "" {
			// Extract package name from path (e.g., "myapp/velox" -> "velox")
			parts := strings.Split(g.Package, "/")
			cfg.Package = parts[len(parts)-1]
		}
	}
	if cfg.Package == "" {
		cfg.Package = "graphql"
	}

	// Detect if we're generating into the same package as the ORM.
	// When true, type references are unqualified (e.g., Client instead of velox.Client).
	samePackage := false
	if cfg.ORMPackage != "" {
		if strings.Contains(cfg.Package, "/") {
			// Full import path comparison — unambiguous.
			samePackage = cfg.Package == cfg.ORMPackage
		} else {
			// Short package name: same-package only when OutDir matches the ORM
			// target (or is empty, meaning auto-inferred from graph). Avoids false
			// positives when different packages share the same base name
			// (e.g., foo/velox vs bar/velox).
			samePackage = cfg.OutDir == "" || (g != nil && cfg.OutDir == g.Target)
		}
	}

	gqlGen := &Generator{
		graph:       g,
		config:      cfg,
		workers:     min(runtime.GOMAXPROCS(0), 16),
		samePackage: samePackage,
	}
	gqlGen.buildEnumNamesCache()
	gqlGen.typedJSONScalars = gqlGen.collectTypedJSONScalars()
	return gqlGen
}

// buildEnumNamesCache pre-builds a set of all generated enum type names
// for O(1) lookup in isValidInputType, and detects cross-entity enum name
// collisions. When two entities produce the same enum name with identical
// values, the enum is marked as shared (emitted once). When values differ,
// an error is recorded and surfaced by validateEnumNames.
func (g *Generator) buildEnumNamesCache() {
	g.enumNames = make(map[string]bool)
	g.sharedEnums = make(map[string]string)
	g.enumSources = make(map[string][]enumSource)

	for _, node := range g.graph.Nodes {
		for _, f := range node.Fields {
			if !f.IsEnum() {
				continue
			}
			enumName := node.Name + pascal(f.Name)
			ann := extractGraphQLAnnotation(f.Annotations)
			if customName := ann.GetType(); customName != "" {
				enumName = customName
			}
			g.enumNames[enumName] = true

			values := make([]string, len(f.EnumValues()))
			copy(values, f.EnumValues())
			slices.Sort(values)
			g.enumSources[enumName] = append(g.enumSources[enumName], enumSource{
				typeName:  node.Name,
				fieldName: f.Name,
				values:    values,
			})
		}
	}

	// Mark shared enums (same name, same values, multiple sources).
	for name, srcs := range g.enumSources {
		if len(srcs) > 1 {
			g.sharedEnums[name] = srcs[0].typeName
		}
	}
}

// validateEnumNames checks for enum name collisions across entities.
// Collisions where all sources have identical values are allowed (shared enum).
// Collisions with differing values return an error.
// Uses the sources already computed by buildEnumNamesCache.
func (g *Generator) validateEnumNames() error {
	for name, srcs := range g.enumSources {
		if len(srcs) <= 1 {
			continue
		}
		// Check if all sources have the same values.
		base := srcs[0].values
		for _, src := range srcs[1:] {
			if !slices.Equal(base, src.values) {
				// Build a descriptive error message.
				var parts []string
				for _, s := range srcs {
					parts = append(parts, fmt.Sprintf("%s.%s (values: %v)", s.typeName, s.fieldName, s.values))
				}
				return fmt.Errorf(
					"graphql: enum name %q is generated by multiple fields with different values: %s; "+
						"add graphql.Type(\"UniqueEnumName\") annotation to disambiguate",
					name, strings.Join(parts, " and "),
				)
			}
		}
	}
	return nil
}

// getTypedJSONScalarsCache returns the cached typed JSON scalars.
func (g *Generator) getTypedJSONScalarsCache() map[string]typedJSONScalar {
	return g.typedJSONScalars
}

// useGenericPredicates returns true if generic predicates should be used.
// By default, generic predicates are enabled (user.Where.Email.EQ(v)).
// Returns false only if FeatureEntPredicates is enabled (user.EmailEQ(v)).
func (g *Generator) useGenericPredicates() bool {
	if g.graph.Config == nil {
		return true // Default to generic predicates
	}
	entPredicates, err := g.graph.FeatureEnabled("sql/entpredicates")
	if err != nil {
		return true // Default to generic predicates
	}
	return !entPredicates // Use generic unless Ent predicates are enabled
}

// hasBytesField returns true if any entity type in the graph has a Bytes field.
func (g *Generator) hasBytesField() bool {
	for _, t := range g.graph.Nodes {
		for _, f := range t.Fields {
			if f.IsBytes() {
				return true
			}
		}
	}
	return false
}

// runtimePkgPath is the import path for the velox runtime package.
const runtimePkgPath = "github.com/syssam/velox/runtime"

// entityPkgName returns the sub-package name for an entity type (lowercase).
func (g *Generator) entityPkgName(t *gen.Type) string {
	return strings.ToLower(t.Name)
}

// entityPkgPath returns the full import path for an entity's sub-package.
func (g *Generator) entityPkgPath(t *gen.Type) string {
	return g.config.ORMPackage + "/" + strings.ToLower(t.Name)
}

// Generate generates all GraphQL artifacts.
func (g *Generator) Generate(ctx context.Context) error {
	// Validate WhereInput annotations before generation
	if g.config.WhereInputs {
		if err := g.validateWhereInputAnnotations(); err != nil {
			return err
		}
	}

	// Validate resolver mappings before generation
	for _, t := range g.filterNodes(g.graph.Nodes, SkipType) {
		if err := g.validateResolverMappings(t); err != nil {
			return err
		}
	}

	// Validate enum name collisions across entities
	if err := g.validateEnumNames(); err != nil {
		return err
	}

	if err := os.MkdirAll(g.config.OutDir, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	errg, ctx := errgroup.WithContext(ctx)
	errg.SetLimit(g.workers)

	// Generate GraphQL SDL schema (only if SchemaGenerator is enabled)
	if g.config.SchemaGenerator {
		schemaFilename := g.config.SchemaFilename
		if schemaFilename == "" {
			schemaFilename = "schema.graphql"
		}
		switch g.config.SchemaSplitMode {
		case SchemaSplitByCategory:
			errg.Go(func() error { return g.writeSchema(ctx, g.genTypesSchema(), "schema", "types.graphql") })
			errg.Go(func() error { return g.writeSchema(ctx, g.genInputsSchema(), "schema", "inputs.graphql") })
			errg.Go(func() error {
				return g.writeSchema(ctx, g.genConnectionsSchema(), "schema", "connections.graphql")
			})
			errg.Go(func() error { return g.writeSchema(ctx, g.genScalarsSchema(), "schema", "scalars.graphql") })
			errg.Go(func() error { return g.writeSchema(ctx, g.genRootSchema(), "", schemaFilename) })
		case SchemaSplitPerEntity:
			rootSchema := g.genPerEntityRootSchema()
			errg.Go(func() error { return g.writeSchema(ctx, rootSchema, "", schemaFilename) })
			// Per-entity files contain entity type, enums, WhereInput, OrderBy, Connection/Edge, mutation inputs
			// Every non-skipped entity gets a per-entity file (at minimum contains the type definition)
			nodes := g.filterNodes(g.graph.Nodes, SkipType)
			for _, t := range nodes {
				errg.Go(func() error {
					filename := fmt.Sprintf("velox_%s.graphql", strings.ToLower(t.Name))
					return g.writeSchema(ctx, g.genEntitySchemaFile(t), "", filename)
				})
			}
		default: // SchemaSplitNone
			errg.Go(func() error { return g.writeSchema(ctx, g.genFullSchema(), "", schemaFilename) })
		}
	}

	// Note: models_gen.go and resolvers.go are generated by gqlgen, not here

	// Generate WhereInput Go structs with P() and Filter() methods (like entgql's gql_where_input.go)
	// This generates the Go structs; the SDL is generated in the schema.
	// WhereInput types go to filter/ sub-package to avoid circular imports.
	if g.config.WhereInputs && g.config.ORMPackage != "" {
		// Shared WhereInput constants (ErrFilterDepthExceeded, DefaultMaxFilterDepth)
		if f := g.genWhereInputShared(); f != nil {
			errg.Go(func() error { return g.writeFileSubdir(ctx, f, "filter", "filter.go") })
		}
		// Per-entity WhereInput files → filter/ sub-package
		for _, t := range g.filterNodes(g.graph.Nodes, SkipType|SkipWhereInput) {
			if !g.hasFilterableContent(t) {
				continue
			}
			errg.Go(func() error {
				if f := g.genEntityWhereInputFile(t); f != nil {
					return g.writeFileSubdir(ctx, f, "filter",
						fmt.Sprintf("%s.go", strings.ToLower(t.Name)))
				}
				return nil
			})
		}
	}

	// Generate Relay Node implementation (like entgql's gql_node.go)
	// Node descriptor (Node, Field, Edge structs) is included in gql_node.go like Ent
	if g.config.RelaySpec {
		// Shared node code (Noder interface, Client methods, registry-based dispatch)
		errg.Go(func() error { return g.writeFile(ctx, g.genNodeShared(), "gql_node.go") })
		// Per-entity node code (implementors) → entity sub-package
		for _, t := range g.filterNodes(g.graph.Nodes, SkipType) {
			errg.Go(func() error {
				return g.writeFileSubdir(ctx, g.genEntityNode(t), g.entityPkgName(t), "gql_node.go")
			})
		}
	}

	// Generate field collection utilities (like entgql's gql_collection.go)
	if g.config.ORMPackage != "" {
		// Per-entity collection metadata → entity sub-packages
		for _, t := range g.filterNodes(g.graph.Nodes, SkipType) {
			errg.Go(func() error {
				if f := g.genEntityCollection(t); f != nil {
					return g.writeFileSubdir(ctx, f, g.entityPkgName(t), "gql_collection.go")
				}
				return nil
			})
		}
		// All CollectFields methods → single query/gql_collection.go
		errg.Go(func() error {
			collectionNodes := g.filterNodes(g.graph.Nodes, SkipType)
			if f := g.genCollectionQueries(collectionNodes); f != nil {
				return g.writeFileSubdir(ctx, f, "query", "gql_collection.go")
			}
			return nil
		})

		// Note: Edge resolvers are handled by gqlgen's forceResolver pattern in entity-pkg-mode.
		// Entity types live in sub-packages, so methods cannot be defined on them from root.

		// Generate pagination utilities (Relay cursor connections)
		if g.config.RelayConnection {
			// Shared pagination code (OrderDirection, Cursor, PageInfo, helpers) → entity/
			if f := g.genPaginationShared(); f != nil {
				errg.Go(func() error { return g.writeFileSubdir(ctx, f, "entity", "gql_pagination_shared.go") })
			}
			// Per-entity Paginate methods → query/ package
			for _, t := range g.filterNodes(g.graph.Nodes, SkipType) {
				if !g.hasRelayConnection(t) {
					continue
				}
				errg.Go(func() error {
					if f := g.genEntityPagination(t); f != nil {
						return g.writeFileSubdir(ctx, f, "query", "gql_pagination_"+toSnakeCase(t.Name)+".go")
					}
					return nil
				})
			}

			// Pagination types (Connection, Edge, Order) → entity/gql_pagination.go
			relayNodes := make([]*gen.Type, 0)
			for _, t := range g.filterNodes(g.graph.Nodes, SkipType) {
				if g.hasRelayConnection(t) {
					relayNodes = append(relayNodes, t)
				}
			}
			if len(relayNodes) > 0 {
				errg.Go(func() error {
					if f := g.genModelPaginationTypes(relayNodes); f != nil {
						return g.writeFileSubdir(ctx, f, "entity", "gql_pagination.go")
					}
					return nil
				})
				// Root re-exports WithXxxOrder/WithXxxFilter for resolver convenience.
				// Type aliases removed — @goModel points directly to entity/.
				errg.Go(func() error {
					if f := g.genRootPaginationHelpers(relayNodes); f != nil {
						return g.writeFileSubdir(ctx, f, "", "gql_pagination.go")
					}
					return nil
				})
			}
		}

		// Per-entity edge resolver methods → entity/gql_edge_{entity}.go
		for _, t := range g.filterNodes(g.graph.Nodes, SkipType) {
			errg.Go(func() error {
				if f := g.genEntityEdge(t); f != nil {
					return g.writeFileSubdir(ctx, f, "entity", "gql_edge_"+toSnakeCase(t.Name)+".go")
				}
				return nil
			})
		}

		// Generate mutation input structs (struct + Mutate + SetInput) → entity sub-package.
		// Mutation inputs reference entity mutation types (UserMutation) which are local.
		// Root re-exports via type aliases generated below.
		if g.config.Mutations {
			for _, t := range g.filterNodes(g.graph.Nodes, SkipType) {
				if !g.wantsMutationCreate(t) && !g.wantsMutationUpdate(t) {
					continue
				}
				errg.Go(func() error {
					if f := g.genEntityMutationInput(t); f != nil {
						return g.writeFileSubdir(ctx, f, g.entityPkgName(t), "gql_mutation_input.go")
					}
					return nil
				})
			}
			// Note: No root mutation input aliases — @goModel points directly to entity sub-packages.
			// This avoids pulling all entity types into root package (build memory).
		}

		// Note: Enum MarshalGQL/UnmarshalGQL is generated by ORM generator into entity files
		// (like Ent's enum.tmpl which embeds into entity files, not a separate gql_enum.go)

		// Note: Transaction utilities (txCtxKey, TxFromContext, NewTxContext) are already
		// generated by the ORM generator in velox.go, so we don't generate gql_transaction.go
	}

	// Generate scalar marshalers for typed JSON fields defined in the schema
	// This generates Marshal/Unmarshal functions so gqlgen can auto-handle these types
	// Note: For third-party types like decimal.Decimal, users should define their own scalars
	if g.config.ORMPackage != "" && len(g.getTypedJSONScalarsCache()) > 0 {
		errg.Go(func() error { return g.writeFile(ctx, g.genScalars(), "gql_scalars.go") })
	}

	// Note: The following are handled by gqlgen or external libraries:
	// - gqlgen.yml: User creates their own gqlgen config
	// - Complexity: gqlgen has built-in complexity support
	// - DataLoaders: Use graph-gophers/dataloader or similar
	// - Error handling: Use gqlgen's gqlerror package

	return errg.Wait()
}

// Generate is a convenience function to generate GraphQL code.
func Generate(g *gen.Graph, cfg Config) error {
	gqlGen := NewGenerator(g, cfg)
	return gqlGen.Generate(context.Background())
}

// Schema generation methods are in schema_sdl.go, schema_types.go,
// schema_input.go, schema_connection.go, and schema_query.go.

// Type definitions (typedJSONScalar, enums, entity types, scalars, fields) are in schema_types.go.

// =============================================================================
// File writing
// =============================================================================

func (g *Generator) writeSchema(ctx context.Context, content, subdir, filename string) error {
	if err := ctx.Err(); err != nil {
		return err
	}

	// Apply schema hooks via typed AST.
	// Hooks apply to ALL schema files (root + per-entity) so users can add
	// directives to entity-specific types in SchemaSplitPerEntity mode.
	if len(g.config.schemaHooks) > 0 {
		schema, err := parseSchemaSDL(content)
		if err != nil {
			return fmt.Errorf("parse schema for hooks: %w", err)
		}
		if err := g.applySchemaHooks(schema); err != nil {
			return err
		}
		// OutputWriter only fires for the root file (complete schema, not fragments).
		if g.config.outputWriter != nil && subdir == "" {
			return g.config.outputWriter(schema)
		}
		content = printSchema(schema)
	} else if g.config.outputWriter != nil && subdir == "" {
		// No hooks but output writer is set — parse and delegate.
		schema, err := parseSchemaSDL(content)
		if err != nil {
			return fmt.Errorf("parse schema for output writer: %w", err)
		}
		return g.config.outputWriter(schema)
	}

	// Use SchemaOutDir for schema files, fallback to OutDir
	baseDir := g.config.SchemaOutDir
	if baseDir == "" {
		baseDir = g.config.OutDir
	}
	dir := baseDir
	if subdir != "" {
		dir = filepath.Join(baseDir, subdir)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(dir, filename)
	// Skip write if content unchanged — preserves mtime for gqlgen incremental builds
	existing, err := os.ReadFile(path)
	if err == nil && string(existing) == content {
		return nil
	}
	return atomicWriteFile(path, []byte(content), 0o644)
}

func (g *Generator) writeFile(ctx context.Context, f *jen.File, filename string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	path := filepath.Join(g.config.OutDir, filename)
	formatted, err := gen.FormatJenFile(f, path)
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	// Skip write if content unchanged — preserves mtime for incremental builds
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, formatted) {
		return nil
	}
	return atomicWriteFile(path, formatted, 0o644)
}

// writeFileSubdir writes a Jennifer file to a sub-directory under OutDir.
// Creates the sub-directory if it doesn't exist.
func (g *Generator) writeFileSubdir(ctx context.Context, f *jen.File, subdir, filename string) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	dir := filepath.Join(g.config.OutDir, subdir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create subdirectory %s: %w", subdir, err)
	}
	path := filepath.Join(dir, filename)
	formatted, err := gen.FormatJenFile(f, path)
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, formatted) {
		return nil
	}
	return atomicWriteFile(path, formatted, 0o644)
}

// atomicWriteFile writes data to a temp file then renames it to path.
// This prevents partial/corrupt files if the process crashes mid-write.
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".velox-gen-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		// Clean up temp file on error.
		if err != nil {
			os.Remove(tmpName)
		}
	}()
	if _, err = tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err = tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	if err = os.Chmod(tmpName, perm); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

// Helper methods, annotation extraction, string utilities, and ORM type helpers
// are in schema_helpers.go.
// Input SDL generation is in schema_input.go.
// Connection SDL generation is in schema_connection.go.
// Query/Mutation SDL generation is in schema_query.go.
