// Package graphql provides GraphQL code generation for Velox schemas.
package graphql

import (
	"github.com/dave/jennifer/jen"
)

// genScalars generates the gql_scalars.go file with MarshalGQL/UnmarshalGQL
// functions for typed JSON fields defined in the schema.
// This allows gqlgen to automatically handle these types without custom resolvers.
//
// Note: For third-party types like decimal.Decimal, users should define their own
// scalar and marshal/unmarshal functions, then configure gqlgen.yml accordingly.
func (g *Generator) genScalars() *jen.File {
	f := jen.NewFile(g.config.Package)
	f.HeaderComment("Code generated by velox. DO NOT EDIT.")

	// Generate marshalers for typed JSON scalars
	typedScalars := g.collectTypedJSONScalars()
	for _, scalar := range typedScalars {
		g.genTypedJSONMarshalers(f, scalar)
	}

	return f
}

// genTypedJSONMarshalers generates type alias and marshalers for a typed JSON scalar.
func (g *Generator) genTypedJSONMarshalers(f *jen.File, scalar typedJSONScalar) {
	// Use the original package path for the type alias
	pkgPath := scalar.OrigPkgPath
	typeName := scalar.TypeName

	// Generate type alias
	f.Comment(scalar.ScalarName + " is a type alias for " + scalar.GoType + ".")
	f.Comment("This allows gqlgen to use the Marshal" + scalar.ScalarName + "/Unmarshal" + scalar.ScalarName + " functions from this package.")
	f.Type().Id(scalar.ScalarName).Op("=").Qual(pkgPath, typeName)
	f.Line()

	// Generate Marshal function
	f.Comment("Marshal" + scalar.ScalarName + " implements graphql.Marshaler for " + scalar.GoType + ".")
	f.Func().Id("Marshal"+scalar.ScalarName).Params(
		jen.Id("v").Qual(pkgPath, typeName),
	).Qual("github.com/99designs/gqlgen/graphql", "Marshaler").Block(
		jen.Return(
			jen.Qual("github.com/99designs/gqlgen/graphql", "WriterFunc").Call(
				jen.Func().Params(jen.Id("w").Qual("io", "Writer")).Block(
					jen.List(jen.Id("data"), jen.Id("_")).Op(":=").Qual("encoding/json", "Marshal").Call(jen.Id("v")),
					jen.Id("w").Dot("Write").Call(jen.Id("data")),
				),
			),
		),
	)
	f.Line()

	// Generate Unmarshal function
	f.Comment("Unmarshal" + scalar.ScalarName + " implements graphql.Unmarshaler for " + scalar.GoType + ".")
	f.Func().Id("Unmarshal"+scalar.ScalarName).Params(
		jen.Id("v").Any(),
	).Params(
		jen.Qual(pkgPath, typeName),
		jen.Error(),
	).Block(
		jen.Var().Id("result").Qual(pkgPath, typeName),
		jen.Switch(jen.Id("val").Op(":=").Id("v").Assert(jen.Id("type"))).Block(
			jen.Case(jen.String()).Block(
				jen.If(
					jen.Id("err").Op(":=").Qual("encoding/json", "Unmarshal").Call(
						jen.Index().Byte().Call(jen.Id("val")),
						jen.Op("&").Id("result"),
					),
					jen.Id("err").Op("!=").Nil(),
				).Block(
					jen.Return(jen.Id("result"), jen.Id("err")),
				),
				jen.Return(jen.Id("result"), jen.Nil()),
			),
			jen.Case(jen.Index().Byte()).Block(
				jen.If(
					jen.Id("err").Op(":=").Qual("encoding/json", "Unmarshal").Call(
						jen.Id("val"),
						jen.Op("&").Id("result"),
					),
					jen.Id("err").Op("!=").Nil(),
				).Block(
					jen.Return(jen.Id("result"), jen.Id("err")),
				),
				jen.Return(jen.Id("result"), jen.Nil()),
			),
			jen.Case(jen.Map(jen.String()).Any()).Block(
				// Re-marshal and unmarshal to convert from map to struct
				jen.List(jen.Id("data"), jen.Id("err")).Op(":=").Qual("encoding/json", "Marshal").Call(jen.Id("val")),
				jen.If(jen.Id("err").Op("!=").Nil()).Block(
					jen.Return(jen.Id("result"), jen.Id("err")),
				),
				jen.If(
					jen.Id("err").Op(":=").Qual("encoding/json", "Unmarshal").Call(
						jen.Id("data"),
						jen.Op("&").Id("result"),
					),
					jen.Id("err").Op("!=").Nil(),
				).Block(
					jen.Return(jen.Id("result"), jen.Id("err")),
				),
				jen.Return(jen.Id("result"), jen.Nil()),
			),
			jen.Default().Block(
				jen.Return(
					jen.Id("result"),
					jen.Qual("fmt", "Errorf").Call(
						jen.Lit("cannot unmarshal %T to "+scalar.GoType),
						jen.Id("v"),
					),
				),
			),
		),
	)
	f.Line()

	// Generate MarshalPtr function
	f.Comment("Marshal" + scalar.ScalarName + "Ptr implements graphql.Marshaler for *" + scalar.GoType + ".")
	f.Func().Id("Marshal"+scalar.ScalarName+"Ptr").Params(
		jen.Id("v").Op("*").Qual(pkgPath, typeName),
	).Qual("github.com/99designs/gqlgen/graphql", "Marshaler").Block(
		jen.If(jen.Id("v").Op("==").Nil()).Block(
			jen.Return(jen.Qual("github.com/99designs/gqlgen/graphql", "Null")),
		),
		jen.Return(jen.Id("Marshal"+scalar.ScalarName).Call(jen.Op("*").Id("v"))),
	)
	f.Line()

	// Generate UnmarshalPtr function
	f.Comment("Unmarshal" + scalar.ScalarName + "Ptr implements graphql.Unmarshaler for *" + scalar.GoType + ".")
	f.Func().Id("Unmarshal"+scalar.ScalarName+"Ptr").Params(
		jen.Id("v").Any(),
	).Params(
		jen.Op("*").Qual(pkgPath, typeName),
		jen.Error(),
	).Block(
		jen.If(jen.Id("v").Op("==").Nil()).Block(
			jen.Return(jen.Nil(), jen.Nil()),
		),
		jen.List(jen.Id("result"), jen.Id("err")).Op(":=").Id("Unmarshal"+scalar.ScalarName).Call(jen.Id("v")),
		jen.If(jen.Id("err").Op("!=").Nil()).Block(
			jen.Return(jen.Nil(), jen.Id("err")),
		),
		jen.Return(jen.Op("&").Id("result"), jen.Nil()),
	)
	f.Line()
}
