package graphql

import (
	"bytes"
	"fmt"

	"github.com/syssam/velox/compiler/gen"
)

// genFullSchema generates the complete GraphQL schema as a single file.
func (g *Generator) genFullSchema() string {
	var buf bytes.Buffer

	// Write header
	buf.WriteString("# Code generated by velox. DO NOT EDIT.\n\n")

	// Federation v2 @link directive (before any type definitions)
	if g.hasFederationEntities() {
		buf.WriteString(federationLinkDirective())
		buf.WriteString("\n\n")
	}

	// Scalars
	buf.WriteString(g.genScalarsSchema())
	buf.WriteString("\n")

	// Node interface (Relay)
	if g.config.RelaySpec {
		buf.WriteString(g.genNodeInterface())
		buf.WriteString("\n")
	}

	// Entity types
	buf.WriteString(g.genTypesSchema())
	buf.WriteString("\n")

	// Input types
	if g.config.WhereInputs || g.config.Mutations || g.config.Ordering {
		buf.WriteString(g.genInputsSchema())
		buf.WriteString("\n")
	}

	// Connection types (Relay)
	if g.config.RelayConnection {
		buf.WriteString(g.genConnectionsSchema())
		buf.WriteString("\n")
	}

	// Query and Mutation types
	buf.WriteString(g.genQueryType())
	buf.WriteString("\n")

	if g.config.Mutations {
		buf.WriteString(g.genMutationType())
	}

	// Subscription type
	if subType := g.genSubscriptionType(); subType != "" {
		buf.WriteString("\n")
		buf.WriteString(subType)
	}

	return buf.String()
}

// genRootSchema generates the root schema file that imports other files.
func (g *Generator) genRootSchema() string {
	var buf bytes.Buffer
	buf.WriteString("# Code generated by velox. DO NOT EDIT.\n\n")
	buf.WriteString("# This schema imports types from the schema/ directory.\n")
	buf.WriteString("# Use gqlgen's schema glob to include all files.\n\n")

	// Federation v2 @link directive
	if g.hasFederationEntities() {
		buf.WriteString(federationLinkDirective())
		buf.WriteString("\n\n")
	}

	buf.WriteString(g.genQueryType())
	buf.WriteString("\n")

	if g.config.Mutations {
		buf.WriteString(g.genMutationType())
	}

	// Subscription type
	if subType := g.genSubscriptionType(); subType != "" {
		buf.WriteString("\n")
		buf.WriteString(subType)
	}

	return buf.String()
}

// genPerEntityRootSchema generates the root schema file for SchemaSplitPerEntity mode.
// Contains shared types only: directives, scalars, Node interface, OrderDirection,
// PageInfo, Query type, Mutation type.
// Entity types, enums, and entity-specific types (WhereInput, OrderBy, Connection/Edge,
// mutation inputs) go in per-entity files (velox_{entity}.graphql).
func (g *Generator) genPerEntityRootSchema() string {
	var buf bytes.Buffer

	buf.WriteString("# Code generated by velox. DO NOT EDIT.\n\n")

	// Federation v2 @link directive (before any type definitions)
	if g.hasFederationEntities() {
		buf.WriteString(federationLinkDirective())
		buf.WriteString("\n\n")
	}

	// Scalars (directives, Cursor, Time, typed JSON scalars)
	buf.WriteString(g.genScalarsSchema())
	buf.WriteString("\n")

	// Node interface (Relay)
	if g.config.RelaySpec {
		buf.WriteString(g.genNodeInterface())
		buf.WriteString("\n")
	}

	// OrderDirection enum (shared) — OrderBy inputs are in per-entity files
	if g.config.Ordering {
		buf.WriteString(`"""
Possible directions in which to order a list of items when provided an ` + "`orderBy`" + ` argument.
"""
enum OrderDirection {
  """
  Specifies an ascending order for a given ` + "`orderBy`" + ` argument.
  """
  ASC
  """
  Specifies a descending order for a given ` + "`orderBy`" + ` argument.
  """
  DESC
}

`)
	}

	// PageInfo type (shared) — Connection/Edge types are in per-entity files
	if g.config.RelayConnection {
		buf.WriteString(g.genPageInfoSchema())
		buf.WriteString("\n")
	}

	// Shared enums (same name across multiple entities with identical values)
	// are emitted in the root file so they appear exactly once.
	if len(g.sharedEnums) > 0 {
		buf.WriteString(g.genSharedEnumTypes())
	}

	// Query and Mutation types
	buf.WriteString(g.genQueryType())
	buf.WriteString("\n")

	if g.config.Mutations {
		buf.WriteString(g.genMutationType())
	}

	// Subscription type
	if subType := g.genSubscriptionType(); subType != "" {
		buf.WriteString("\n")
		buf.WriteString(subType)
	}

	return buf.String()
}

// genSharedEnumTypes generates enum definitions for enums shared across multiple entities.
// Each shared enum is emitted once, using the first entity that owns it.
func (g *Generator) genSharedEnumTypes() string {
	var buf bytes.Buffer
	generated := make(map[string]bool)
	nodes := g.filterNodes(g.graph.Nodes, SkipType)
	for _, t := range nodes {
		fields := g.filterFields(t.Fields, SkipEnumField)
		for _, f := range fields {
			if !f.IsEnum() {
				continue
			}
			enumName := t.Name + pascal(f.Name)
			ann := g.getFieldAnnotation(f)
			if customType := ann.GetType(); customType != "" {
				enumName = customType
			}
			owner, shared := g.sharedEnums[enumName]
			if !shared || owner != t.Name || generated[enumName] {
				continue
			}
			generated[enumName] = true
			buf.WriteString(g.genEnumType(t, f))
			buf.WriteString("\n")
		}
	}
	return buf.String()
}

// genPageInfoSchema generates the PageInfo type definition in GraphQL SDL.
// Extracted from genConnectionsSchema for reuse in per-entity split mode.
func (g *Generator) genPageInfoSchema() string {
	var buf bytes.Buffer
	buf.WriteString(`"""
Information about pagination in a connection.
https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
"""
`)
	if g.config.ORMPackage != "" {
		fmt.Fprintf(&buf, "type PageInfo @goModel(model: \"%s.PageInfo\") {\n", gqlrelayPkg)
	} else {
		buf.WriteString("type PageInfo {\n")
	}
	buf.WriteString(`  """
  When paginating forwards, are there more items?
  """
  hasNextPage: Boolean!
  """
  When paginating backwards, are there more items?
  """
  hasPreviousPage: Boolean!
  """
  When paginating backwards, the cursor to continue.
  """
  startCursor: Cursor
  """
  When paginating forwards, the cursor to continue.
  """
  endCursor: Cursor
}
`)
	return buf.String()
}

// genQueryType generates the Query type.
func (g *Generator) genQueryType() string {
	var buf bytes.Buffer
	buf.WriteString("type Query {\n")

	// Node query (Relay) with documentation
	if g.config.RelaySpec {
		buf.WriteString(`  """
  Fetches an object given its ID.
  """
  node(
    """
    ID of the object.
    """
    id: ID!
  ): Node
  """
  Lookup nodes by a list of IDs.
  """
  nodes(
    """
    The list of node IDs.
    """
    ids: [ID!]!
  ): [Node]!
`)
	}

	// Entity queries (no individual entity queries like Ent - use node() instead)
	// Use filterNodes helper (like Ent)
	nodes := g.filterNodes(g.graph.Nodes, SkipType)
	for _, t := range nodes {
		typeName := g.graphqlTypeName(t)
		pluralName := camel(pluralize(typeName))

		// List/connection query
		if g.config.RelayConnection && g.hasRelayConnection(t) {
			orderByArg := g.orderByArg(t)
			args := g.genQueryConnectionArgs(t, typeName, orderByArg)
			fmt.Fprintf(&buf, "  %s%s: %sConnection!\n", pluralName, args, typeName)
		} else {
			// Simple list query for QueryField-only entities (no args like Ent)
			fmt.Fprintf(&buf, "  %s: [%s!]!\n", pluralName, typeName)
		}
	}

	buf.WriteString("}\n")
	return buf.String()
}

// genQueryConnectionArgs generates documented connection arguments for Query type.
func (g *Generator) genQueryConnectionArgs(t *gen.Type, typeName string, orderByArg string) string {
	var buf bytes.Buffer
	writeConnectionBaseArgs(&buf)
	// Ent order: orderBy before where
	if g.config.Ordering && g.wantsOrderField(t) {
		fmt.Fprintf(&buf, `    """
    Ordering options for %s returned from the connection.
    """
    %s

`, pluralize(typeName), orderByArg)
	}
	if g.config.WhereInputs && g.wantsWhereInput(t) {
		fmt.Fprintf(&buf, `    """
    Filtering options for %s returned from the connection.
    """
    where: %sWhereInput
`, pluralize(typeName), typeName)
	}
	buf.WriteString("  )")
	return buf.String()
}

// genMutationType generates the Mutation type.
// Returns empty string if no mutations are defined (opt-in style).
func (g *Generator) genMutationType() string {
	var mutations []string

	// Use filterNodes helper (like Ent)
	nodes := g.filterNodes(g.graph.Nodes, SkipType)
	for _, t := range nodes {
		typeName := g.graphqlTypeName(t)

		// Create mutation
		if g.wantsMutationCreate(t) {
			mutations = append(mutations, fmt.Sprintf("  create%s(input: Create%sInput!): %s!", typeName, typeName, typeName))
		}

		// Update mutation
		if g.wantsMutationUpdate(t) {
			mutations = append(mutations, fmt.Sprintf("  update%s(id: ID!, input: Update%sInput!): %s!", typeName, typeName, typeName))
		}

		// Delete mutation
		if g.wantsMutationDelete(t) {
			mutations = append(mutations, fmt.Sprintf("  delete%s(id: ID!): ID!", typeName))
		}
	}

	// Don't generate empty Mutation type - GraphQL requires at least one field
	if len(mutations) == 0 {
		return ""
	}

	var buf bytes.Buffer
	buf.WriteString("type Mutation {\n")
	for _, m := range mutations {
		buf.WriteString(m)
		buf.WriteString("\n")
	}
	buf.WriteString("}\n")
	return buf.String()
}

// genEntitySchemaFile generates a per-entity schema file containing the entity type
// definition, its enums, and all entity-specific types: WhereInput, OrderBy,
// Connection/Edge, and mutation inputs.
// Shared types (directives, scalars, Node, OrderDirection, PageInfo, Query, Mutation)
// stay in the root schema file.
func (g *Generator) genEntitySchemaFile(t *gen.Type) string {
	var buf bytes.Buffer
	buf.WriteString("# Code generated by velox. DO NOT EDIT.\n\n")

	// Entity type definition
	buf.WriteString(g.genEntityType(t))
	buf.WriteString("\n")

	// Enum types for this entity's fields
	buf.WriteString(g.genEntityEnumTypes(t))

	// WhereInput (the largest type — 50-100+ lines per entity)
	if g.config.WhereInputs && g.wantsWhereInput(t) {
		buf.WriteString(g.genWhereInput(t))
		buf.WriteString("\n")
	}

	// OrderBy input + OrderField enum (only for Relay connection entities —
	// non-Relay entities use simple list queries with no orderBy argument)
	if g.config.Ordering && g.wantsOrderField(t) && g.hasRelayConnection(t) {
		buf.WriteString(g.genOrderBy(t))
		buf.WriteString("\n")
	}

	// Connection + Edge types (Relay)
	if g.config.RelayConnection && g.hasRelayConnection(t) {
		buf.WriteString(g.genEntityConnectionSchema(t))
		buf.WriteString("\n")
	}

	// Mutation inputs (CreateXXXInput, UpdateXXXInput)
	if g.config.Mutations {
		if g.wantsMutationCreate(t) {
			buf.WriteString(g.genCreateInput(t))
			buf.WriteString("\n")
		}
		if g.wantsMutationUpdate(t) {
			buf.WriteString(g.genUpdateInput(t))
			buf.WriteString("\n")
		}
	}

	return buf.String()
}
