// Code generated by velox. DO NOT EDIT.

package user

// CreateUserInput represents a mutation input for creating users.
type CreateUserInput struct {
	Name    string  `json:"name"`
	Email   string  `json:"email"`
	Age     *int    `json:"age,omitempty"`
	Bio     *string `json:"bio,omitempty"`
	PostIDs []int64 `json:"postIDs,omitempty"`
}

// Mutate applies the CreateUserInput on the UserMutation builder.
func (i *CreateUserInput) Mutate(m *UserMutation) {
	m.SetName(i.Name)
	m.SetEmail(i.Email)
	if i.Age != nil {
		m.SetAge(*i.Age)
	}
	if i.Bio != nil {
		m.SetBio(*i.Bio)
	}
	if len(i.PostIDs) > 0 {
		m.AddPostIDs(i.PostIDs...)
	}
}

// SetInput applies the change-set in the CreateUserInput on the UserCreate builder.
func (c *UserCreate) SetInput(i CreateUserInput) *UserCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateUserInput represents a mutation input for updating users.
type UpdateUserInput struct {
	Name          *string `json:"name,omitempty"`
	Email         *string `json:"email,omitempty"`
	Age           *int    `json:"age,omitempty"`
	ClearBio      bool    `json:"clearBio,omitempty"`
	Bio           *string `json:"bio,omitempty"`
	ClearPosts    bool    `json:"clearPosts,omitempty"`
	AddPostIDs    []int64 `json:"addPostIDs,omitempty"`
	RemovePostIDs []int64 `json:"removePostIDs,omitempty"`
}

// Mutate applies the UpdateUserInput on the UserMutation builder.
func (i *UpdateUserInput) Mutate(m *UserMutation) {
	if i.Name != nil {
		m.SetName(*i.Name)
	}
	if i.Email != nil {
		m.SetEmail(*i.Email)
	}
	if i.Age != nil {
		m.SetAge(*i.Age)
	}
	if i.ClearBio {
		m.ClearBio()
	}
	if i.Bio != nil {
		m.SetBio(*i.Bio)
	}
	if i.ClearPosts {
		m.ClearPosts()
	}
	if len(i.AddPostIDs) > 0 {
		m.AddPostIDs(i.AddPostIDs...)
	}
	if len(i.RemovePostIDs) > 0 {
		m.RemovePostIDs(i.RemovePostIDs...)
	}
}

// SetInput applies the change-set in the UpdateUserInput on the UserUpdate builder.
func (c *UserUpdate) SetInput(i UpdateUserInput) *UserUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateUserInput on the UserUpdateOne builder.
func (c *UserUpdateOne) SetInput(i UpdateUserInput) *UserUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
