// Code generated by velox. DO NOT EDIT.

package query

import (
	"context"

	"example.com/app/velox/entity"
	"example.com/app/velox/user"
	"github.com/syssam/velox/contrib/graphql/gqlrelay"
	"github.com/syssam/velox/dialect/sql"
)

// Paginate returns a paginated UserConnection using Relay cursor pagination.
func (q *UserQuery) Paginate(ctx context.Context, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, opts ...entity.UserPaginateOption) (*entity.UserConnection, error) {
	if err := gqlrelay.ValidateFirstLast(first, last); err != nil {
		return nil, err
	}
	cfg := &entity.UserPagerConfig{}
	for _, opt := range opts {
		opt(cfg)
	}
	if cfg.Filter != nil {
		p, err := cfg.Filter()
		if err != nil {
			return nil, err
		}
		if p != nil {
			q.Where(p)
		}
	}
	totalCount, err := q.Clone().Count(ctx)
	if err != nil {
		return nil, err
	}
	var sqlDir gqlrelay.OrderDirection = gqlrelay.OrderDirectionAsc
	if cfg.Order != nil && cfg.Order.Field != nil {
		sqlDir = cfg.Order.Direction
	}
	if last != nil {
		sqlDir = sqlDir.Reverse()
	}
	if cfg.Order != nil && cfg.Order.Field != nil {
		q.Order(sql.OrderByField(cfg.Order.Field.Column, gqlrelay.DirectionOrderTerm(sqlDir)).ToFunc())
		q.Order(sql.OrderByField(user.FieldID, gqlrelay.DirectionOrderTerm(sqlDir)).ToFunc())
	} else {
		q.Order(sql.OrderByField(user.FieldID, gqlrelay.DirectionOrderTerm(sqlDir)).ToFunc())
	}
	if after != nil || before != nil {
		var orderField string
		var orderDir gqlrelay.OrderDirection = gqlrelay.OrderDirectionAsc
		if cfg.Order != nil && cfg.Order.Field != nil {
			orderField = cfg.Order.Field.Column
			orderDir = cfg.Order.Direction
		}
		for _, p := range gqlrelay.CursorsPredicate(after, before, user.FieldID, orderField, orderDir) {
			q.Where(p)
		}
	}
	if first != nil {
		q.Limit(*first + 1)
	} else if last != nil {
		q.Limit(*last + 1)
	}
	nodes, err := q.All(ctx)
	if err != nil {
		return nil, err
	}
	var backwardHasPrev bool
	if last != nil {
		if len(nodes) > *last {
			nodes = nodes[:len(nodes)-1]
			backwardHasPrev = true
		}
		for i, j := 0, len(nodes)-1; i < j; i, j = i+1, j-1 {
			nodes[i], nodes[j] = nodes[j], nodes[i]
		}
	}
	conn := entity.BuildUserConnection(nodes, totalCount, cfg.Order, after, first, before, nil)
	if backwardHasPrev {
		conn.PageInfo.HasPreviousPage = true
	}
	return conn, nil
}
