package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"example.com/shop/velox"
	"github.com/google/uuid"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input velox.CreateCategoryInput) (*velox.Category, error) {
	return r.client.Category.Create().SetInput(input).Save(ctx)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id uuid.UUID, input velox.UpdateCategoryInput) (*velox.Category, error) {
	return r.client.Category.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	if err := r.client.Category.DeleteOneID(id).Exec(ctx); err != nil {
		return uuid.Nil, err
	}
	return id, nil
}

// CreateCustomer is the resolver for the createCustomer field.
func (r *mutationResolver) CreateCustomer(ctx context.Context, input velox.CreateCustomerInput) (*velox.Customer, error) {
	return r.client.Customer.Create().SetInput(input).Save(ctx)
}

// UpdateCustomer is the resolver for the updateCustomer field.
func (r *mutationResolver) UpdateCustomer(ctx context.Context, id uuid.UUID, input velox.UpdateCustomerInput) (*velox.Customer, error) {
	return r.client.Customer.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteCustomer is the resolver for the deleteCustomer field.
func (r *mutationResolver) DeleteCustomer(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	if err := r.client.Customer.DeleteOneID(id).Exec(ctx); err != nil {
		return uuid.Nil, err
	}
	return id, nil
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input velox.CreateOrderInput) (*velox.Order, error) {
	return r.client.Order.Create().SetInput(input).Save(ctx)
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, id uuid.UUID, input velox.UpdateOrderInput) (*velox.Order, error) {
	return r.client.Order.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteOrder is the resolver for the deleteOrder field.
func (r *mutationResolver) DeleteOrder(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	if err := r.client.Order.DeleteOneID(id).Exec(ctx); err != nil {
		return uuid.Nil, err
	}
	return id, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input velox.CreateProductInput) (*velox.Product, error) {
	return r.client.Product.Create().SetInput(input).Save(ctx)
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id uuid.UUID, input velox.UpdateProductInput) (*velox.Product, error) {
	return r.client.Product.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	if err := r.client.Product.DeleteOneID(id).Exec(ctx); err != nil {
		return uuid.Nil, err
	}
	return id, nil
}

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, input velox.CreateReviewInput) (*velox.Review, error) {
	return r.client.Review.Create().SetInput(input).Save(ctx)
}

// UpdateReview is the resolver for the updateReview field.
func (r *mutationResolver) UpdateReview(ctx context.Context, id uuid.UUID, input velox.UpdateReviewInput) (*velox.Review, error) {
	return r.client.Review.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteReview is the resolver for the deleteReview field.
func (r *mutationResolver) DeleteReview(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	if err := r.client.Review.DeleteOneID(id).Exec(ctx); err != nil {
		return uuid.Nil, err
	}
	return id, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input velox.CreateTagInput) (*velox.Tag, error) {
	return r.client.Tag.Create().SetInput(input).Save(ctx)
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, id uuid.UUID, input velox.UpdateTagInput) (*velox.Tag, error) {
	return r.client.Tag.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	if err := r.client.Tag.DeleteOneID(id).Exec(ctx); err != nil {
		return uuid.Nil, err
	}
	return id, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input velox.CreateUserInput) (*velox.User, error) {
	return r.client.User.Create().SetInput(input).Save(ctx)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, input velox.UpdateUserInput) (*velox.User, error) {
	return r.client.User.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	if err := r.client.User.DeleteOneID(id).Exec(ctx); err != nil {
		return uuid.Nil, err
	}
	return id, nil
}

// Subtotal is the resolver for the subtotal field.
func (r *orderResolver) Subtotal(ctx context.Context, obj *velox.Order) (string, error) {
	panic(fmt.Errorf("not implemented: Subtotal - subtotal"))
}

// DiscountAmount is the resolver for the discountAmount field.
func (r *orderResolver) DiscountAmount(ctx context.Context, obj *velox.Order) (string, error) {
	panic(fmt.Errorf("not implemented: DiscountAmount - discountAmount"))
}

// TaxAmount is the resolver for the taxAmount field.
func (r *orderResolver) TaxAmount(ctx context.Context, obj *velox.Order) (string, error) {
	panic(fmt.Errorf("not implemented: TaxAmount - taxAmount"))
}

// ShippingCost is the resolver for the shippingCost field.
func (r *orderResolver) ShippingCost(ctx context.Context, obj *velox.Order) (string, error) {
	panic(fmt.Errorf("not implemented: ShippingCost - shippingCost"))
}

// Total is the resolver for the total field.
func (r *orderResolver) Total(ctx context.Context, obj *velox.Order) (string, error) {
	panic(fmt.Errorf("not implemented: Total - total"))
}

// UnitPrice is the resolver for the unitPrice field.
func (r *orderItemResolver) UnitPrice(ctx context.Context, obj *velox.OrderItem) (string, error) {
	panic(fmt.Errorf("not implemented: UnitPrice - unitPrice"))
}

// LineTotal is the resolver for the lineTotal field.
func (r *orderItemResolver) LineTotal(ctx context.Context, obj *velox.OrderItem) (string, error) {
	panic(fmt.Errorf("not implemented: LineTotal - lineTotal"))
}

// Price is the resolver for the price field.
func (r *productResolver) Price(ctx context.Context, obj *velox.Product) (string, error) {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// CostPrice is the resolver for the costPrice field.
func (r *productResolver) CostPrice(ctx context.Context, obj *velox.Product) (*string, error) {
	panic(fmt.Errorf("not implemented: CostPrice - costPrice"))
}

// CompareAtPrice is the resolver for the compareAtPrice field.
func (r *productResolver) CompareAtPrice(ctx context.Context, obj *velox.Product) (*string, error) {
	panic(fmt.Errorf("not implemented: CompareAtPrice - compareAtPrice"))
}

// ImageUrls is the resolver for the imageUrls field.
func (r *productResolver) ImageUrls(ctx context.Context, obj *velox.Product) (map[string]any, error) {
	if obj.ImageUrls == nil {
		return nil, nil
	}
	// Convert []string to map with index keys for JSON scalar
	result := make(map[string]any)
	result["urls"] = obj.ImageUrls
	return result, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id uuid.UUID) (velox.Noder, error) {
	return r.client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []uuid.UUID) ([]velox.Noder, error) {
	return r.client.Noders(ctx, ids)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, after *velox.Cursor, first *int, before *velox.Cursor, last *int, orderBy *velox.CategoryOrder, where *velox.CategoryWhereInput) (*velox.CategoryConnection, error) {
	query := r.client.Category.Query()
	opts := []velox.CategoryPaginateOption{
		velox.WithCategoryOrder(orderBy),
	}
	if where != nil {
		opts = append(opts, velox.WithCategoryFilter(where.Filter))
	}
	return query.Paginate(ctx, after, first, before, last, opts...)
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context, after *velox.Cursor, first *int, before *velox.Cursor, last *int, orderBy *velox.CustomerOrder, where *velox.CustomerWhereInput) (*velox.CustomerConnection, error) {
	query := r.client.Customer.Query()
	opts := []velox.CustomerPaginateOption{
		velox.WithCustomerOrder(orderBy),
	}
	if where != nil {
		opts = append(opts, velox.WithCustomerFilter(where.Filter))
	}
	return query.Paginate(ctx, after, first, before, last, opts...)
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, after *velox.Cursor, first *int, before *velox.Cursor, last *int, orderBy *velox.OrderOrder, where *velox.OrderWhereInput) (*velox.OrderConnection, error) {
	query := r.client.Order.Query()
	opts := []velox.OrderPaginateOption{
		velox.WithOrderOrder(orderBy),
	}
	if where != nil {
		opts = append(opts, velox.WithOrderFilter(where.Filter))
	}
	return query.Paginate(ctx, after, first, before, last, opts...)
}

// OrderItems is the resolver for the orderItems field.
func (r *queryResolver) OrderItems(ctx context.Context, after *velox.Cursor, first *int, before *velox.Cursor, last *int, orderBy *velox.OrderItemOrder, where *velox.OrderItemWhereInput) (*velox.OrderItemConnection, error) {
	query := r.client.OrderItem.Query()
	opts := []velox.OrderItemPaginateOption{
		velox.WithOrderItemOrder(orderBy),
	}
	if where != nil {
		opts = append(opts, velox.WithOrderItemFilter(where.Filter))
	}
	return query.Paginate(ctx, after, first, before, last, opts...)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, after *velox.Cursor, first *int, before *velox.Cursor, last *int, orderBy *velox.ProductOrder, where *velox.ProductWhereInput) (*velox.ProductConnection, error) {
	query := r.client.Product.Query()
	opts := []velox.ProductPaginateOption{
		velox.WithProductOrder(orderBy),
	}
	if where != nil {
		opts = append(opts, velox.WithProductFilter(where.Filter))
	}
	return query.Paginate(ctx, after, first, before, last, opts...)
}

// Reviews is the resolver for the reviews field.
func (r *queryResolver) Reviews(ctx context.Context, after *velox.Cursor, first *int, before *velox.Cursor, last *int, orderBy *velox.ReviewOrder, where *velox.ReviewWhereInput) (*velox.ReviewConnection, error) {
	query := r.client.Review.Query()
	opts := []velox.ReviewPaginateOption{
		velox.WithReviewOrder(orderBy),
	}
	if where != nil {
		opts = append(opts, velox.WithReviewFilter(where.Filter))
	}
	return query.Paginate(ctx, after, first, before, last, opts...)
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, after *velox.Cursor, first *int, before *velox.Cursor, last *int, orderBy *velox.TagOrder, where *velox.TagWhereInput) (*velox.TagConnection, error) {
	query := r.client.Tag.Query()
	opts := []velox.TagPaginateOption{
		velox.WithTagOrder(orderBy),
	}
	if where != nil {
		opts = append(opts, velox.WithTagFilter(where.Filter))
	}
	return query.Paginate(ctx, after, first, before, last, opts...)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, after *velox.Cursor, first *int, before *velox.Cursor, last *int, orderBy *velox.UserOrder, where *velox.UserWhereInput) (*velox.UserConnection, error) {
	query := r.client.User.Query()
	opts := []velox.UserPaginateOption{
		velox.WithUserOrder(orderBy),
	}
	if where != nil {
		opts = append(opts, velox.WithUserFilter(where.Filter))
	}
	return query.Paginate(ctx, after, first, before, last, opts...)
}

// Subtotal is the resolver for the subtotal field.
func (r *createOrderInputResolver) Subtotal(ctx context.Context, obj *velox.CreateOrderInput, data string) error {
	panic(fmt.Errorf("not implemented: Subtotal - subtotal"))
}

// DiscountAmount is the resolver for the discountAmount field.
func (r *createOrderInputResolver) DiscountAmount(ctx context.Context, obj *velox.CreateOrderInput, data string) error {
	panic(fmt.Errorf("not implemented: DiscountAmount - discountAmount"))
}

// TaxAmount is the resolver for the taxAmount field.
func (r *createOrderInputResolver) TaxAmount(ctx context.Context, obj *velox.CreateOrderInput, data string) error {
	panic(fmt.Errorf("not implemented: TaxAmount - taxAmount"))
}

// ShippingCost is the resolver for the shippingCost field.
func (r *createOrderInputResolver) ShippingCost(ctx context.Context, obj *velox.CreateOrderInput, data string) error {
	panic(fmt.Errorf("not implemented: ShippingCost - shippingCost"))
}

// Total is the resolver for the total field.
func (r *createOrderInputResolver) Total(ctx context.Context, obj *velox.CreateOrderInput, data string) error {
	panic(fmt.Errorf("not implemented: Total - total"))
}

// Price is the resolver for the price field.
func (r *createProductInputResolver) Price(ctx context.Context, obj *velox.CreateProductInput, data string) error {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// CostPrice is the resolver for the costPrice field.
func (r *createProductInputResolver) CostPrice(ctx context.Context, obj *velox.CreateProductInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostPrice - costPrice"))
}

// CompareAtPrice is the resolver for the compareAtPrice field.
func (r *createProductInputResolver) CompareAtPrice(ctx context.Context, obj *velox.CreateProductInput, data *string) error {
	panic(fmt.Errorf("not implemented: CompareAtPrice - compareAtPrice"))
}

// ImageUrls is the resolver for the imageUrls field.
func (r *createProductInputResolver) ImageUrls(ctx context.Context, obj *velox.CreateProductInput, data map[string]any) error {
	if data == nil {
		return nil
	}
	// Convert map[string]any to []string
	if urls, ok := data["urls"].([]any); ok {
		var result []string
		for _, u := range urls {
			if s, ok := u.(string); ok {
				result = append(result, s)
			}
		}
		obj.ImageUrls = result
	}
	return nil
}

// UnitPrice is the resolver for the unitPrice field.
func (r *orderItemWhereInputResolver) UnitPrice(ctx context.Context, obj *velox.OrderItemWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: UnitPrice - unitPrice"))
}

// UnitPriceNeq is the resolver for the unitPriceNEQ field.
func (r *orderItemWhereInputResolver) UnitPriceNeq(ctx context.Context, obj *velox.OrderItemWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: UnitPriceNeq - unitPriceNEQ"))
}

// UnitPriceIn is the resolver for the unitPriceIn field.
func (r *orderItemWhereInputResolver) UnitPriceIn(ctx context.Context, obj *velox.OrderItemWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: UnitPriceIn - unitPriceIn"))
}

// UnitPriceNotIn is the resolver for the unitPriceNotIn field.
func (r *orderItemWhereInputResolver) UnitPriceNotIn(ctx context.Context, obj *velox.OrderItemWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: UnitPriceNotIn - unitPriceNotIn"))
}

// LineTotal is the resolver for the lineTotal field.
func (r *orderItemWhereInputResolver) LineTotal(ctx context.Context, obj *velox.OrderItemWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LineTotal - lineTotal"))
}

// LineTotalNeq is the resolver for the lineTotalNEQ field.
func (r *orderItemWhereInputResolver) LineTotalNeq(ctx context.Context, obj *velox.OrderItemWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: LineTotalNeq - lineTotalNEQ"))
}

// LineTotalIn is the resolver for the lineTotalIn field.
func (r *orderItemWhereInputResolver) LineTotalIn(ctx context.Context, obj *velox.OrderItemWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: LineTotalIn - lineTotalIn"))
}

// LineTotalNotIn is the resolver for the lineTotalNotIn field.
func (r *orderItemWhereInputResolver) LineTotalNotIn(ctx context.Context, obj *velox.OrderItemWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: LineTotalNotIn - lineTotalNotIn"))
}

// Subtotal is the resolver for the subtotal field.
func (r *orderWhereInputResolver) Subtotal(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Subtotal - subtotal"))
}

// SubtotalNeq is the resolver for the subtotalNEQ field.
func (r *orderWhereInputResolver) SubtotalNeq(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: SubtotalNeq - subtotalNEQ"))
}

// SubtotalIn is the resolver for the subtotalIn field.
func (r *orderWhereInputResolver) SubtotalIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: SubtotalIn - subtotalIn"))
}

// SubtotalNotIn is the resolver for the subtotalNotIn field.
func (r *orderWhereInputResolver) SubtotalNotIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: SubtotalNotIn - subtotalNotIn"))
}

// DiscountAmount is the resolver for the discountAmount field.
func (r *orderWhereInputResolver) DiscountAmount(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: DiscountAmount - discountAmount"))
}

// DiscountAmountNeq is the resolver for the discountAmountNEQ field.
func (r *orderWhereInputResolver) DiscountAmountNeq(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: DiscountAmountNeq - discountAmountNEQ"))
}

// DiscountAmountIn is the resolver for the discountAmountIn field.
func (r *orderWhereInputResolver) DiscountAmountIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: DiscountAmountIn - discountAmountIn"))
}

// DiscountAmountNotIn is the resolver for the discountAmountNotIn field.
func (r *orderWhereInputResolver) DiscountAmountNotIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: DiscountAmountNotIn - discountAmountNotIn"))
}

// TaxAmount is the resolver for the taxAmount field.
func (r *orderWhereInputResolver) TaxAmount(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: TaxAmount - taxAmount"))
}

// TaxAmountNeq is the resolver for the taxAmountNEQ field.
func (r *orderWhereInputResolver) TaxAmountNeq(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: TaxAmountNeq - taxAmountNEQ"))
}

// TaxAmountIn is the resolver for the taxAmountIn field.
func (r *orderWhereInputResolver) TaxAmountIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: TaxAmountIn - taxAmountIn"))
}

// TaxAmountNotIn is the resolver for the taxAmountNotIn field.
func (r *orderWhereInputResolver) TaxAmountNotIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: TaxAmountNotIn - taxAmountNotIn"))
}

// ShippingCost is the resolver for the shippingCost field.
func (r *orderWhereInputResolver) ShippingCost(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ShippingCost - shippingCost"))
}

// ShippingCostNeq is the resolver for the shippingCostNEQ field.
func (r *orderWhereInputResolver) ShippingCostNeq(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ShippingCostNeq - shippingCostNEQ"))
}

// ShippingCostIn is the resolver for the shippingCostIn field.
func (r *orderWhereInputResolver) ShippingCostIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: ShippingCostIn - shippingCostIn"))
}

// ShippingCostNotIn is the resolver for the shippingCostNotIn field.
func (r *orderWhereInputResolver) ShippingCostNotIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: ShippingCostNotIn - shippingCostNotIn"))
}

// Total is the resolver for the total field.
func (r *orderWhereInputResolver) Total(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Total - total"))
}

// TotalNeq is the resolver for the totalNEQ field.
func (r *orderWhereInputResolver) TotalNeq(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: TotalNeq - totalNEQ"))
}

// TotalIn is the resolver for the totalIn field.
func (r *orderWhereInputResolver) TotalIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: TotalIn - totalIn"))
}

// TotalNotIn is the resolver for the totalNotIn field.
func (r *orderWhereInputResolver) TotalNotIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: TotalNotIn - totalNotIn"))
}

// InternalNotes is the resolver for the internalNotes field.
// NOTE: internal_notes is skipped from the Go struct via graphql.Skip(graphql.SkipType), so this is a no-op.
func (r *orderWhereInputResolver) InternalNotes(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesNeq is the resolver for the internalNotesNEQ field.
func (r *orderWhereInputResolver) InternalNotesNeq(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesIn is the resolver for the internalNotesIn field.
func (r *orderWhereInputResolver) InternalNotesIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	return nil
}

// InternalNotesNotIn is the resolver for the internalNotesNotIn field.
func (r *orderWhereInputResolver) InternalNotesNotIn(ctx context.Context, obj *velox.OrderWhereInput, data []string) error {
	return nil
}

// InternalNotesGt is the resolver for the internalNotesGT field.
func (r *orderWhereInputResolver) InternalNotesGt(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesGte is the resolver for the internalNotesGTE field.
func (r *orderWhereInputResolver) InternalNotesGte(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesLt is the resolver for the internalNotesLT field.
func (r *orderWhereInputResolver) InternalNotesLt(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesLte is the resolver for the internalNotesLTE field.
func (r *orderWhereInputResolver) InternalNotesLte(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesContains is the resolver for the internalNotesContains field.
func (r *orderWhereInputResolver) InternalNotesContains(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesHasPrefix is the resolver for the internalNotesHasPrefix field.
func (r *orderWhereInputResolver) InternalNotesHasPrefix(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesHasSuffix is the resolver for the internalNotesHasSuffix field.
func (r *orderWhereInputResolver) InternalNotesHasSuffix(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesEqualFold is the resolver for the internalNotesEqualFold field.
func (r *orderWhereInputResolver) InternalNotesEqualFold(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesContainsFold is the resolver for the internalNotesContainsFold field.
func (r *orderWhereInputResolver) InternalNotesContainsFold(ctx context.Context, obj *velox.OrderWhereInput, data *string) error {
	return nil
}

// InternalNotesIsNil is the resolver for the internalNotesIsNil field.
func (r *orderWhereInputResolver) InternalNotesIsNil(ctx context.Context, obj *velox.OrderWhereInput, data *bool) error {
	return nil
}

// InternalNotesNotNil is the resolver for the internalNotesNotNil field.
func (r *orderWhereInputResolver) InternalNotesNotNil(ctx context.Context, obj *velox.OrderWhereInput, data *bool) error {
	return nil
}

// Price is the resolver for the price field.
func (r *productWhereInputResolver) Price(ctx context.Context, obj *velox.ProductWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// PriceNeq is the resolver for the priceNEQ field.
func (r *productWhereInputResolver) PriceNeq(ctx context.Context, obj *velox.ProductWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: PriceNeq - priceNEQ"))
}

// PriceIn is the resolver for the priceIn field.
func (r *productWhereInputResolver) PriceIn(ctx context.Context, obj *velox.ProductWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: PriceIn - priceIn"))
}

// PriceNotIn is the resolver for the priceNotIn field.
func (r *productWhereInputResolver) PriceNotIn(ctx context.Context, obj *velox.ProductWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: PriceNotIn - priceNotIn"))
}

// CostPrice is the resolver for the costPrice field.
func (r *productWhereInputResolver) CostPrice(ctx context.Context, obj *velox.ProductWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostPrice - costPrice"))
}

// CostPriceNeq is the resolver for the costPriceNEQ field.
func (r *productWhereInputResolver) CostPriceNeq(ctx context.Context, obj *velox.ProductWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostPriceNeq - costPriceNEQ"))
}

// CostPriceIn is the resolver for the costPriceIn field.
func (r *productWhereInputResolver) CostPriceIn(ctx context.Context, obj *velox.ProductWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: CostPriceIn - costPriceIn"))
}

// CostPriceNotIn is the resolver for the costPriceNotIn field.
func (r *productWhereInputResolver) CostPriceNotIn(ctx context.Context, obj *velox.ProductWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: CostPriceNotIn - costPriceNotIn"))
}

// CompareAtPrice is the resolver for the compareAtPrice field.
func (r *productWhereInputResolver) CompareAtPrice(ctx context.Context, obj *velox.ProductWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CompareAtPrice - compareAtPrice"))
}

// CompareAtPriceNeq is the resolver for the compareAtPriceNEQ field.
func (r *productWhereInputResolver) CompareAtPriceNeq(ctx context.Context, obj *velox.ProductWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: CompareAtPriceNeq - compareAtPriceNEQ"))
}

// CompareAtPriceIn is the resolver for the compareAtPriceIn field.
func (r *productWhereInputResolver) CompareAtPriceIn(ctx context.Context, obj *velox.ProductWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: CompareAtPriceIn - compareAtPriceIn"))
}

// CompareAtPriceNotIn is the resolver for the compareAtPriceNotIn field.
func (r *productWhereInputResolver) CompareAtPriceNotIn(ctx context.Context, obj *velox.ProductWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: CompareAtPriceNotIn - compareAtPriceNotIn"))
}

// Subtotal is the resolver for the subtotal field.
func (r *updateOrderInputResolver) Subtotal(ctx context.Context, obj *velox.UpdateOrderInput, data *string) error {
	panic(fmt.Errorf("not implemented: Subtotal - subtotal"))
}

// DiscountAmount is the resolver for the discountAmount field.
func (r *updateOrderInputResolver) DiscountAmount(ctx context.Context, obj *velox.UpdateOrderInput, data *string) error {
	panic(fmt.Errorf("not implemented: DiscountAmount - discountAmount"))
}

// TaxAmount is the resolver for the taxAmount field.
func (r *updateOrderInputResolver) TaxAmount(ctx context.Context, obj *velox.UpdateOrderInput, data *string) error {
	panic(fmt.Errorf("not implemented: TaxAmount - taxAmount"))
}

// ShippingCost is the resolver for the shippingCost field.
func (r *updateOrderInputResolver) ShippingCost(ctx context.Context, obj *velox.UpdateOrderInput, data *string) error {
	panic(fmt.Errorf("not implemented: ShippingCost - shippingCost"))
}

// Total is the resolver for the total field.
func (r *updateOrderInputResolver) Total(ctx context.Context, obj *velox.UpdateOrderInput, data *string) error {
	panic(fmt.Errorf("not implemented: Total - total"))
}

// Price is the resolver for the price field.
func (r *updateProductInputResolver) Price(ctx context.Context, obj *velox.UpdateProductInput, data *string) error {
	panic(fmt.Errorf("not implemented: Price - price"))
}

// CostPrice is the resolver for the costPrice field.
func (r *updateProductInputResolver) CostPrice(ctx context.Context, obj *velox.UpdateProductInput, data *string) error {
	panic(fmt.Errorf("not implemented: CostPrice - costPrice"))
}

// CompareAtPrice is the resolver for the compareAtPrice field.
func (r *updateProductInputResolver) CompareAtPrice(ctx context.Context, obj *velox.UpdateProductInput, data *string) error {
	panic(fmt.Errorf("not implemented: CompareAtPrice - compareAtPrice"))
}

// ImageUrls is the resolver for the imageUrls field.
func (r *updateProductInputResolver) ImageUrls(ctx context.Context, obj *velox.UpdateProductInput, data map[string]any) error {
	if data == nil {
		return nil
	}
	// Convert map[string]any to []string
	if urls, ok := data["urls"].([]any); ok {
		var result []string
		for _, u := range urls {
			if s, ok := u.(string); ok {
				result = append(result, s)
			}
		}
		obj.ImageUrls = result
	}
	return nil
}

// PasswordHash is the resolver for the passwordHash field.
// NOTE: password_hash is marked as sensitive via graphql.Skip(graphql.SkipType), so this is a no-op.
func (r *userWhereInputResolver) PasswordHash(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashNeq is the resolver for the passwordHashNEQ field.
func (r *userWhereInputResolver) PasswordHashNeq(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashIn is the resolver for the passwordHashIn field.
func (r *userWhereInputResolver) PasswordHashIn(ctx context.Context, obj *velox.UserWhereInput, data []string) error {
	return nil
}

// PasswordHashNotIn is the resolver for the passwordHashNotIn field.
func (r *userWhereInputResolver) PasswordHashNotIn(ctx context.Context, obj *velox.UserWhereInput, data []string) error {
	return nil
}

// PasswordHashGt is the resolver for the passwordHashGT field.
func (r *userWhereInputResolver) PasswordHashGt(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashGte is the resolver for the passwordHashGTE field.
func (r *userWhereInputResolver) PasswordHashGte(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashLt is the resolver for the passwordHashLT field.
func (r *userWhereInputResolver) PasswordHashLt(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashLte is the resolver for the passwordHashLTE field.
func (r *userWhereInputResolver) PasswordHashLte(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashContains is the resolver for the passwordHashContains field.
func (r *userWhereInputResolver) PasswordHashContains(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashHasPrefix is the resolver for the passwordHashHasPrefix field.
func (r *userWhereInputResolver) PasswordHashHasPrefix(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashHasSuffix is the resolver for the passwordHashHasSuffix field.
func (r *userWhereInputResolver) PasswordHashHasSuffix(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashEqualFold is the resolver for the passwordHashEqualFold field.
func (r *userWhereInputResolver) PasswordHashEqualFold(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// PasswordHashContainsFold is the resolver for the passwordHashContainsFold field.
func (r *userWhereInputResolver) PasswordHashContainsFold(ctx context.Context, obj *velox.UserWhereInput, data *string) error {
	return nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// OrderItem returns OrderItemResolver implementation.
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// CreateOrderInput returns CreateOrderInputResolver implementation.
func (r *Resolver) CreateOrderInput() CreateOrderInputResolver { return &createOrderInputResolver{r} }

// CreateProductInput returns CreateProductInputResolver implementation.
func (r *Resolver) CreateProductInput() CreateProductInputResolver {
	return &createProductInputResolver{r}
}

// OrderItemWhereInput returns OrderItemWhereInputResolver implementation.
func (r *Resolver) OrderItemWhereInput() OrderItemWhereInputResolver {
	return &orderItemWhereInputResolver{r}
}

// OrderWhereInput returns OrderWhereInputResolver implementation.
func (r *Resolver) OrderWhereInput() OrderWhereInputResolver { return &orderWhereInputResolver{r} }

// ProductWhereInput returns ProductWhereInputResolver implementation.
func (r *Resolver) ProductWhereInput() ProductWhereInputResolver {
	return &productWhereInputResolver{r}
}

// UpdateOrderInput returns UpdateOrderInputResolver implementation.
func (r *Resolver) UpdateOrderInput() UpdateOrderInputResolver { return &updateOrderInputResolver{r} }

// UpdateProductInput returns UpdateProductInputResolver implementation.
func (r *Resolver) UpdateProductInput() UpdateProductInputResolver {
	return &updateProductInputResolver{r}
}

// UserWhereInput returns UserWhereInputResolver implementation.
func (r *Resolver) UserWhereInput() UserWhereInputResolver { return &userWhereInputResolver{r} }

type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type createOrderInputResolver struct{ *Resolver }
type createProductInputResolver struct{ *Resolver }
type orderItemWhereInputResolver struct{ *Resolver }
type orderWhereInputResolver struct{ *Resolver }
type productWhereInputResolver struct{ *Resolver }
type updateOrderInputResolver struct{ *Resolver }
type updateProductInputResolver struct{ *Resolver }
type userWhereInputResolver struct{ *Resolver }
