package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"example.com/shop/graph/model"
	"example.com/shop/velox"
	"github.com/google/uuid"
)

// CreateOrderWithItems is the resolver for the createOrderWithItems field.
func (r *mutationResolver) CreateOrderWithItems(ctx context.Context, input model.CreateOrderWithItemsInput) (*velox.Order, error) {
	panic(fmt.Errorf("not implemented: CreateOrderWithItems - createOrderWithItems"))
}

// ProductID is the resolver for the productId field.
func (r *orderItemInputResolver) ProductID(ctx context.Context, obj *model.OrderItemInput, data uuid.UUID) error {
	panic(fmt.Errorf("not implemented: ProductID - productId"))
}

// OrderItemInput returns OrderItemInputResolver implementation.
func (r *Resolver) OrderItemInput() OrderItemInputResolver { return &orderItemInputResolver{r} }

type orderItemInputResolver struct{ *Resolver }
