package gqlgen

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"example.com/fullgql/velox/entity"
)

// Summary is the resolver for the summary field.
func (r *userResolver) Summary(ctx context.Context, obj *entity.User) (string, error) {
	if obj.Bio == nil || *obj.Bio == "" {
		return obj.Name, nil
	}
	return obj.Name + " — " + *obj.Bio, nil
}
