package gqlgen

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"example.com/fullgql/velox"
	"example.com/fullgql/velox/category"
	"example.com/fullgql/velox/comment"
	"example.com/fullgql/velox/entity"
	"example.com/fullgql/velox/gqlfilter"
	"example.com/fullgql/velox/label"
	"example.com/fullgql/velox/member"
	"example.com/fullgql/velox/product"
	"example.com/fullgql/velox/tag"
	"example.com/fullgql/velox/todo"
	"example.com/fullgql/velox/user"
	"example.com/fullgql/velox/workspace"
	"github.com/syssam/velox/contrib/graphql/gqlrelay"
)

// Todos is the resolver for the todos field.
//
// Body shape: fast-path eager-load check, then fall through to Paginate.
// This is the recommended pattern for hand-written resolvers in velox —
// mirrors the entity-method fast path (entity/gql_edge_*.go) so that
// parent queries using .WithTodos() don't waste the eager load when the
// user hits this edge via GraphQL.
func (r *categoryResolver) Todos(ctx context.Context, obj *entity.Category, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TodoOrder, where *gqlfilter.TodoWhereInput) (*entity.TodoConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.TodosOrErr(); err == nil {
			return entity.BuildTodoConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Todo.Query().Where(todo.HasCategoryWith(category.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithTodoOrder(orderBy), entity.WithTodoFilter(where.Filter))
}

// Children is the resolver for the children field.
func (r *categoryResolver) Children(ctx context.Context, obj *entity.Category, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.CategoryOrder, where *gqlfilter.CategoryWhereInput) (*entity.CategoryConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.ChildrenOrErr(); err == nil {
			return entity.BuildCategoryConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Category.Query().Where(category.HasParentWith(category.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithCategoryOrder(orderBy), entity.WithCategoryFilter(where.Filter))
}

// Todos is the resolver for the todos field.
func (r *labelResolver) Todos(ctx context.Context, obj *entity.Label, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TodoOrder, where *gqlfilter.TodoWhereInput) (*entity.TodoConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.TodosOrErr(); err == nil {
			return entity.BuildTodoConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Todo.Query().Where(todo.HasLabelsWith(label.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithTodoOrder(orderBy), entity.WithTodoFilter(where.Filter))
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input category.CreateCategoryInput) (*entity.Category, error) {
	return r.Client.Category.Create().SetInput(input).Save(ctx)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id int, input category.UpdateCategoryInput) (*entity.Category, error) {
	return r.Client.Category.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input comment.CreateCommentInput) (*entity.Comment, error) {
	return r.Client.Comment.Create().SetInput(input).Save(ctx)
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id int, input comment.UpdateCommentInput) (*entity.Comment, error) {
	return r.Client.Comment.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input label.CreateLabelInput) (*entity.Label, error) {
	return r.Client.Label.Create().SetInput(input).Save(ctx)
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, id int, input label.UpdateLabelInput) (*entity.Label, error) {
	return r.Client.Label.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateMember is the resolver for the createMember field.
func (r *mutationResolver) CreateMember(ctx context.Context, input member.CreateMemberInput) (*entity.Member, error) {
	return r.Client.Member.Create().SetInput(input).Save(ctx)
}

// UpdateMember is the resolver for the updateMember field.
func (r *mutationResolver) UpdateMember(ctx context.Context, id int, input member.UpdateMemberInput) (*entity.Member, error) {
	return r.Client.Member.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input product.CreateProductInput) (*entity.Product, error) {
	return r.Client.Product.Create().SetInput(input).Save(ctx)
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id int, input product.UpdateProductInput) (*entity.Product, error) {
	return r.Client.Product.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input tag.CreateTagInput) (*entity.Tag, error) {
	return r.Client.Tag.Create().SetInput(input).Save(ctx)
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, id int, input tag.UpdateTagInput) (*entity.Tag, error) {
	return r.Client.Tag.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input todo.CreateTodoInput) (*entity.Todo, error) {
	return r.Client.Todo.Create().SetInput(input).Save(ctx)
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id int, input todo.UpdateTodoInput) (*entity.Todo, error) {
	return r.Client.Todo.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input user.CreateUserInput) (*entity.User, error) {
	return r.Client.User.Create().SetInput(input).Save(ctx)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int, input user.UpdateUserInput) (*entity.User, error) {
	return r.Client.User.UpdateOneID(id).SetInput(input).Save(ctx)
}

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, input workspace.CreateWorkspaceInput) (*entity.Workspace, error) {
	return r.Client.Workspace.Create().SetInput(input).Save(ctx)
}

// UpdateWorkspace is the resolver for the updateWorkspace field.
func (r *mutationResolver) UpdateWorkspace(ctx context.Context, id int, input workspace.UpdateWorkspaceInput) (*entity.Workspace, error) {
	return r.Client.Workspace.UpdateOneID(id).SetInput(input).Save(ctx)
}

// Thumbnail is the resolver for the thumbnail field.
func (r *productResolver) Thumbnail(ctx context.Context, obj *entity.Product) (*string, error) {
	panic(fmt.Errorf("not implemented: Thumbnail - thumbnail"))
}

// Tags is the resolver for the tags field.
func (r *productResolver) Tags(ctx context.Context, obj *entity.Product, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TagOrder, where *gqlfilter.TagWhereInput) (*entity.TagConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.TagsOrErr(); err == nil {
			return entity.BuildTagConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Tag.Query().Where(tag.HasProductsWith(product.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithTagOrder(orderBy), entity.WithTagFilter(where.Filter))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (velox.Noder, error) {
	return r.Client.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]velox.Noder, error) {
	return r.Client.Noders(ctx, ids)
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context) ([]*entity.AuditLog, error) {
	return r.Client.AuditLog.Query().All(ctx)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.CategoryOrder, where *gqlfilter.CategoryWhereInput) (*entity.CategoryConnection, error) {
	return r.Client.Category.Query().Paginate(ctx, after, first, before, last, entity.WithCategoryOrder(orderBy), entity.WithCategoryFilter(where.Filter))
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context) ([]*entity.Comment, error) {
	return r.Client.Comment.Query().All(ctx)
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.LabelOrder, where *gqlfilter.LabelWhereInput) (*entity.LabelConnection, error) {
	return r.Client.Label.Query().Paginate(ctx, after, first, before, last, entity.WithLabelOrder(orderBy), entity.WithLabelFilter(where.Filter))
}

// Members is the resolver for the members field.
func (r *queryResolver) Members(ctx context.Context) ([]*entity.Member, error) {
	return r.Client.Member.Query().All(ctx)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.ProductOrder, where *gqlfilter.ProductWhereInput) (*entity.ProductConnection, error) {
	return r.Client.Product.Query().Paginate(ctx, after, first, before, last, entity.WithProductOrder(orderBy), entity.WithProductFilter(where.Filter))
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TagOrder, where *gqlfilter.TagWhereInput) (*entity.TagConnection, error) {
	return r.Client.Tag.Query().Paginate(ctx, after, first, before, last, entity.WithTagOrder(orderBy), entity.WithTagFilter(where.Filter))
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TodoOrder, where *gqlfilter.TodoWhereInput) (*entity.TodoConnection, error) {
	return r.Client.Todo.Query().Paginate(ctx, after, first, before, last, entity.WithTodoOrder(orderBy), entity.WithTodoFilter(where.Filter))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.UserOrder, where *gqlfilter.UserWhereInput) (*entity.UserConnection, error) {
	return r.Client.User.Query().Paginate(ctx, after, first, before, last, entity.WithUserOrder(orderBy), entity.WithUserFilter(where.Filter))
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.WorkspaceOrder, where *gqlfilter.WorkspaceWhereInput) (*entity.WorkspaceConnection, error) {
	return r.Client.Workspace.Query().Paginate(ctx, after, first, before, last, entity.WithWorkspaceOrder(orderBy), entity.WithWorkspaceFilter(where.Filter))
}

// Todos is the resolver for the todos field.
func (r *tagResolver) Todos(ctx context.Context, obj *entity.Tag, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TodoOrder, where *gqlfilter.TodoWhereInput) (*entity.TodoConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.TodosOrErr(); err == nil {
			return entity.BuildTodoConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Todo.Query().Where(todo.HasTagsWith(tag.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithTodoOrder(orderBy), entity.WithTodoFilter(where.Filter))
}

// Products is the resolver for the products field.
func (r *tagResolver) Products(ctx context.Context, obj *entity.Tag, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.ProductOrder, where *gqlfilter.ProductWhereInput) (*entity.ProductConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.ProductsOrErr(); err == nil {
			return entity.BuildProductConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Product.Query().Where(product.HasTagsWith(tag.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithProductOrder(orderBy), entity.WithProductFilter(where.Filter))
}

// Tags is the resolver for the tags field.
func (r *todoResolver) Tags(ctx context.Context, obj *entity.Todo, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TagOrder, where *gqlfilter.TagWhereInput) (*entity.TagConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.TagsOrErr(); err == nil {
			return entity.BuildTagConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Tag.Query().Where(tag.HasTodosWith(todo.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithTagOrder(orderBy), entity.WithTagFilter(where.Filter))
}

// Labels is the resolver for the labels field.
func (r *todoResolver) Labels(ctx context.Context, obj *entity.Todo, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.LabelOrder, where *gqlfilter.LabelWhereInput) (*entity.LabelConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.LabelsOrErr(); err == nil {
			return entity.BuildLabelConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Label.Query().Where(label.HasTodosWith(todo.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithLabelOrder(orderBy), entity.WithLabelFilter(where.Filter))
}

// Todos is the resolver for the todos field.
func (r *userResolver) Todos(ctx context.Context, obj *entity.User, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TodoOrder, where *gqlfilter.TodoWhereInput) (*entity.TodoConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.TodosOrErr(); err == nil {
			return entity.BuildTodoConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Todo.Query().Where(todo.HasOwnerWith(user.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithTodoOrder(orderBy), entity.WithTodoFilter(where.Filter))
}

// Todos is the resolver for the todos field.
func (r *workspaceResolver) Todos(ctx context.Context, obj *entity.Workspace, after *gqlrelay.Cursor, first *int, before *gqlrelay.Cursor, last *int, orderBy *entity.TodoOrder, where *gqlfilter.TodoWhereInput) (*entity.TodoConnection, error) {
	if where == nil && after == nil && before == nil {
		if nodes, err := obj.Edges.TodosOrErr(); err == nil {
			return entity.BuildTodoConnection(nodes, 0, orderBy, after, first, before, last), nil
		}
	}
	q := r.Client.Todo.Query().Where(todo.HasWorkspaceWith(workspace.IDField.EQ(obj.ID)))
	return q.Paginate(ctx, after, first, before, last, entity.WithTodoOrder(orderBy), entity.WithTodoFilter(where.Filter))
}

// Thumbnail is the resolver for the thumbnail field.
func (r *createProductInputResolver) Thumbnail(ctx context.Context, obj *product.CreateProductInput, data *string) error {
	panic(fmt.Errorf("not implemented: Thumbnail - thumbnail"))
}

// Thumbnail is the resolver for the thumbnail field.
func (r *updateProductInputResolver) Thumbnail(ctx context.Context, obj *product.UpdateProductInput, data *string) error {
	panic(fmt.Errorf("not implemented: Thumbnail - thumbnail"))
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Label returns LabelResolver implementation.
func (r *Resolver) Label() LabelResolver { return &labelResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Tag returns TagResolver implementation.
func (r *Resolver) Tag() TagResolver { return &tagResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// Workspace returns WorkspaceResolver implementation.
func (r *Resolver) Workspace() WorkspaceResolver { return &workspaceResolver{r} }

// CreateProductInput returns CreateProductInputResolver implementation.
func (r *Resolver) CreateProductInput() CreateProductInputResolver {
	return &createProductInputResolver{r}
}

// UpdateProductInput returns UpdateProductInputResolver implementation.
func (r *Resolver) UpdateProductInput() UpdateProductInputResolver {
	return &updateProductInputResolver{r}
}

type categoryResolver struct{ *Resolver }
type labelResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type tagResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type workspaceResolver struct{ *Resolver }
type createProductInputResolver struct{ *Resolver }
type updateProductInputResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *auditLogResolver) User(ctx context.Context, obj *entity.AuditLog) (*entity.User, error) {
	if u, err := obj.Edges.UserOrErr(); err == nil {
		return u, nil
	}
	return r.Client.User.Query().Where(user.HasAuditLogsWith(auditlog.IDField.EQ(obj.ID))).Only(ctx)
}
func (r *categoryResolver) Parent(ctx context.Context, obj *entity.Category) (*entity.Category, error) {
	if parent, err := obj.Edges.ParentOrErr(); err == nil {
		return parent, nil
	}
	return r.Client.Category.Query().Where(category.HasChildrenWith(category.IDField.EQ(obj.ID))).Only(ctx)
}
func (r *commentResolver) Todo(ctx context.Context, obj *entity.Comment) (*entity.Todo, error) {
	if t, err := obj.Edges.TodoOrErr(); err == nil {
		return t, nil
	}
	return r.Client.Todo.Query().Where(todo.HasCommentsWith(comment.IDField.EQ(obj.ID))).Only(ctx)
}
func (r *commentResolver) Author(ctx context.Context, obj *entity.Comment) (*entity.User, error) {
	if u, err := obj.Edges.AuthorOrErr(); err == nil {
		return u, nil
	}
	return r.Client.User.Query().Where(user.HasCommentsWith(comment.IDField.EQ(obj.ID))).Only(ctx)
}
func (r *memberResolver) Workspace(ctx context.Context, obj *entity.Member) (*entity.Workspace, error) {
	if w, err := obj.Edges.WorkspaceOrErr(); err == nil {
		return w, nil
	}
	return r.Client.Workspace.Query().Where(workspace.HasMembersWith(member.IDField.EQ(obj.ID))).Only(ctx)
}
func (r *memberResolver) User(ctx context.Context, obj *entity.Member) (*entity.User, error) {
	if u, err := obj.Edges.UserOrErr(); err == nil {
		return u, nil
	}
	return r.Client.User.Query().Where(user.HasMembershipsWith(member.IDField.EQ(obj.ID))).Only(ctx)
}
func (r *mutationResolver) DeleteCategory(ctx context.Context, id int) (int, error) {
	if err := r.Client.Category.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}
func (r *mutationResolver) DeleteComment(ctx context.Context, id int) (int, error) {
	if err := r.Client.Comment.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}
func (r *mutationResolver) DeleteMember(ctx context.Context, id int) (int, error) {
	if err := r.Client.Member.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}
func (r *mutationResolver) DeleteProduct(ctx context.Context, id int) (int, error) {
	if err := r.Client.Product.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}
func (r *mutationResolver) DeleteTag(ctx context.Context, id int) (int, error) {
	if err := r.Client.Tag.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}
func (r *mutationResolver) DeleteTodo(ctx context.Context, id int) (int, error) {
	if err := r.Client.Todo.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}
func (r *mutationResolver) DeleteUser(ctx context.Context, id int) (int, error) {
	if err := r.Client.User.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}
func (r *mutationResolver) DeleteWorkspace(ctx context.Context, id int) (int, error) {
	if err := r.Client.Workspace.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}
func (r *todoResolver) Owner(ctx context.Context, obj *entity.Todo) (*entity.User, error) {
	if u, err := obj.Edges.OwnerOrErr(); err == nil {
		return u, nil
	}
	return r.Client.User.Query().Where(user.HasTodosWith(todo.IDField.EQ(obj.ID))).Only(ctx)
}
func (r *todoResolver) Comments(ctx context.Context, obj *entity.Todo) ([]*entity.Comment, error) {
	return r.Client.Comment.Query().Where(comment.HasTodoWith(todo.IDField.EQ(obj.ID))).All(ctx)
}
func (r *todoResolver) Category(ctx context.Context, obj *entity.Todo) (*entity.Category, error) {
	if c, err := obj.Edges.CategoryOrErr(); err == nil {
		return c, nil
	}
	return r.Client.Category.Query().Where(category.HasTodosWith(todo.IDField.EQ(obj.ID))).First(ctx)
}
func (r *todoResolver) Workspace(ctx context.Context, obj *entity.Todo) (*entity.Workspace, error) {
	panic(fmt.Errorf("not implemented: Workspace - workspace"))
}
func (r *userResolver) Comments(ctx context.Context, obj *entity.User) ([]*entity.Comment, error) {
	return r.Client.Comment.Query().Where(comment.HasAuthorWith(user.IDField.EQ(obj.ID))).All(ctx)
}
func (r *userResolver) Memberships(ctx context.Context, obj *entity.User) ([]*entity.Member, error) {
	return r.Client.Member.Query().Where(member.HasUserWith(user.IDField.EQ(obj.ID))).All(ctx)
}
func (r *userResolver) AuditLogs(ctx context.Context, obj *entity.User) ([]*entity.AuditLog, error) {
	return r.Client.AuditLog.Query().Where(auditlog.HasUserWith(user.IDField.EQ(obj.ID))).All(ctx)
}
func (r *workspaceResolver) Members(ctx context.Context, obj *entity.Workspace) ([]*entity.Member, error) {
	return r.Client.Member.Query().Where(member.HasWorkspaceWith(workspace.IDField.EQ(obj.ID))).All(ctx)
}
func (r *Resolver) AuditLog() AuditLogResolver { return &auditLogResolver{r} }
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }
func (r *Resolver) Member() MemberResolver { return &memberResolver{r} }
type auditLogResolver struct{ *Resolver }
type commentResolver struct{ *Resolver }
type memberResolver struct{ *Resolver }
*/
