// Code generated by velox. DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	velox "github.com/syssam/velox"
	"github.com/syssam/velox/dialect/sql"
	"github.com/syssam/velox/tests/integration/predicate"
	ormquery "github.com/syssam/velox/tests/integration/query"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next velox.Querier) velox.Querier {
	return velox.QuerierFunc(func(ctx context.Context, q velox.Query) (velox.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next velox.Querier) velox.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q velox.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The CommentFunc type is an adapter to allow the use of ordinary function as a Querier.
type CommentFunc func(context.Context, *ormquery.CommentQuery) (velox.Value, error)

// Query calls f(ctx, q).
func (f CommentFunc) Query(ctx context.Context, q velox.Query) (velox.Value, error) {
	if q, ok := q.(*ormquery.CommentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect CommentQuery", q)
}

// The TraverseComment type is an adapter to allow the use of ordinary function as Traverser.
type TraverseComment func(context.Context, *ormquery.CommentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseComment) Intercept(next velox.Querier) velox.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseComment) Traverse(ctx context.Context, q velox.Query) error {
	if q, ok := q.(*ormquery.CommentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect CommentQuery", q)
}

// The PostFunc type is an adapter to allow the use of ordinary function as a Querier.
type PostFunc func(context.Context, *ormquery.PostQuery) (velox.Value, error)

// Query calls f(ctx, q).
func (f PostFunc) Query(ctx context.Context, q velox.Query) (velox.Value, error) {
	if q, ok := q.(*ormquery.PostQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect PostQuery", q)
}

// The TraversePost type is an adapter to allow the use of ordinary function as Traverser.
type TraversePost func(context.Context, *ormquery.PostQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePost) Intercept(next velox.Querier) velox.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePost) Traverse(ctx context.Context, q velox.Query) error {
	if q, ok := q.(*ormquery.PostQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect PostQuery", q)
}

// The TagFunc type is an adapter to allow the use of ordinary function as a Querier.
type TagFunc func(context.Context, *ormquery.TagQuery) (velox.Value, error)

// Query calls f(ctx, q).
func (f TagFunc) Query(ctx context.Context, q velox.Query) (velox.Value, error) {
	if q, ok := q.(*ormquery.TagQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect TagQuery", q)
}

// The TraverseTag type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTag func(context.Context, *ormquery.TagQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTag) Intercept(next velox.Querier) velox.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTag) Traverse(ctx context.Context, q velox.Query) error {
	if q, ok := q.(*ormquery.TagQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect TagQuery", q)
}

// The TokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type TokenFunc func(context.Context, *ormquery.TokenQuery) (velox.Value, error)

// Query calls f(ctx, q).
func (f TokenFunc) Query(ctx context.Context, q velox.Query) (velox.Value, error) {
	if q, ok := q.(*ormquery.TokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect TokenQuery", q)
}

// The TraverseToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseToken func(context.Context, *ormquery.TokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseToken) Intercept(next velox.Querier) velox.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseToken) Traverse(ctx context.Context, q velox.Query) error {
	if q, ok := q.(*ormquery.TokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect TokenQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ormquery.UserQuery) (velox.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q velox.Query) (velox.Value, error) {
	if q, ok := q.(*ormquery.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ormquery.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next velox.Querier) velox.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q velox.Query) error {
	if q, ok := q.(*ormquery.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect UserQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q velox.Query) (Query, error) {
	switch q := q.(type) {
	case *ormquery.CommentQuery:
		return &commentQuery{
			tq:  q,
			typ: "Comment",
		}, nil
	case *ormquery.PostQuery:
		return &postQuery{
			tq:  q,
			typ: "Post",
		}, nil
	case *ormquery.TagQuery:
		return &tagQuery{
			tq:  q,
			typ: "Tag",
		}, nil
	case *ormquery.TokenQuery:
		return &tokenQuery{
			tq:  q,
			typ: "Token",
		}, nil
	case *ormquery.UserQuery:
		return &userQuery{
			tq:  q,
			typ: "User",
		}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

// commentQuery is a concrete Query wrapper for *CommentQuery (entity mode).
type commentQuery struct {
	typ string
	tq  *ormquery.CommentQuery
}

func (q commentQuery) Type() string {
	return q.typ
}
func (q commentQuery) Limit(limit int) {
	q.tq.Limit(limit)
}
func (q commentQuery) Offset(offset int) {
	q.tq.Offset(offset)
}
func (q commentQuery) Unique(unique bool) {
	q.tq.Unique(unique)
}
func (q commentQuery) Order(orders ...func(*sql.Selector)) {
	q.tq.Order(orders...)
}
func (q commentQuery) WhereP(ps ...func(*sql.Selector)) {
	preds := make([]predicate.Comment, len(ps))
	for i, p := range ps {
		preds[i] = p
	}
	q.tq.Where(preds...)
}

// postQuery is a concrete Query wrapper for *PostQuery (entity mode).
type postQuery struct {
	typ string
	tq  *ormquery.PostQuery
}

func (q postQuery) Type() string {
	return q.typ
}
func (q postQuery) Limit(limit int) {
	q.tq.Limit(limit)
}
func (q postQuery) Offset(offset int) {
	q.tq.Offset(offset)
}
func (q postQuery) Unique(unique bool) {
	q.tq.Unique(unique)
}
func (q postQuery) Order(orders ...func(*sql.Selector)) {
	q.tq.Order(orders...)
}
func (q postQuery) WhereP(ps ...func(*sql.Selector)) {
	preds := make([]predicate.Post, len(ps))
	for i, p := range ps {
		preds[i] = p
	}
	q.tq.Where(preds...)
}

// tagQuery is a concrete Query wrapper for *TagQuery (entity mode).
type tagQuery struct {
	typ string
	tq  *ormquery.TagQuery
}

func (q tagQuery) Type() string {
	return q.typ
}
func (q tagQuery) Limit(limit int) {
	q.tq.Limit(limit)
}
func (q tagQuery) Offset(offset int) {
	q.tq.Offset(offset)
}
func (q tagQuery) Unique(unique bool) {
	q.tq.Unique(unique)
}
func (q tagQuery) Order(orders ...func(*sql.Selector)) {
	q.tq.Order(orders...)
}
func (q tagQuery) WhereP(ps ...func(*sql.Selector)) {
	preds := make([]predicate.Tag, len(ps))
	for i, p := range ps {
		preds[i] = p
	}
	q.tq.Where(preds...)
}

// tokenQuery is a concrete Query wrapper for *TokenQuery (entity mode).
type tokenQuery struct {
	typ string
	tq  *ormquery.TokenQuery
}

func (q tokenQuery) Type() string {
	return q.typ
}
func (q tokenQuery) Limit(limit int) {
	q.tq.Limit(limit)
}
func (q tokenQuery) Offset(offset int) {
	q.tq.Offset(offset)
}
func (q tokenQuery) Unique(unique bool) {
	q.tq.Unique(unique)
}
func (q tokenQuery) Order(orders ...func(*sql.Selector)) {
	q.tq.Order(orders...)
}
func (q tokenQuery) WhereP(ps ...func(*sql.Selector)) {
	preds := make([]predicate.Token, len(ps))
	for i, p := range ps {
		preds[i] = p
	}
	q.tq.Where(preds...)
}

// userQuery is a concrete Query wrapper for *UserQuery (entity mode).
type userQuery struct {
	typ string
	tq  *ormquery.UserQuery
}

func (q userQuery) Type() string {
	return q.typ
}
func (q userQuery) Limit(limit int) {
	q.tq.Limit(limit)
}
func (q userQuery) Offset(offset int) {
	q.tq.Offset(offset)
}
func (q userQuery) Unique(unique bool) {
	q.tq.Unique(unique)
}
func (q userQuery) Order(orders ...func(*sql.Selector)) {
	q.tq.Order(orders...)
}
func (q userQuery) WhereP(ps ...func(*sql.Selector)) {
	preds := make([]predicate.User, len(ps))
	for i, p := range ps {
		preds[i] = p
	}
	q.tq.Where(preds...)
}
